/**
 * Control ledger — GENERATED by `critics/controls.ts` (`renderLedgerSource`).
 * Do not edit by hand: `controls.test.ts` regenerates the table from the
 * anchors × controls run and fails when this file disagrees with it, so a
 * dimension's `controlStatus` can only come from a measured detection rate.
 *
 * Derived from severity 3 of every corruption family, seed(s) 1,
 * and every purpose-built worsening, over the eight in-song benchmark anchors
 * (ethnic-vocal overflows the song; the owner's song is an anchor but not a
 * control target — see `dimensions/anchors.ts`).
 *
 * The status rule is `critics/sensitivity.ts` — the one rule shared with the
 * adversarial harness and B-08's ledger. `gatingTransforms` names the
 * independent, non-prepared transforms that earned a `gated` status;
 * `reason` says why a dimension is not gated.
 */
import type { LedgerEntry } from "../sensitivity";

export type { LedgerEntry };

export const CONTROL_LEDGER_VERSION = "B05C_CONTROLS_v3" as const;

export const CONTROL_LEDGER: Record<string, LedgerEntry> = {
  density: { status: "gated", strongestControl: "arrival_thinned_below_its_setup", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["arrival_thinned_below_its_setup","piano_one_note_per_bar","strip_bed_to_top_voice"], reason: "3 independent non-prepared transforms passed (arrival_thinned_below_its_setup, piano_one_note_per_bar, strip_bed_to_top_voice) and no clean anchor is blocked" },
  emotionalArcAndTension: { status: "informing", strongestControl: "swap_climax_with_quietest", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["swap_climax_with_quietest"], reason: "1 of 2 independent non-prepared transforms pass" },
  groove: { status: "gated", strongestControl: "unlock_bass_from_kick", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["onset_jitter@3","unlock_bass_from_kick"], reason: "2 independent non-prepared transforms passed (onset_jitter@3, unlock_bass_from_kick) and no clean anchor is blocked" },
  harmony: { status: "gated", strongestControl: "chord_tone_to_non_chord_tone@3", detectionRate: 1, ci95: [0.8456, 1], n: 22, cleanAnchorBlockingRate: 0, gatingTransforms: ["chord_tone_to_non_chord_tone@3","cross_part_clash@3","parallel_perfect_motion","pitch_shift_out_of_key@3","random_pitch"], reason: "5 independent non-prepared transforms passed (chord_tone_to_non_chord_tone@3, cross_part_clash@3, parallel_perfect_motion, pitch_shift_out_of_key@3, random_pitch) and no clean anchor is blocked" },
  idiomaticity: { status: "informing", strongestControl: "piano_wide_voicing", detectionRate: 1, ci95: [0.6306, 1], n: 8, cleanAnchorBlockingRate: 0, gatingTransforms: ["piano_wide_voicing"], reason: "1 of 2 independent non-prepared transforms pass; caught brass_hold_forever 2/2 but on fewer than 8 items (the transform does not apply to every anchor)" },
  melodyAndCounterline: { status: "gated", strongestControl: "top_line_erratic", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["top_line_erratic","top_line_into_vocal_register"], reason: "2 independent non-prepared transforms passed (top_line_erratic, top_line_into_vocal_register) and no clean anchor is blocked" },
  motifRecurrenceAndDevelopment: { status: "informing", strongestControl: "random_pitch", detectionRate: 0.5556, ci95: [0.212, 0.863], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: [], reason: "0 of 2 independent non-prepared transforms pass" },
  orchestration: { status: "gated", strongestControl: "drums_only", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["drums_only","silence_planned_family","tutti_everywhere"], reason: "3 independent non-prepared transforms passed (drums_only, silence_planned_family, tutti_everywhere) and no clean anchor is blocked" },
  performanceRealisation: { status: "gated", strongestControl: "strip_cc_and_quantise", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["strip_cc_and_quantise","velocity_flatten_all"], reason: "2 independent non-prepared transforms passed (strip_cc_and_quantise, velocity_flatten_all) and no clean anchor is blocked" },
  playability: { status: "gated", strongestControl: "bass_roots_only_leaps", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["bass_roots_only_leaps","piano_wide_voicing"], reason: "2 independent non-prepared transforms passed (bass_roots_only_leaps, piano_wide_voicing) and no clean anchor is blocked" },
  register: { status: "gated", strongestControl: "role_inversion@3", detectionRate: 1, ci95: [0.6915, 1], n: 10, cleanAnchorBlockingRate: 0, gatingTransforms: ["octave_displacement@3","role_inversion@3","strings_up_two_octaves"], reason: "3 independent non-prepared transforms passed (octave_displacement@3, role_inversion@3, strings_up_two_octaves) and no clean anchor is blocked" },
  repetitionVsVariation: { status: "informing", strongestControl: "bar_copy_repetition@3", detectionRate: 0.9444, ci95: [0.7271, 0.9986], n: 18, cleanAnchorBlockingRate: 0, gatingTransforms: ["bar_copy_repetition@3"], reason: "1 of 2 independent non-prepared transforms pass; caught chorus_copy 5/5, chorus_copy+develop_chorus_2 5/5 but on fewer than 8 items (the transform does not apply to every anchor)" },
  rhythmicInteraction: { status: "informing", strongestControl: "parallel_doubling@3", detectionRate: 1, ci95: [0.8456, 1], n: 22, cleanAnchorBlockingRate: 0, gatingTransforms: ["parallel_doubling@3"], reason: "1 of 2 independent non-prepared transforms pass" },
  sectionDevelopment: { status: "demoted", strongestControl: "section_swap@3", detectionRate: 0, ci95: [0, 0.1482], n: 23, cleanAnchorBlockingRate: 0, gatingTransforms: [], reason: "strongest claimed transform section_swap@3 detected 0 % of 23 items, below 50 %; caught chorus_copy+develop_chorus_2 5/5 but on fewer than 8 items (the transform does not apply to every anchor)" },
  transitions: { status: "informing", strongestControl: "erase_boundary_events+realise_boundaries", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: [], reason: "0 of 2 independent non-prepared transforms pass (erase_boundary_events+realise_boundaries is prepared: it writes the gesture it then erases)" },
  voiceLeading: { status: "informing", strongestControl: "bass_roots_only_leaps", detectionRate: 1, ci95: [0.6637, 1], n: 9, cleanAnchorBlockingRate: 0, gatingTransforms: ["bass_roots_only_leaps"], reason: "1 of 2 independent non-prepared transforms pass" },
};
