/**
 * The audited data sources (Wave Q — data acquisition, PR-76; audit of
 * 2026-09-09).
 *
 * Every row records what was actually read and where, with the date. Where a
 * layer was not read from a primary source it says `secondary` or `unknown`,
 * and `classifyDataSource()` refuses to clear it. The gaps are the useful
 * part of this file.
 *
 * What "read" means here: the page named in `source` was fetched on `readOn`
 * and the licence wording quoted from it. Pages that answered 403/404/504 on
 * the day are recorded as unread with the URL that was tried, so the next
 * audit knows where to go. Search-engine snippets and papers are `secondary`.
 *
 * Nothing in this file was downloaded. `acquisition` is `NOT_FETCHED` on
 * every row and a test refuses any other value. Nothing here is legal advice.
 */
import type { DataSourceEntry, LicenceEvidence, UnderlyingWorksEvidence } from "./dataSourceRegistry";

const READ_ON = "2026-09-09";

const read = (stated: string, source: string): LicenceEvidence => ({
  stated, source, readOn: READ_ON, confidence: "verified_primary_source",
});
const secondary = (stated: string, source: string): LicenceEvidence => ({
  stated, source, readOn: READ_ON, confidence: "secondary",
});
const unread = (triedUrl: string | null): LicenceEvidence => ({
  stated: null, source: triedUrl ? `not read — ${triedUrl}` : null, readOn: null, confidence: "unknown",
});
/** A source with no per-work marking: the compilation licence is the per-work licence. */
const uniform = (compilation: LicenceEvidence): LicenceEvidence => ({
  ...compilation,
  stated: compilation.stated ? `uniform — ${compilation.stated}` : null,
});
const works = (
  cleared: UnderlyingWorksEvidence["cleared"],
  basis: UnderlyingWorksEvidence["basis"],
  evidence: LicenceEvidence,
): UnderlyingWorksEvidence => ({ ...evidence, cleared, basis });

const claim = (worksCount: number | null, text: string) => ({ works: worksCount, claim: text, measured: false });

export const DATA_SOURCE_REGISTRY: DataSourceEntry[] = [
  // -------------------------------------------------------------------------
  // The backbone, for reference: the one source already admitted (PR-51)
  // -------------------------------------------------------------------------
  {
    id: "PDMX_NO_LICENSE_CONFLICT",
    name: "PDMX — no_license_conflict subset",
    kind: "open_dataset",
    publisher: "Long, Novack, Berg-Kirkpatrick, McAuley (UC San Diego); Zenodo record 15571083",
    url: "https://zenodo.org/records/15571083",
    formats: ["musicxml", "midi"],
    ensemble: "mixed",
    multitrackShare: 20_638 / 222_820,
    styles: ["classical_early", "western_folk", "film_game", "contemporary_pop", "rock", "jazz_blues", "edm_house_techno", "rnb_soul", "hiphop"],
    regions: ["global (MuseScore uploads)"],
    claimedSize: {
      works: 222_820,
      claim: "222,856 admitted rows, 222,820 with a MIDI file; 20,638 multitrack works, 19,588 independent after near-duplicate collapse (PR-65, measured on every file)",
      measured: true,
    },
    // Per-family task totals are PR-65's measured `genres.byFamily` counts
    // over all 16 types (solo works included). Arrangement tasks per family
    // are NOT measured per genre in the profile; they are the measured
    // multitrack work count for the family × the corpus-wide rate of 49.41
    // arrangement tasks per multitrack work — an estimate, and said so.
    // 2,112,944 tasks from the 74 % of works with no genre label are credited
    // to no family at all.
    measuredYieldByStyle: {
      classical_early: { totalTasks: 800_391, arrangementTasks: Math.round(9_150 * (1_019_817 / 20_638)), basis: "measured 800,391 tasks; 9,150 multitrack works × 49.41" },
      western_folk: { totalTasks: 97_827 + 3_096, arrangementTasks: Math.round((683 + 27) * (1_019_817 / 20_638)), basis: "measured folk 97,827 + country 3,096; 710 multitrack works × 49.41" },
      film_game: { totalTasks: 90_240, arrangementTasks: Math.round(781 * (1_019_817 / 20_638)), basis: "measured soundtrack 90,240; 781 multitrack works × 49.41" },
      rock: { totalTasks: 87_263, arrangementTasks: Math.round(619 * (1_019_817 / 20_638)), basis: "measured 87,263; 619 multitrack works × 49.41" },
      contemporary_pop: { totalTasks: 49_110, arrangementTasks: Math.round(437 * (1_019_817 / 20_638)), basis: "measured 49,110; 437 multitrack works × 49.41 — mostly piano-vocal transcription (PR-60)" },
      jazz_blues: { totalTasks: 21_945, arrangementTasks: Math.round(152 * (1_019_817 / 20_638)), basis: "measured 21,945; 152 multitrack works × 49.41" },
      edm_house_techno: { totalTasks: 14_815, arrangementTasks: Math.round(125 * (1_019_817 / 20_638)), basis: "measured electronic 14,815; 125 multitrack works × 49.41 — notation, not production" },
      rnb_soul: { totalTasks: 9_592, arrangementTasks: Math.round(84 * (1_019_817 / 20_638)), basis: "measured 9,592; 84 multitrack works × 49.41" },
      hiphop: { totalTasks: 6_637, arrangementTasks: Math.round(95 * (1_019_817 / 20_638)), basis: "measured 6,637; 95 multitrack works × 49.41" },
    },
    compilationLicence: read(
      "cc-by-4.0 (Zenodo record licence) — covers the compilation, not the works inside it",
      "Zenodo record 15571083 via the public API, recorded in docs/evidence/pdmx-acquisition-live.json (PR-51)",
    ),
    perWorkLicence: read(
      "PDMX.csv `license` column, public domain / CC0 / cc-zero per row, admitted only when the authors' `license_conflict` flag is clear — read on all 254,077 rows",
      "PDMX.csv + subset/no_license_conflict.txt, pdmxIngest.ts PUBLIC_DOMAIN gate (PR-51)",
    ),
    underlyingWorks: works(
      "yes",
      "cc_release_by_author",
      read(
        "The uploader's public-domain / CC0 dedication on MuseScore, cross-checked by the authors against the file's own metadata; rows where the two disagree are excluded",
        "PDMX paper (arXiv 2409.10831) and the subset flag, applied per row in PR-51",
      ),
    ),
    statedRestriction: null,
    cost: { model: "free", note: "already acquired under PR-51; 469 MB verified against Zenodo md5" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["exists: work id, licence string, license_conflict flag, authors' subset membership, dataset and rights digests (datasetRightsProof.ts)"],
    knownLimitations: [
      "Residual: an uploader can dedicate an arrangement of a copyrighted song as public domain; PDMX verifies the metadata agreement, not the composition rights. PR-60 found the corpus's 'pop' is largely piano-vocal transcription — this residual is what that is.",
      "3,197 labelled non-classical multitrack works, 0 Mizrahi/Israeli (PR-65). This is the gap the rest of this registry exists to fill.",
    ],
    auditConfidence: "verified_primary_source",
  },

  // -------------------------------------------------------------------------
  // Cleared on primary sources — read, permissive, works cleared
  // -------------------------------------------------------------------------
  {
    id: "GROOVE_MIDI_DATASET",
    name: "Groove MIDI Dataset (GMD)",
    kind: "open_dataset",
    publisher: "Google LLC / Magenta",
    url: "https://magenta.tensorflow.org/datasets/groove",
    formats: ["midi", "audio_mix"],
    ensemble: "drums_only",
    multitrackShare: null,
    styles: ["reggae_afrobeat", "latin", "middle_eastern_maqam", "hiphop", "edm_house_techno", "rnb_soul", "rock", "contemporary_pop", "jazz_blues", "western_folk"],
    regions: ["USA (studio); genre labels afrobeat, afrocuban, highlife, latin, middleeastern, reggae, hiphop, dance, funk, gospel, soul, punk, rock, pop, jazz, blues, country, neworleans"],
    claimedSize: claim(1_150, "1,150 MIDI files, 13.6 hours, ~22,000 measures, 445,494 hits, 10 drummers (dataset page)"),
    compilationLicence: read(
      "Creative Commons Attribution 4.0 International (CC BY 4.0), made available by Google LLC",
      "https://magenta.tensorflow.org/datasets/groove",
    ),
    perWorkLicence: uniform(read(
      "one licence for the whole release; no per-file variation",
      "https://magenta.tensorflow.org/datasets/groove",
    )),
    underlyingWorks: works(
      "yes",
      "commissioned_original",
      read(
        "Performances recorded by Google on a Roland TD-11 by ten drummers, 'more than 80% of duration coming from hired professionals', following a metronome — original performances, no transcribed works",
        "https://magenta.tensorflow.org/datasets/groove",
      ),
    ),
    statedRestriction: null,
    cost: { model: "free", note: "direct download" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["file id, drummer id, genre label, CC BY 4.0 attribution string, release version"],
    knownLimitations: [
      "Drums only: no pitched context, so it cannot form an arrangement task by itself. Its value is as a groove prior (the afrobeat/reggae/latin/middleeastern grooves are the only cleared production-style material in this whole registry).",
      "Genre labels are the drummers' own session labels — 'middleeastern' is a Western studio drummer's idea of it, not a darbuka player's.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "EXPANDED_GROOVE_MIDI",
    name: "Expanded Groove MIDI Dataset (E-GMD)",
    kind: "open_dataset",
    publisher: "Google LLC / Magenta",
    url: "https://magenta.tensorflow.org/datasets/e-gmd",
    formats: ["midi", "audio_mix"],
    ensemble: "drums_only",
    multitrackShare: null,
    styles: ["reggae_afrobeat", "latin", "hiphop", "edm_house_techno", "rnb_soul", "rock", "contemporary_pop"],
    regions: ["USA (studio)"],
    claimedSize: claim(1_059, "1,059 unique sequences × 43 kits = 45,537 sequences, 444.5 hours of audio; MIDI-only 103 MB (dataset page)"),
    compilationLicence: read("Creative Commons Attribution 4.0 International (CC BY 4.0), Google LLC", "https://magenta.tensorflow.org/datasets/e-gmd"),
    perWorkLicence: uniform(read("one licence for the whole release", "https://magenta.tensorflow.org/datasets/e-gmd")),
    underlyingWorks: works("yes", "commissioned_original", read(
      "Re-recordings of the GMD sequences on a Roland TD-17 across 43 kits — the same commissioned performances",
      "https://magenta.tensorflow.org/datasets/e-gmd",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "direct download; 90 GB with audio" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["as GMD; the MIDI is the same 1,059 sequences, so it adds audio, not works"],
    knownLimitations: ["Symbolically a duplicate of GMD; its 43 kit renderings matter for audio models, not for the arranger."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "RADIF_CORPUS",
    name: "Radif Corpus (Mīrzā ʿAbdollāh radif, Iranian classical)",
    kind: "open_dataset",
    publisher: "Radif Corpus authors (arXiv 2507.10456); Zenodo 10.5281/zenodo.15742125",
    url: "https://arxiv.org/html/2507.10456v1",
    formats: ["midi", "musicxml"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["middle_eastern_maqam"],
    regions: ["Iran (dastgāh system — a neighbour of Arabic/Turkish maqam, not the same system)"],
    claimedSize: claim(228, "228 non-metric gūshehs, 43,441 notes, ~281 minutes; MIDI, CSV and MusicXML (paper)"),
    compilationLicence: read(
      "'All materials are released under a CC-BY 4.0 license, allowing for reuse and adaptation with proper credit.'",
      "https://arxiv.org/html/2507.10456v1 (full text); Zenodo record 15742125 answered 504 on the day",
    ),
    perWorkLicence: uniform(read("one licence statement for all materials", "https://arxiv.org/html/2507.10456v1")),
    underlyingWorks: works("yes", "public_domain_by_age", read(
      "Mīrzā ʿAbdollāh's radif (d. 1918), transcribed from Dariush Talai's edition 'Radif Analysis' — the repertoire is traditional and public domain by age",
      "https://arxiv.org/html/2507.10456v1",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo download" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["gūsheh id, dastgāh, CC BY attribution, note that the transcription derives from Talai's edition (residual: edition rights, see limitations)"],
    knownLimitations: [
      "Residual: Talai's edition is a modern copyrighted book; the dataset authors' CC BY release covers their transcription, and the underlying repertoire is PD by age — the edition's own typographic/editorial rights are a residual to note, not a block.",
      "Monophonic and non-metric: zero arrangement tasks. Its use is a modal/melodic prior for the Middle-Eastern family, not production material.",
      "Dastgāh is not maqam: related interval theory, different repertoire and practice.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "OPENSCORE_LIEDER",
    name: "OpenScore Lieder Corpus",
    kind: "open_dataset",
    publisher: "OpenScore (Gotham, Jonas et al.)",
    url: "https://github.com/OpenScore/Lieder",
    formats: ["musicxml"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["classical_early"],
    regions: ["19th-century Europe"],
    claimedSize: claim(1_200, "over 1,200 songs by more than 100 composers (README)"),
    compilationLicence: read("'These scores are released under Creative Commons Zero (CC0).'", "https://github.com/OpenScore/Lieder"),
    perWorkLicence: uniform(read("every score CC0 (README)", "https://github.com/OpenScore/Lieder")),
    underlyingWorks: works("yes", "public_domain_by_age", read(
      "'collection of songs by 19th century composers' — public domain by age",
      "https://github.com/OpenScore/Lieder",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub clone" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["work id, composer death year ≤ 1955 (Israel: life + 70), CC0 marker"],
    knownLimitations: [
      "Voice + piano: two families, so it is multitrack to the extractor, but the arrangement it teaches is 19th-century accompaniment.",
      "Hosted on MuseScore, so a large share is very probably already inside PDMX; the overlap is unmeasured.",
      "Not a target style. Listed because it is cleared, not because it helps the pop/Mizrahi gap.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MUTOPIA",
    name: "The Mutopia Project",
    kind: "public_domain_archive",
    publisher: "Mutopia Project volunteers",
    url: "https://www.mutopiaproject.org/legal.html",
    formats: ["lilypond", "midi"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["classical_early", "western_folk"],
    regions: ["Europe (classical), some traditional"],
    claimedSize: claim(null, "count not read in this audit; CA2's acknowledgments list 2,451 Mutopia links (globalModelRegistryData.ts)"),
    compilationLicence: read(
      "Per piece, one of: Creative Commons Attribution-ShareAlike (4.0/3.0/2.5/2.0/1.0), Creative Commons Attribution (4.0/3.0/2.5), or Public Domain — each stated to permit commercial use",
      "https://www.mutopiaproject.org/legal.html",
    ),
    perWorkLicence: read(
      "the licence is declared in each piece's header per the legal page; per-piece values must be read at ingest",
      "https://www.mutopiaproject.org/legal.html",
    ),
    underlyingWorks: works("yes", "public_domain_by_age", read(
      "Overwhelmingly composers dead > 70 years; modern contributions are CC-released by their own authors (CA2's residual 1: 18 of 237 composer rows with post-1926 deaths)",
      "https://www.mutopiaproject.org/legal.html + globalModelRegistryData.ts CA2 audit",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "site download / git" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["piece id, header licence string, composer death year, typesetter attribution (CC-BY requires it), share-alike flag"],
    knownLimitations: [
      "Multitrack share unknown; classical chamber and orchestral works exist but were not counted. Yield therefore unknown.",
      "CA2 was trained on it, so as training data for a CA2 fine-tune it adds little new.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "ONAIR_MUSIC_STEMS",
    name: "OnAir Music Dataset (royalty-free stems)",
    kind: "open_dataset",
    publisher: "OnAir Music project / SevagH",
    url: "https://github.com/sevagh/OnAir-Music-Dataset",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["hiphop", "edm_house_techno"],
    regions: ["Canada (lo-fi / electronic)"],
    claimedSize: claim(11, "11 tracks in v4 (README)"),
    compilationLicence: read("Creative Commons Attribution Share Alike 4.0 International — stated for both the audio and the dataset", "https://github.com/sevagh/OnAir-Music-Dataset"),
    perWorkLicence: uniform(read("all tracks under the same licence (README)", "https://github.com/sevagh/OnAir-Music-Dataset")),
    underlyingWorks: works("yes", "cc_release_by_author", read(
      "the OnAir project's own royalty-free songs, released by their creators",
      "https://github.com/sevagh/OnAir-Music-Dataset",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub release" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["track id, CC BY-SA attribution, share-alike propagation note"],
    knownLimitations: [
      "Eleven songs of audio: cleared and irrelevant at this size. Listed to show what a cleared stem source looks like — and that audio stems yield zero symbolic tasks until transcribed.",
      "CC BY-SA share-alike on training data is an open legal question for model weights; counsel before relying on any SA source.",
    ],
    auditConfidence: "verified_primary_source",
  },

  // -------------------------------------------------------------------------
  // Research only — permissive on paper, uncleared works underneath
  // -------------------------------------------------------------------------
  {
    id: "LAKH_MIDI",
    name: "Lakh MIDI Dataset (LMD)",
    kind: "open_dataset",
    publisher: "Colin Raffel",
    url: "https://colinraffel.com/projects/lmd/",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "rnb_soul", "hiphop", "edm_house_techno", "latin", "jazz_blues", "film_game"],
    regions: ["global, scraped"],
    claimedSize: claim(176_581, "176,581 unique MIDI files, 45,129 matched to the Million Song Dataset (project page)"),
    compilationLicence: read("'The Lakh MIDI Dataset is distributed with a CC-BY 4.0 license'", "https://colinraffel.com/projects/lmd/"),
    perWorkLicence: unread("no per-file licence exists — 'scraped from publicly-available sources on the internet'"),
    underlyingWorks: works("no", "copyrighted_transcription", read(
      "'a transcription of the song' — MIDI transcriptions of commercial recordings, scraped; the compilation licence does not reach the songs",
      "https://colinraffel.com/projects/lmd/",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "refused on rights (PR-60), not on cost" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built: no work-level provenance exists"],
    knownLimitations: ["The structural problem of the field (decision-pack §7): the best pop multitrack corpus is uncleared. Benchmark use only, and outputs of Lakh-trained teachers go through teacherOutputsNeedReview."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "SLAKH2100",
    name: "Slakh2100",
    kind: "open_dataset",
    publisher: "Manilow, Wichern, Seetharaman, Le Roux (Northwestern / MERL)",
    url: "https://zenodo.org/records/4599666",
    formats: ["audio_stems", "midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno"],
    regions: ["global (Lakh-derived)"],
    claimedSize: claim(2_100, "2,100 tracks, 145 hours, 187 instrument patches (Zenodo record)"),
    compilationLicence: read("cc-by-4.0 (Zenodo licence id)", "https://zenodo.org/api/records/4599666"),
    perWorkLicence: unread("none — inherited from Lakh"),
    underlyingWorks: works("no", "copyrighted_transcription", read(
      "'synthesized from the Lakh MIDI Dataset v0.1' — the same uncleared transcriptions, rendered",
      "https://zenodo.org/api/records/4599666",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built: Lakh provenance"],
    knownLimitations: ["A rendering does not launder a transcription."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "METAMIDI",
    name: "MetaMIDI Dataset (MMD)",
    kind: "open_dataset",
    publisher: "Jeffrey Ens, Philippe Pasquier (Metacreation Lab)",
    url: "https://github.com/jeffreyjohnens/MetaMIDIDataset",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "rnb_soul", "hiphop", "edm_house_techno", "latin", "jazz_blues"],
    regions: ["global, scraped"],
    claimedSize: claim(436_631, "436,631 MIDI files; 237,236 linked to Spotify (README)"),
    compilationLicence: read(
      "No open licence; restricted Zenodo access on a request form: name, institutional affiliation, research project, and 'an acknowledgement that they will not share nor distribute the dataset'",
      "https://github.com/jeffreyjohnens/MetaMIDIDataset",
    ),
    perWorkLicence: unread("none — 'Scraped artist + title metadata for 221,504 MIDIs'"),
    underlyingWorks: works("no", "copyrighted_transcription", read(
      "scraped MIDI matched to commercial recordings (Spotify, MusicBrainz ids)",
      "https://github.com/jeffreyjohnens/MetaMIDIDataset",
    )),
    statedRestriction: "access only for a named research project; no sharing or distribution",
    cost: { model: "unavailable", note: "research-project request only" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["GigaMIDI and MIDI-RWKV inherit this provenance (model registry)."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MIDICAPS",
    name: "MidiCaps",
    kind: "open_dataset",
    publisher: "AMAAI Lab (SUTD)",
    url: "https://huggingface.co/datasets/amaai-lab/MidiCaps",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno"],
    regions: ["global (Lakh-derived)"],
    claimedSize: claim(168_385, "168,385 MIDI files with text captions (dataset card)"),
    compilationLicence: read("CC-BY-SA-4.0 (dataset card)", "https://huggingface.co/datasets/amaai-lab/MidiCaps/blob/main/README.md"),
    perWorkLicence: unread("none — 'The original MIDI files originate from the Lakh MIDI Dataset'"),
    underlyingWorks: works("no", "copyrighted_transcription", read("Lakh MIDI underneath", "https://huggingface.co/datasets/amaai-lab/MidiCaps/blob/main/README.md")),
    statedRestriction: null,
    cost: { model: "free", note: "Hugging Face" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built: Lakh provenance"],
    knownLimitations: ["The captions are new work; the notes are Lakh's."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "POP909",
    name: "POP909",
    kind: "open_dataset",
    publisher: "Music X Lab (NYU Shanghai)",
    url: "https://github.com/music-x-lab/POP909-Dataset",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "east_asian"],
    regions: ["China (Mandarin pop)"],
    claimedSize: claim(909, "909 songs — MELODY, BRIDGE and PIANO tracks (README; the count is from the paper title, secondary)"),
    compilationLicence: read("MIT licence badge on the repository (the README does not separately license the MIDI)", "https://github.com/music-x-lab/POP909-Dataset"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary(
      "piano arrangements of 909 commercial Chinese pop songs by professional musicians (ISMIR 2020 paper, not read in this audit)",
      "arXiv 2008.07142 (secondary)",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built without the songs' publishers"],
    knownLimitations: ["The best multitrack pop-arrangement dataset in the field is transcriptions of copyrighted songs. Benchmark only."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "NES_MDB",
    name: "NES Music Database (NES-MDB)",
    kind: "open_dataset",
    publisher: "Chris Donahue (UCSD)",
    url: "https://github.com/chrisdonahue/nesmdb",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["film_game"],
    regions: ["Japan/USA (NES games, 1980s–90s)"],
    claimedSize: claim(5_278, "5,278 songs from 397 NES games, 296 composers (README)"),
    compilationLicence: read("MIT licence badge (README)", "https://github.com/chrisdonahue/nesmdb"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", read(
      "parsed from 'assembly code of NES games' — commercial game soundtracks still in copyright",
      "https://github.com/chrisdonahue/nesmdb",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built without the games' publishers"],
    knownLimitations: ["Four monophonic voices: a genuine multitrack arrangement corpus for chiptune, and uncleared."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "VGMIDI",
    name: "VGMIDI",
    kind: "open_dataset",
    publisher: "Lucas N. Ferreira",
    url: "https://github.com/lucasnfe/vgmidi",
    formats: ["midi"],
    ensemble: "solo",
    multitrackShare: null,
    styles: ["film_game"],
    regions: ["global (video game soundtracks)"],
    claimedSize: claim(4_050, "200 labelled + 3,850 unlabelled piano arrangements of video game soundtracks (README)"),
    compilationLicence: unread("https://github.com/lucasnfe/vgmidi — no licence stated"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", read("'piano arrangements of video game soundtracks'", "https://github.com/lucasnfe/vgmidi")),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["Solo piano; no arrangement tasks even if it were cleared."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "YM2413_MDB",
    name: "YM2413-MDB",
    kind: "open_dataset",
    publisher: "Eunjin Choi et al. (KAIST)",
    url: "https://github.com/jech2/YM2413-MDB",
    formats: ["midi", "audio_mix"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["film_game"],
    regions: ["Japan (Sega / MSX games, 1980s)"],
    claimedSize: claim(669, "669 audio and MIDI files from Sega and MSX games (README)"),
    compilationLicence: unread("https://github.com/jech2/YM2413-MDB — README states no licence; the paper says CC BY 4.0 (secondary)"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", read("'music from Sega and MSX PC games in the 80s'", "https://github.com/jech2/YM2413-MDB")),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["Emotion labels are new work; the music is the games'."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "DADAGP",
    name: "DadaGP",
    kind: "open_dataset",
    publisher: "Sarmento, Kumar et al. (QMUL / Dadabots)",
    url: "https://archives.ismir.net/ismir2021/paper/000076.pdf",
    formats: ["guitarpro"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["rock", "contemporary_pop"],
    regions: ["global (GuitarPro tab community)"],
    claimedSize: claim(26_181, "26,181 GuitarPro song scores, 739 genres (paper, secondary)"),
    compilationLicence: secondary("no licence found; the paper discusses the ethics of the tabs' copyright", "ISMIR 2021 paper via search (secondary)"),
    perWorkLicence: unread("none — community tabs"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary("user-made tabs of commercial rock/metal songs", "ISMIR 2021 paper (secondary)")),
    statedRestriction: null,
    cost: { model: "unavailable", note: "request to the authors" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["The only large multitrack band-arrangement symbolic corpus for rock, and uncleared."],
    auditConfidence: "secondary",
  },
  {
    id: "HOOKTHEORY_THEORYTAB",
    name: "Hooktheory TheoryTab database",
    kind: "community_archive",
    publisher: "Hooktheory LLC",
    url: "https://www.hooktheory.com/terms",
    formats: ["midi"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno", "film_game"],
    regions: ["global (community transcriptions of popular songs)"],
    claimedSize: claim(40_000, "over 40,000 chord and melody analyses (site, secondary)"),
    compilationLicence: secondary(
      "Terms of Service: no copying, scraping, bulk download, text-and-data mining or redistribution of the TheoryTab database without a written data licence (terms page answered 403; wording from search index)",
      "https://www.hooktheory.com/terms (403 on the day; secondary)",
    ),
    perWorkLicence: unread("none — crowd-sourced"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary("transcriptions of copyrighted popular songs", "https://www.hooktheory.com/theorytab/about (secondary)")),
    statedRestriction: "no text-and-data mining or bulk download without a written data licence",
    cost: { model: "negotiate", note: "written data licence from Hooktheory; would still not clear the songs" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built without the songs' publishers"],
    knownLimitations: ["Lead-sheet level (melody + Roman-numeral chords): no arrangement task even if cleared."],
    auditConfidence: "secondary",
  },
  {
    id: "WIKIFONIA",
    name: "Wikifonia lead-sheet archive",
    kind: "community_archive",
    publisher: "Wikifonia (offline since 2013)",
    url: "http://www.wikifonia.org/",
    formats: ["musicxml"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["contemporary_pop", "jazz_blues"],
    regions: ["global"],
    claimedSize: claim(null, "the domain now resolves to a domain-sale page; no count"),
    compilationLicence: read("site gone — wikifonia.org is a domain-marketplace page", "http://www.wikifonia.org/"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary("lead sheets of copyrighted songs, withdrawn after publisher pressure", "PR-60 decision-report (secondary)")),
    statedRestriction: null,
    cost: { model: "unavailable", note: "offline" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["Copies circulate as research mirrors; PR-60 refused them and this audit agrees."],
    auditConfidence: "secondary",
  },
  {
    id: "MULTTIPOP",
    name: "MulTTiPop",
    kind: "open_dataset",
    publisher: "gclef-cmu.org (CMU)",
    url: "https://arxiv.org/abs/2607.08756",
    formats: ["midi", "audio_mix"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop"],
    regions: ["USA (pop 1930s–2000s)"],
    claimedSize: claim(572, "572 segments, 3.5 hours, multitrack MIDI aligned to commercial pop audio (abstract, secondary)"),
    compilationLicence: unread("https://arxiv.org/abs/2607.08756 — licence not stated in the abstract"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary("aligned to 'commercial pop audio'", "arXiv 2607.08756 abstract (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "project site" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["A transcription benchmark, not a training source."],
    auditConfidence: "secondary",
  },
  {
    id: "COMMERCIAL_COVER_MIDI_PUBLISHERS",
    name: "Commercial cover-MIDI publishers (Geerdes, Hit Trax and peers)",
    kind: "commercial_catalogue",
    publisher: "Geerdes midimusic; Hit Trax",
    url: "https://www.geerdes.com/",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "rnb_soul", "latin", "jazz_blues"],
    regions: ["Germany, Australia — international pop repertoire"],
    claimedSize: claim(null, "tens of thousands of titles each (not read; both sites refused the connection on the day)"),
    compilationLicence: unread("https://www.geerdes.com/en/faq (ECONNREFUSED); https://www.hittrax.com.au/licensing (TLS error)"),
    perWorkLicence: unread("per-title licence for performance use, not read"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary(
      "professionally programmed MIDI of copyrighted songs, sold under performance/backing-track licences that clear the composition for performance, not for derivative databases",
      "industry practice; the publishers' pages were not read (secondary)",
    )),
    statedRestriction: null,
    cost: { model: "negotiate", note: "a training licence would need the publisher AND each composition's rights-holder" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["publisher licence naming ML training as a permitted use; per-title composition clearance via the relevant society"],
    knownLimitations: ["The closest thing to 'production-style multitrack MIDI of real pop songs' that exists commercially, and doubly uncleared."],
    auditConfidence: "secondary",
  },
  {
    id: "ISRAELI_COVER_MIDI_MARKET",
    name: "Israeli wedding-band / singer MIDI and playback market",
    kind: "commercial_catalogue",
    publisher: "individual Israeli MIDI programmers and playback studios (no central catalogue found)",
    url: "https://www.u-music.co.il/post/midi-files",
    formats: ["midi", "audio_stems"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "contemporary_pop"],
    regions: ["Israel"],
    claimedSize: claim(null, "no catalogue with a count was found; the Hebrew pages found point to scraped international free-MIDI sites or to classical MIDI"),
    compilationLicence: read(
      "u-music.co.il's Hebrew MIDI page recommends BitMidi, Midiworld, FreeMidi.org — scraped sites — and states no licence; dycom-il.com carries a copyright notice covering its (classical/choral) MIDI files",
      "https://www.u-music.co.il/post/midi-files; http://dycom-il.com/midi.html",
    ),
    perWorkLicence: unread("no vendor terms for Mizrahi cover MIDI were located"),
    underlyingWorks: works("no", "copyrighted_transcription", read(
      "cover MIDI of ACUM-administered songs: the programmer's rights and the composition's rights are both required, and neither is granted for ML training by a playback purchase",
      "https://www.acum.org.il/en/ (which rights ACUM administers)",
    )),
    statedRestriction: null,
    cost: { model: "negotiate", note: "programmer licence + ACUM/publisher clearance per song; no price basis exists" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["programmer assignment naming ML training; composition clearance per song (ACUM member or publisher); recording rights are not involved for MIDI"],
    knownLimitations: [
      "Nothing found is a dataset. The Mizrahi MIDI that exists is made for singers' backing tracks and lives on hard drives, not in catalogues with terms.",
      "This is the route that would actually teach Mizrahi production — and it is the most expensive to clear per work.",
    ],
    auditConfidence: "verified_primary_source",
  },

  // -------------------------------------------------------------------------
  // Blocked — non-commercial or AI-training bans, read
  // -------------------------------------------------------------------------
  {
    id: "GIGAMIDI",
    name: "GigaMIDI",
    kind: "open_dataset",
    publisher: "Metacreation Lab (SFU)",
    url: "https://huggingface.co/datasets/Metacreation/GigaMIDI",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno", "hiphop", "jazz_blues", "classical_early"],
    regions: ["global, aggregated (MetaMIDI, Lakh, XMIDI, …)"],
    claimedSize: claim(2_136_218, "2,136,218 unique MIDI files (dataset card)"),
    compilationLicence: read(
      "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0); collected and distributed under Fair Dealing provisions of the Canadian Copyright Act",
      "https://huggingface.co/datasets/Metacreation/GigaMIDI",
    ),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", read("aggregates MetaMIDI, Lakh, XMIDI, top-MAGD, MASD", "https://huggingface.co/datasets/Metacreation/GigaMIDI")),
    statedRestriction: "'You agree to use the GigaMIDI dataset only for non-commercial research or education'",
    cost: { model: "free", note: "gated Hugging Face access" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["Already blocks MIDI-RWKV and MIDI-LLM in the model registry."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MAESTRO",
    name: "MAESTRO v3",
    kind: "open_dataset",
    publisher: "Google LLC / Magenta",
    url: "https://magenta.tensorflow.org/datasets/maestro",
    formats: ["midi", "audio_mix"],
    ensemble: "solo",
    multitrackShare: null,
    styles: ["classical_early"],
    regions: ["International Piano-e-Competition"],
    claimedSize: claim(1_276, "~1,276 performances, ~200 hours (dataset page)"),
    compilationLicence: read("Creative Commons Attribution Non-Commercial Share-Alike 4.0 (CC BY-NC-SA 4.0)", "https://magenta.tensorflow.org/datasets/maestro"),
    perWorkLicence: uniform(read("one licence for the release", "https://magenta.tensorflow.org/datasets/maestro")),
    underlyingWorks: works("yes", "public_domain_by_age", read("17th–early-20th-century repertoire", "https://magenta.tensorflow.org/datasets/maestro")),
    statedRestriction: null,
    cost: { model: "free", note: "direct download" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked before a record matters"],
    knownLimitations: ["Cleared works, NC compilation: the licence blocks, not the music."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "ARIA_MIDI",
    name: "Aria-MIDI",
    kind: "open_dataset",
    publisher: "Louis Bradshaw (loubb)",
    url: "https://huggingface.co/datasets/loubb/aria-midi",
    formats: ["midi"],
    ensemble: "solo",
    multitrackShare: null,
    styles: ["classical_early", "jazz_blues", "contemporary_pop"],
    regions: ["global (solo-piano recordings)"],
    claimedSize: claim(1_186_253, "1,186,253 MIDI files (dataset card)"),
    compilationLicence: read("CC-BY-NC-SA 4.0", "https://huggingface.co/datasets/loubb/aria-midi"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", read("'created by transcribing publicly available solo-piano audio recordings'", "https://huggingface.co/datasets/loubb/aria-midi")),
    statedRestriction: null,
    cost: { model: "free", note: "Hugging Face" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: ["Blocks the Aria model in the model registry."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "LOS_ANGELES_MIDI",
    name: "Los Angeles MIDI Dataset (and the Tegridy / Monster MIDI collections)",
    kind: "open_dataset",
    publisher: "asigalov61 (Project Los Angeles)",
    url: "https://huggingface.co/datasets/projectlosangeles/Los-Angeles-MIDI-Dataset",
    formats: ["midi"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno", "film_game", "classical_early"],
    regions: ["global, scraped"],
    claimedSize: claim(404_714, "404,714 MIDIs in v4.0 (dataset card); Tegridy and Monster are further collections by the same author"),
    compilationLicence: read("cc-by-nc-sa-4.0 (dataset card); Tegridy collections CC BY-NC-SA (search, secondary)", "https://huggingface.co/datasets/projectlosangeles/Los-Angeles-MIDI-Dataset"),
    perWorkLicence: unread("none — 'MIDI scrape'"),
    underlyingWorks: works("no", "copyrighted_transcription", read("scraped; sources not disclosed", "https://huggingface.co/datasets/projectlosangeles/Los-Angeles-MIDI-Dataset")),
    statedRestriction: null,
    cost: { model: "free", note: "Hugging Face" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["cannot be built"],
    knownLimitations: [],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "SYMBTR",
    name: "SymbTr — Turkish makam symbolic collection",
    kind: "open_dataset",
    publisher: "Karaosmanoğlu / MTG-UPF (CompMusic)",
    url: "https://github.com/MTG/SymbTr",
    formats: ["musicxml", "midi"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["middle_eastern_maqam"],
    regions: ["Turkey (Ottoman/Turkish makam)"],
    claimedSize: claim(2_200, "2,200 pieces, 155 makams, 88 usuls, 56 forms, ~865,000 notes (README)"),
    compilationLicence: read("Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International", "https://github.com/MTG/SymbTr"),
    perWorkLicence: uniform(read("one licence for the collection", "https://github.com/MTG/SymbTr")),
    underlyingWorks: works("unknown", "traditional_unattributed", read(
      "'scores are selected from reliable sources'; many are classical Ottoman works PD by age, some 20th-century composers are not — no per-work statement",
      "https://github.com/MTG/SymbTr",
    )),
    statedRestriction: null,
    cost: { model: "negotiate", note: "MTG would have to relicense; the NC is theirs to lift" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked before a record matters; if relicensed: composer death year per piece, makam, usul"],
    knownLimitations: [
      "The best makam-adjacent symbolic corpus in existence, and NC. Turkish makam shares the modal world of Arabic maqam and of much Mizrahi repertoire; a relicensing conversation with MTG is the single highest-value negotiation for the Middle-Eastern family.",
      "Monophonic scores: modal/melodic prior only, no arrangement tasks.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "SARAGA",
    name: "Saraga (Carnatic + Hindustani)",
    kind: "open_dataset",
    publisher: "MTG-UPF (CompMusic)",
    url: "https://github.com/MTG/saraga",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["indian"],
    regions: ["India"],
    claimedSize: claim(357, "249 Carnatic recordings (52.7 h) + 108 Hindustani (43.6 h) (companion site)"),
    compilationLicence: read("data (audio, annotations): Creative Commons Attribution-NonCommercial 4.0 International; code: AGPL-3.0", "https://raw.githubusercontent.com/MTG/saraga/master/LICENSE.md"),
    perWorkLicence: uniform(read("one data licence", "https://raw.githubusercontent.com/MTG/saraga/master/LICENSE.md")),
    underlyingWorks: works("unknown", "copyrighted_transcription", read("concert recordings with artist permission for research", "https://mtg.github.io/saraga/")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["Audio with multitrack stems and no notation: even relicensed it yields no symbolic task."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "CARNATIC_VARNAM",
    name: "Carnatic Varnam Dataset",
    kind: "open_dataset",
    publisher: "MTG-UPF (CompMusic)",
    url: "https://compmusic.upf.edu/carnatic-varnam-dataset",
    formats: ["audio_mix", "esac"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["indian"],
    regions: ["India (Carnatic)"],
    claimedSize: claim(28, "28 solo vocal recordings with taala annotations and machine-readable swara notation (site)"),
    compilationLicence: read("CC BY-NC-ND 3.0 ES ('All content is licensed under a Creative Commons License … unless otherwise specified')", "https://compmusic.upf.edu/carnatic-varnam-dataset"),
    perWorkLicence: uniform(read("site-wide licence", "https://compmusic.upf.edu/carnatic-varnam-dataset")),
    underlyingWorks: works("unknown", "traditional_unattributed", read("varnams are traditional compositions, mostly by composers dead > 70 years; performers' rights in the recordings not addressed", "https://compmusic.upf.edu/carnatic-varnam-dataset")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["The only machine-readable Indian notation this audit found, 28 items, NC-ND."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "JINGJU_SCORES",
    name: "Jingju Music Scores Collection (Beijing opera)",
    kind: "open_dataset",
    publisher: "MTG-UPF (CompMusic); Zenodo 3233843",
    url: "https://zenodo.org/records/3233843",
    formats: ["musicxml"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["east_asian"],
    regions: ["China (jingju)"],
    claimedSize: claim(108, "108 MusicXML scores, 1,084 melodic lines, each with a separate jinghu accompaniment staff (search summary of the record, secondary)"),
    compilationLicence: secondary(
      "the Zenodo record answered 504 on the day; the CompMusic site's default is CC BY-NC-ND 3.0 ES 'unless otherwise specified'",
      "https://compmusic.upf.edu/datasets footer (read) + https://zenodo.org/records/3233843 (not read)",
    ),
    perWorkLicence: unread("https://zenodo.org/records/3233843"),
    underlyingWorks: works("unknown", "traditional_unattributed", secondary("transnotated from printed jianpu editions of traditional arias", "search summary (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["the record's own licence; the printed editions' rights"],
    knownLimitations: ["Voice + jinghu: a real two-part traditional arrangement corpus, tiny, and on the MTG site default it is NC. The record itself must be read before that verdict is final."],
    auditConfidence: "secondary",
  },
  {
    id: "MEERTENS_TUNE_COLLECTIONS",
    name: "Meertens Tune Collections (MTC-ANN, MTC-FS-INST)",
    kind: "open_dataset",
    publisher: "Meertens Instituut / P. van Kranenburg",
    url: "https://github.com/pvankranenburg/MTCFeatures",
    formats: ["kern", "midi"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["western_folk"],
    regions: ["Netherlands"],
    claimedSize: claim(18_360, "MTC-ANN 360 + MTC-FS-INST ~18,000 melodies (README)"),
    compilationLicence: read("Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported", "https://raw.githubusercontent.com/pvankranenburg/MTCFeatures/master/LICENCE_Data"),
    perWorkLicence: uniform(read("one data licence", "https://raw.githubusercontent.com/pvankranenburg/MTCFeatures/master/LICENCE_Data")),
    underlyingWorks: works("yes", "traditional_unattributed", read("Dutch folk songs from historical sources", "https://github.com/pvankranenburg/MTCFeatures")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: [],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "BACH_370_CHORALES_HUMDRUM",
    name: "Bach 370 chorales (craigsapp Humdrum edition)",
    kind: "open_dataset",
    publisher: "Craig Sapp (CCARH)",
    url: "https://github.com/craigsapp/bach-370-chorales",
    formats: ["kern"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["classical_early"],
    regions: ["Germany"],
    claimedSize: claim(370, "370 chorales"),
    compilationLicence: read("Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) on the digital edition", "https://raw.githubusercontent.com/craigsapp/bach-370-chorales/master/LICENSE.txt"),
    perWorkLicence: uniform(read("one licence for the edition", "https://raw.githubusercontent.com/craigsapp/bach-370-chorales/master/LICENSE.txt")),
    underlyingWorks: works("yes", "public_domain_by_age", read("J. S. Bach", "https://github.com/craigsapp/bach-370-chorales")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked; PDMX and Mutopia carry the same chorales under open terms"],
    knownLimitations: ["Recorded as the read example of the KernScores pattern: PD music, NC edition. The KernScores entry below stays unread because every collection there has its own terms."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "THESESSION_DATA",
    name: "The Session — tune data dump",
    kind: "community_archive",
    publisher: "Jeremy Keith (adactio) / thesession.org",
    url: "https://github.com/adactio/TheSession-data",
    formats: ["abc"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["western_folk"],
    regions: ["Ireland, Scotland, and the diaspora"],
    claimedSize: claim(null, "count not read; tens of thousands of tune settings (secondary)"),
    compilationLicence: read(
      "ODC Open Database License (ODbL) — commercial use permitted, share-alike; and, at the top of LICENSE.md: 'You may not use, adapt, modify, or process the material in any way with Large Language Models' (accessibility exception)",
      "https://raw.githubusercontent.com/adactio/TheSession-data/main/LICENSE.md",
    ),
    perWorkLicence: unread("ODbL covers the database, 'not … rights in individual Contents'; per-tune rights are the contributors'"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("mostly traditional tunes; members also post their own compositions", "https://raw.githubusercontent.com/adactio/TheSession-data/main/LICENSE.md")),
    statedRestriction: "may not process the material in any way with Large Language Models",
    cost: { model: "free", note: "blocked by the LLM clause" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["Whether a symbolic-music transformer is a 'Large Language Model' is arguable; the publisher's intent is not. Treated as a ban."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "ZEMERESHET",
    name: "Zemereshet (זמרשת) — early Hebrew song archive",
    kind: "community_archive",
    publisher: "Zemereshet (non-profit)",
    url: "https://www.zemereshet.co.il/",
    formats: ["pdf_notation", "audio_mix"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "jewish_diaspora"],
    regions: ["Israel / pre-state Yishuv (Shirei Eretz Yisrael, not Mizrahi)"],
    claimedSize: claim(null, "thousands of songs (site; no count read)"),
    compilationLicence: read(
      "'published on the site with the courtesy of rights holders and Zemereshet and are intended for private, non-commercial use only'; site states recordings through 1966 are public domain in Israel and works otherwise protected 70 years after the author's death",
      "https://www.zemereshet.co.il/ (terms, Hebrew)",
    ),
    perWorkLicence: unread("per-song rights sit with composers/estates; the site publishes by courtesy"),
    underlyingWorks: works("unknown", "public_domain_by_age", read("composers of the 1880s–1948 repertoire; many died after 1955, so PD status is per composer", "https://www.zemereshet.co.il/")),
    statedRestriction: "private, non-commercial use only; no copying without written permission of Zemereshet and the rights holders",
    cost: { model: "negotiate", note: "the site's terms block; PD-by-age songs could be re-transcribed from PD sources, per composer" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["composer and lyricist death years (≤ 1955 → PD in Israel); source edition; Zemereshet's own written permission if its files are used"],
    knownLimitations: [
      "This is Israeli song, not Mizrahi music, and it is melody with lyrics — sheet music, not production.",
      "Its one durable gift is the rule it states: Israeli PD = author dead 70 years; recordings through 1966 PD.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "DIGITAL_ARABIC_MAQAM_ARCHIVE",
    name: "Digital Arabic Maqām Archive (diarmaqar.net)",
    kind: "open_dataset",
    publisher: "diarmaqar.net (open source)",
    url: "https://diarmaqar.net/en",
    formats: ["theory_only"],
    ensemble: "none",
    multitrackShare: null,
    styles: ["middle_eastern_maqam"],
    regions: ["Arab world (theory sources over nine centuries)"],
    claimedSize: claim(0, "tuning systems, ajnās, maqāmāt, suyūr, intiqālāt — theory, no repertoire (site)"),
    compilationLicence: read("Licensed under CC BY-NC-SA 4.0", "https://diarmaqar.net/en"),
    perWorkLicence: uniform(read("one licence", "https://diarmaqar.net/en")),
    underlyingWorks: works("yes", "not_applicable", read("theory data, no works", "https://diarmaqar.net/en")),
    statedRestriction: null,
    cost: { model: "free", note: "public JSON API; NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked; and it carries no works anyway"],
    knownLimitations: ["Useful as a reference for the universal-style module's maqam pitch systems (PR-66 already has 48 systems); not a training source and NC."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "IRMA_IRANIAN",
    name: "IRMA — Iranian classical audio-MIDI corpus",
    kind: "open_dataset",
    publisher: "IRMA authors (arXiv 2508.19876)",
    url: "https://arxiv.org/pdf/2508.19876",
    formats: ["midi", "audio_mix"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["middle_eastern_maqam"],
    regions: ["Iran"],
    claimedSize: claim(null, "count not read"),
    compilationLicence: secondary("symbolic and analytical components under CC BY-NC 4.0 (search snippet of the paper)", "arXiv 2508.19876 (secondary)"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("unknown", "traditional_unattributed", secondary("Iranian classical performances", "arXiv 2508.19876 (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked on the stated NC; the paper should be read if that changes"],
    knownLimitations: [],
    auditConfidence: "secondary",
  },
  {
    id: "CHORDONOMICON",
    name: "Chordonomicon",
    kind: "open_dataset",
    publisher: "ailsntua (NTUA)",
    url: "https://huggingface.co/datasets/ailsntua/Chordonomicon",
    formats: ["theory_only"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock"],
    regions: ["global (user-submitted chord sheets)"],
    claimedSize: claim(679_807, "679,807 rows of chord progressions (dataset viewer)"),
    compilationLicence: read("cc-by-nc-4.0", "https://huggingface.co/datasets/ailsntua/Chordonomicon"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("no", "copyrighted_transcription", secondary("chord progressions of copyrighted songs from a guitar-tab site (paper, secondary)", "arXiv 2410.22046 (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["Chords only, no melody or notes: not an arrangement source in any case."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MUSDB18",
    name: "MUSDB18 / MUSDB18-HQ",
    kind: "open_dataset",
    publisher: "SigSep (Rafii, Liutkus, Stöter, Mimilakis, Bittner)",
    url: "https://sigsep.github.io/datasets/musdb.html",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "hiphop", "edm_house_techno"],
    regions: ["global"],
    claimedSize: claim(150, "150 full tracks, ~10 hours, 4 stems (site)"),
    compilationLicence: read("'the tracks can only be used for academic purposes'; per-track licences listed (46 MedleyDB tracks CC BY-NC-SA 4.0, 100 from the Mixing Secrets library, 2 Native Instruments, 2 Easton Ellises CC BY-NC-SA 3.0)", "https://sigsep.github.io/datasets/musdb.html"),
    perWorkLicence: read("per-track list published; every source is NC or educational-only", "https://sigsep.github.io/datasets/musdb.html"),
    underlyingWorks: works("no", "copyrighted_transcription", read("original songs by their artists, licensed to the dataset for academic use", "https://sigsep.github.io/datasets/musdb.html")),
    statedRestriction: "academic purposes only",
    cost: { model: "free", note: "Zenodo request" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["The reference stem dataset of the separation field; academic only."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MOISESDB",
    name: "MoisesDB",
    kind: "open_dataset",
    publisher: "Moises.ai",
    url: "https://github.com/moises-ai/moises-db",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "rnb_soul", "hiphop", "latin"],
    regions: ["global"],
    claimedSize: claim(240, "240 tracks (paper, secondary; README gives no count)"),
    compilationLicence: read("'MoisesDB is distributed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)'", "https://github.com/moises-ai/moises-db"),
    perWorkLicence: uniform(read("one licence", "https://github.com/moises-ai/moises-db")),
    underlyingWorks: works("unknown", "copyrighted_transcription", read("songs by artists who licensed them to Moises for the dataset", "https://github.com/moises-ai/moises-db")),
    statedRestriction: null,
    cost: { model: "free", note: "NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: [],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "MEDLEYDB",
    name: "MedleyDB 1.0 / 2.0",
    kind: "open_dataset",
    publisher: "Bittner et al. (NYU MARL)",
    url: "https://medleydb.weebly.com/",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "jazz_blues", "classical_early", "western_folk", "hiphop"],
    regions: ["USA"],
    claimedSize: claim(196, "122 multitracks (1.0), 196 total with 2.0 (site)"),
    compilationLicence: read("CC BY-NC-SA 4.0 — stated on the MUSDB18 page for the 46 MedleyDB tracks it includes; MedleyDB's own page says 'royalty-free' and names no licence", "https://sigsep.github.io/datasets/musdb.html + https://medleydb.weebly.com/"),
    perWorkLicence: unread("per-track metadata on Zenodo, request-gated"),
    underlyingWorks: works("unknown", "copyrighted_transcription", read("original songs by participating artists", "https://medleydb.weebly.com/")),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo request; NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: [],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "SPLICE_SOUNDS",
    name: "Splice Sounds (samples, loops, MIDI)",
    kind: "commercial_pack",
    publisher: "Splice (DCI Sounds)",
    url: "https://splice.com/terms",
    formats: ["midi", "audio_stems"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["edm_house_techno", "hiphop", "contemporary_pop", "rnb_soul", "latin", "reggae_afrobeat", "middle_eastern_maqam"],
    regions: ["global marketplace"],
    claimedSize: claim(null, "millions of sounds (marketing); MIDI packs are a fraction"),
    compilationLicence: read(
      "perpetual right to use Sounds 'in combination with other sounds in music productions to create new recordings'; 'you may not… use the Sounds or portions of Sounds… as source or training material for generative or other types of artificial intelligence models'; no redistribution except inside a New Recording",
      "https://splice.com/terms",
    ),
    perWorkLicence: uniform(read("one Terms of Use for all Sounds", "https://splice.com/terms")),
    underlyingWorks: works("yes", "cc_release_by_author", read("content licensed to Splice by its producers for the Sounds licence", "https://splice.com/terms")),
    statedRestriction: "may not use the Sounds as source or training material for generative or other types of artificial intelligence models",
    cost: { model: "one_time", note: "credits — irrelevant, the AI clause blocks" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["The one marketplace with Middle-Eastern / Mizrahi-flavoured production MIDI packs at scale, and it bans exactly our use."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "TOONTRACK_MIDI_PACKS",
    name: "Toontrack MIDI packs (EZdrummer, EZkeys, EZbass)",
    kind: "commercial_pack",
    publisher: "Toontrack Music AB",
    url: "https://www.toontrack.com/end-user-license-agreement/",
    formats: ["midi"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["rock", "contemporary_pop", "hiphop", "edm_house_techno", "rnb_soul", "latin", "reggae_afrobeat", "jazz_blues", "western_folk"],
    regions: ["Sweden (studio-played packs by named session players)"],
    claimedSize: claim(null, "hundreds of packs, thousands of grooves each (catalogue, not counted)"),
    compilationLicence: read(
      "EULA effective 2026-06-22, §6: prohibited to 'use any Product or Product Component, in whole or in part, including any sounds, MIDI files, or presets related thereto, as a source to develop or train any artificial intelligence technology'; use permitted 'only in the context of creating musical arrangements, recordings of arrangements, audiovisual works, video games and live performances'",
      "https://www.toontrack.com/end-user-license-agreement/",
    ),
    perWorkLicence: uniform(read("one EULA per product; 'Product' includes MIDI packs", "https://www.toontrack.com/end-user-license-agreement/")),
    underlyingWorks: works("yes", "commissioned_original", read("original grooves played by hired drummers/pianists/bassists for Toontrack", "https://www.toontrack.com/end-user-license-agreement/")),
    statedRestriction: "may not use any MIDI file as a source to develop or train any artificial intelligence technology",
    cost: { model: "one_time", note: "irrelevant; blocked" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked; a bespoke licence from Toontrack naming ML training would be the only route"],
    knownLimitations: ["Musically the closest cleared-by-construction source to what the arranger must write (played drums, bass, keys in production styles). Its EULA changed in 2026 to forbid exactly this."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "LOOPMASTERS_LOOPCLOUD",
    name: "Loopmasters / Loopcloud sample and MIDI packs",
    kind: "commercial_pack",
    publisher: "Loopmasters Ltd",
    url: "https://help.loopmasters.com/hc/en-us/articles/27012699080348-Loopmasters-License-Agreement",
    formats: ["midi", "audio_stems"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["edm_house_techno", "hiphop", "contemporary_pop", "reggae_afrobeat", "latin"],
    regions: ["UK marketplace"],
    claimedSize: claim(null, "not counted"),
    compilationLicence: secondary(
      "licence prohibits using any Loopmasters or Loopcloud product 'for the purpose of training, developing or enhancing any content generated by AI systems, machine learning models or any similar technology' (help-centre article; the page answered 403 to this audit, wording from the search index)",
      "https://help.loopmasters.com/hc/en-us/articles/27012699080348-Loopmasters-License-Agreement (403; secondary)",
    ),
    perWorkLicence: unread("per-label licences (e.g. Big Fish Audio) exist and were not read"),
    underlyingWorks: works("yes", "cc_release_by_author", secondary("producer-made content licensed to Loopmasters", "search (secondary)")),
    statedRestriction: "prohibited for the purpose of training, developing or enhancing AI systems or machine learning models",
    cost: { model: "one_time", note: "irrelevant; blocked" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["blocked"],
    knownLimitations: ["Blocked on a secondary reading of an explicit ban — the conservative direction. Reading the page would not change the verdict."],
    auditConfidence: "secondary",
  },

  // -------------------------------------------------------------------------
  // Legal review required — unread licence, or per-work provenance unknown
  // -------------------------------------------------------------------------
  {
    id: "IMSLP_PD_CC0_SUBSET",
    name: "IMSLP — public-domain / CC0 works (incl. the TiMauzi imslp-midi-cc0-1.0 crawl)",
    kind: "public_domain_archive",
    publisher: "Project Petrucci LLC; crawl by TiMauzi on Hugging Face",
    url: "https://imslp.org/wiki/IMSLP:Creative_Commons_and_Performance_Restricted_licenses",
    formats: ["midi", "musicxml", "pdf_notation"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["classical_early", "latin", "western_folk", "jewish_diaspora"],
    regions: ["global; PD Latin (Nazareth d. 1934, Villoldo d. 1919, Gardel d. 1935) and early Jewish/Hebrew art song exist per work"],
    claimedSize: claim(1_113, "1,113 MIDI entries in the CC0/PD crawl of 2024-07 (dataset card); IMSLP itself hosts far more, mostly PDF"),
    compilationLicence: read(
      "Licensing policy: contributor options CC0, CC BY, CC BY-SA, Performance-Restricted variants; the commercially-restrictive CC variants are 'deprecated and their use is strongly discouraged'; NoDerivs no longer allowed; PD by country rule (US pre-1931; EU/Israel life + 70; Canada life + 50 pre-1972 deaths)",
      "https://imslp.org/wiki/IMSLP:Creative_Commons_and_Performance_Restricted_licenses + https://imslp.org/wiki/IMSLP:Copyright_Made_Simple",
    ),
    perWorkLicence: read("per-file licence tag on IMSLP; the HF crawl kept only 'public domain and cc0-1.0'", "https://huggingface.co/datasets/TiMauzi/imslp-midi-cc0-1.0"),
    underlyingWorks: works("unknown", "public_domain_by_age", read(
      "PD status is per country; the crawl includes 'Modern (231)' and 'Early 20th century (28)' entries whose composers may not be dead 70 years — the Israeli rule — so each work needs a death-year check",
      "https://huggingface.co/datasets/TiMauzi/imslp-midi-cc0-1.0",
    )),
    statedRestriction: null,
    cost: { model: "free", note: "per-work check is the cost" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["IMSLP work id, file licence tag (CC0/PD only), composer AND arranger death years ≤ 1955, country-of-PD rule applied, the MIDI's own uploader licence"],
    knownLimitations: [
      "Mostly PDF; the MIDI/MusicXML minority is what the crawl found. Multitrack share unknown.",
      "Not a target style except for PD Latin salon repertoire and the odd Ottoman/Jewish art song; both need a per-work search, none found counted.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "CPDL",
    name: "Choral Public Domain Library (CPDL)",
    kind: "public_domain_archive",
    publisher: "CPDL",
    url: "https://www.cpdl.org/wiki/index.php/ChoralWiki:CPDL",
    formats: ["musicxml", "midi", "pdf_notation"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["classical_early"],
    regions: ["Europe (choral)"],
    claimedSize: claim(null, "tens of thousands of choral editions (not read; every CPDL page answered 403)"),
    compilationLicence: unread("https://www.cpdl.org/wiki/index.php/ChoralWiki:CPDL (403), ChoralWiki:CPDL_License (403), ChoralWiki:Copyright (403)"),
    perWorkLicence: unread("per-edition licence (CPDL licence, CC variants incl. NC, Personal) — not read"),
    underlyingWorks: works("unknown", "public_domain_by_age", unread("PD by age for most; contemporary editions and compositions exist")),
    statedRestriction: null,
    cost: { model: "free", note: "download" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["edition licence string, composer death year, editor's licence"],
    knownLimitations: ["Choral SATB is multitrack to the extractor but not a target style."],
    auditConfidence: "unknown",
  },
  {
    id: "BM_DATASET",
    name: "BMdataset (Baroque LilyPond)",
    kind: "open_dataset",
    publisher: "BMdataset authors (arXiv 2604.10628)",
    url: "https://arxiv.org/abs/2604.10628",
    formats: ["lilypond"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["classical_early"],
    regions: ["Europe (Baroque)"],
    claimedSize: claim(393, "393 LilyPond scores, 2,646 movements, transcribed from Baroque manuscripts (abstract)"),
    compilationLicence: unread("the arXiv page shows the paper's CC BY 4.0, not the dataset's; the data licence was not read"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("yes", "public_domain_by_age", read("Baroque manuscripts", "https://arxiv.org/abs/2604.10628")),
    statedRestriction: null,
    cost: { model: "free", note: "likely; unread" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["data licence; transcriber attribution"],
    knownLimitations: ["Not a target style."],
    auditConfidence: "secondary",
  },
  {
    id: "KERNSCORES_HUMDRUM_DATA",
    name: "KernScores / humdrum-data (per-collection licences)",
    kind: "public_domain_archive",
    publisher: "CCARH Stanford / humdrum-tools",
    url: "https://github.com/humdrum-tools/humdrum-data",
    formats: ["kern"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["classical_early", "western_folk", "east_asian"],
    regions: ["Europe; Essen (Germany, Poland, China); Native American songs (Densmore); child ballads"],
    claimedSize: claim(26_490, "26,490 files, 18.4 M notes (humdrum-data README); kern.ccarh.org states 108,703 files"),
    compilationLicence: read("no umbrella licence: each collection's README and the files' YEC/YEM reference records carry the terms", "https://github.com/humdrum-tools/humdrum-data"),
    perWorkLicence: unread("per collection; only bach-370-chorales was read (NC — see its own entry)"),
    underlyingWorks: works("unknown", "public_domain_by_age", read("PD composers and traditional song for the most part", "https://github.com/humdrum-tools/humdrum-data")),
    statedRestriction: null,
    cost: { model: "free", note: "git" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["collection README licence, YEC/YEM records per file, composer death year"],
    knownLimitations: ["The one read collection is NC; expect the same for other craigsapp editions. Essen's China sub-collection (~2,000 Han folk melodies) is the only East-Asian symbolic material this audit found that could be PD — melody only."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "ESSEN_FOLKSONG_ESAC",
    name: "Essen Folksong Collection (EsAC)",
    kind: "public_domain_archive",
    publisher: "Helmut Schaffrath / Ewa Dahlig-Turek (esac-data.org)",
    url: "https://www.esac-data.org/",
    formats: ["esac", "kern", "midi"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["western_folk", "east_asian", "balkan"],
    regions: ["Germany, Poland, China; minor European collections"],
    claimedSize: claim(20_000, "'20.000 songs and instrumental melodies, mostly from Germany, Poland and China' (site)"),
    compilationLicence: unread("https://www.esac-data.org/ — no licence or terms stated on the site"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("traditional folk melodies from printed collections; the encodings are the Essen project's", "https://www.esac-data.org/")),
    statedRestriction: null,
    cost: { model: "free", note: "download; terms unknown" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["a written statement from esac-data.org on reuse; per-collection printed source and its date"],
    knownLimitations: ["Melody only: zero arrangement tasks. The Balkan share is 'minor collections' — not counted."],
    auditConfidence: "unknown",
  },
  {
    id: "NOTTINGHAM_MUSIC_DATABASE",
    name: "Nottingham Music Database (ABC)",
    kind: "public_domain_archive",
    publisher: "Eric Foxley; ABC conversion by James Allwright / Seymour Shlien",
    url: "https://abc.sourceforge.net/NMD/",
    formats: ["abc"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["western_folk"],
    regions: ["Britain, USA"],
    claimedSize: claim(1_018, "≈1,018 tunes across jigs, hornpipes, reels, waltzes, Ashover (abc.sourceforge.net index)"),
    compilationLicence: read("no general licence stated; for the Ashover set 'the IPR associated with the original NMD format collection reside with Mick Peat'", "https://abc.sourceforge.net/NMD/ + https://ifdo.ca/~seymour/nottingham/nottingham.html"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("traditional dance tunes", "https://ifdo.ca/~seymour/nottingham/nottingham.html")),
    statedRestriction: null,
    cost: { model: "free", note: "download; terms unknown" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["written permission from the compiler's estate or the ABC editors; tune provenance"],
    knownLimitations: ["Melody + chord symbols: needs an arrangement step to become a task, and PR-60 said so."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "KLEZMER_ABC_JC",
    name: "JC's ABC Klezmer tunes (trillian.mit.edu)",
    kind: "community_archive",
    publisher: "John Chambers",
    url: "http://trillian.mit.edu/~jc/music/abc/Klezmer/",
    formats: ["abc"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["jewish_diaspora", "balkan"],
    regions: ["Eastern-European Jewish; some Balkan/Romanian tunes 'that fit the style'"],
    claimedSize: claim(null, "hundreds of ABC files (index listing; not counted)"),
    compilationLicence: read("no licence or copyright statement; 'The files here are used by the folks that I play klezmer music with'", "http://trillian.mit.edu/~jc/music/abc/Klezmer/"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("traditional bulgars, freylekhs, khosidls, horas, niguns — mostly PD by age, some 20th-century composed tunes", "http://trillian.mit.edu/~jc/music/abc/Klezmer/")),
    statedRestriction: null,
    cost: { model: "free", note: "ask the compiler" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["compiler's written permission; per-tune composer where known"],
    knownLimitations: ["Melody only; no arrangement task. The closest thing to a Jewish-diaspora symbolic corpus that exists in the open."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "JEWISH_MIDI_UCI",
    name: "Jewish MIDI files (Dan Hirschberg, UC Irvine)",
    kind: "community_archive",
    publisher: "Dan Hirschberg",
    url: "https://ics.uci.edu/~dan/midi/jewish/",
    formats: ["midi"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["jewish_diaspora", "mizrahi_israeli"],
    regions: ["USA (holiday songs, Hatikva, Hava Nagila, Yerushalayim Shel Zahav)"],
    claimedSize: claim(30, "≈30 MIDI files, last modified 1998 (page)"),
    compilationLicence: read("no licence or usage statement", "https://ics.uci.edu/~dan/midi/jewish/"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("mixed: traditional (Dayenu, Maoz Tsur) and copyrighted (Yerushalayim Shel Zahav — Naomi Shemer, d. 2004)", "https://ics.uci.edu/~dan/midi/jewish/")),
    statedRestriction: null,
    cost: { model: "free", note: "negligible size" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["per-song composer and death year; author's permission"],
    knownLimitations: ["Thirty files. Listed because the search for Israeli MIDI returns it, and to show what 'Israeli' material in the open looks like."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "NLI_PIYUT_SNUNIT",
    name: "National Library of Israel — Piyut and Tefillah site (Snunit) and music collections",
    kind: "public_domain_archive",
    publisher: "National Library of Israel / Snunit",
    url: "https://www.nli.org.il/en/discover/music/jewish-music/piyut",
    formats: ["audio_mix"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "jewish_diaspora", "middle_eastern_maqam"],
    regions: ["Israel; Moroccan, Iraqi, Yemenite, Syrian, Persian, Ashkenazi traditions"],
    claimedSize: claim(null, "thousands of piyut recordings (site; not counted)"),
    compilationLicence: unread("https://www.nli.org.il/en/terms-of-use (403)"),
    perWorkLicence: unread("per-item rights statements on the catalogue, not read"),
    underlyingWorks: works("unknown", "traditional_unattributed", secondary("liturgical melodies, largely traditional; the recordings carry performers' and producers' rights", "search (secondary)")),
    statedRestriction: null,
    cost: { model: "negotiate", note: "NLI licensing desk" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["NLI item rights statement; performer consent; melody provenance (traditional vs composed); a transcription step — there is no notation"],
    knownLimitations: [
      "Audio, not notation: yields no symbolic task without transcription — and it is monophonic singing, not production.",
      "The maqam-based melodic language of Mizrahi music lives here. A negotiated research-then-commercial licence with NLI is the one institutional route this audit found for authentic Middle-Eastern Jewish melody.",
    ],
    auditConfidence: "unknown",
  },
  {
    id: "ACUM_RIGHTS_ROUTE",
    name: "ACUM (Israeli authors', composers' and publishers' society) — licensing route",
    kind: "rights_route",
    publisher: "ACUM",
    url: "https://www.acum.org.il/en/",
    formats: ["theory_only"],
    ensemble: "none",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "contemporary_pop"],
    regions: ["Israel"],
    claimedSize: claim(0, "not a dataset: the body that licenses Israeli compositions (10,000+ members, 98 affiliated societies)"),
    compilationLicence: read("administers performance, mechanical/reproduction and synchronisation rights; no AI/ML or data-mining licence is offered on the site", "https://www.acum.org.il/en/"),
    perWorkLicence: unread("per-work clearance would be per member/publisher"),
    underlyingWorks: works("unknown", "owner_or_assigned_rights", read("the compositions themselves; ACUM does not hold MIDI or recordings", "https://www.acum.org.il/en/")),
    statedRestriction: null,
    cost: { model: "negotiate", note: "no published tariff for ML training; a bespoke licence category would have to be created" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["ACUM licence naming ML training and derivative-model use; per-work list with ISWC; publisher co-signature where applicable"],
    knownLimitations: [
      "Context, not licence: the Israeli Ministry of Justice opinion of 2022-12-18 finds ML training on copyrighted works likely permitted as fair use under Israeli law, excluding datasets built to compete with a single author and outputs that reproduce the works. An opinion, not a statute, and it does not clear a MIDI programmer's rights or a foreign publisher's — it lowers, it does not remove, the need for a licence.",
    ],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "OWNER_OWN_PRODUCTIONS",
    name: "First party — the owner's own productions (DAW sessions, stems, MIDI)",
    kind: "first_party",
    publisher: "the platform owner",
    url: null,
    formats: ["midi", "audio_stems"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "contemporary_pop"],
    regions: ["Israel"],
    claimedSize: claim(null, "not inventoried"),
    compilationLicence: unread("no document yet: an internal rights declaration is the licence"),
    perWorkLicence: unread("per session: co-writers, samples, session musicians, label agreements"),
    underlyingWorks: works("unknown", "owner_or_assigned_rights", unread("own compositions where solely authored; co-written or label-owned works need consent")),
    statedRestriction: null,
    cost: { model: "free", note: "already owned; the cost is the inventory and the per-session declaration" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: [
      "session id and title; every author and their share; publisher/label if any; every sample or loop with its licence (Splice/Toontrack content inside a session is NOT cleared for training even though the song is); session musicians' consent; whether the MIDI is the owner's own performance",
      "tier: HUMAN_ORIGIN_REFERENCE; PROFESSIONAL_HUMAN_GOLD only with evidence of release/credits",
    ],
    knownLimitations: [
      "The only Mizrahi/Israeli *production* multitrack this audit can name that could be cleared this month. Size unknown until inventoried.",
      "Sessions built on third-party packs carry those packs' AI bans into the training set; the record must list every imported loop.",
    ],
    auditConfidence: "unknown",
  },
  {
    id: "PRODUCER_CATALOGUE_LICENCE",
    name: "First party — producers' existing catalogues licensed as HUMAN_ORIGIN_REFERENCE",
    kind: "first_party",
    publisher: "Israeli/Middle-Eastern producers who own their masters and stems",
    url: null,
    formats: ["midi", "audio_stems"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["mizrahi_israeli", "middle_eastern_maqam", "contemporary_pop", "hiphop", "edm_house_techno"],
    regions: ["Israel, Middle East"],
    claimedSize: claim(null, "per negotiation"),
    compilationLicence: unread("no contract exists yet"),
    perWorkLicence: unread("per work: producer's rights (arrangement/MIDI/stems) AND composition rights"),
    underlyingWorks: works("unknown", "owner_or_assigned_rights", unread("cleared only where the producer is also the composer, or the composer signs")),
    statedRestriction: null,
    cost: { model: "negotiate", note: "per-catalogue licence fee or revenue share; no price basis in this audit" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: [
      "written licence naming 'training of machine-learning models and commercial use of derived models' as permitted; work list with authors and ISWC/ISRC; producer's warranty that stems contain no third-party packs with AI bans (or a list of them); tier HUMAN_ORIGIN_REFERENCE; PROFESSIONAL_HUMAN_GOLD only with release evidence",
    ],
    knownLimitations: [
      "The owner's rule distinguishes this from hiring: nobody is paid to write the model's targets; a producer's *existing* catalogue — made for its own release — is licensed as human-origin reference. A commissioned production made to order for training would cross that line and is not proposed.",
    ],
    auditConfidence: "unknown",
  },
  {
    id: "LICENSED_TRAINING_DATA_BROKERS",
    name: "Licensed training-data brokers (Rightsify GCX, Musical AI, Soundverse partner program)",
    kind: "commercial_catalogue",
    publisher: "Rightsify; Musical AI; Soundverse",
    url: "https://rightsify.com/gcx/",
    formats: ["audio_stems", "audio_mix"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["contemporary_pop", "edm_house_techno", "hiphop", "latin", "reggae_afrobeat", "film_game"],
    regions: ["global production-music catalogues"],
    claimedSize: claim(null, "'human-curated, ethically sourced music data'; no counts, formats or prices on the page"),
    compilationLicence: read("marketing page only: 'License Premium Datasets', contact form; no terms published", "https://rightsify.com/gcx/"),
    perWorkLicence: unread("per-asset documentation is promised, not shown"),
    underlyingWorks: works("unknown", "owner_or_assigned_rights", secondary("production-music libraries and independent artists who opted in (industry reporting)", "search (secondary)")),
    statedRestriction: null,
    cost: { model: "negotiate", note: "enterprise pricing; audio-first" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["licence naming symbolic derivation (transcription) and commercial model use; per-asset provenance; whether MIDI/stems are included at all"],
    knownLimitations: ["Audio catalogues built for audio models; nothing found says they hold MIDI. For an arranger they would need transcription, which is not the human's notes."],
    auditConfidence: "secondary",
  },
  {
    id: "CYMATICS_MIDI",
    name: "Cymatics MIDI and sample packs",
    kind: "commercial_pack",
    publisher: "Cymatics LLC",
    url: "https://cymatics.fm/pages/free-sample-packs-license-agreement",
    formats: ["midi", "audio_stems"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["edm_house_techno", "hiphop", "contemporary_pop", "rnb_soul"],
    regions: ["USA marketplace"],
    claimedSize: claim(null, "not counted"),
    compilationLicence: read("the licence page is a request form that emails the agreement; the text is not on the page", "https://cymatics.fm/pages/free-sample-packs-license-agreement"),
    perWorkLicence: unread("per-pack agreement, delivered by email"),
    underlyingWorks: works("unknown", "cc_release_by_author", secondary("'100% royalty free' for use in the buyer's own music; no clause about model training was seen in third-party copies of the agreement — a use-in-compositions licence is not a training licence", "search (secondary)")),
    statedRestriction: null,
    cost: { model: "one_time", note: "pack price; a training licence would be a separate ask" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["the emailed agreement, read; written extension to ML training"],
    knownLimitations: ["Royalty-free ≠ trainable. Until an agreement text naming training is read, unknown."],
    auditConfidence: "secondary",
  },
  {
    id: "GROOVE_MONKEE_MIDI",
    name: "Groove Monkee MIDI drum packs",
    kind: "commercial_pack",
    publisher: "Groove Monkee",
    url: "https://groovemonkee.com/pages/license",
    formats: ["midi"],
    ensemble: "drums_only",
    multitrackShare: null,
    styles: ["rock", "contemporary_pop", "latin", "reggae_afrobeat", "hiphop", "jazz_blues"],
    regions: ["USA"],
    claimedSize: claim(null, "not counted"),
    compilationLicence: unread("https://groovemonkee.com/pages/license (404)"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("unknown", "commissioned_original", unread("played grooves by the vendor's drummers")),
    statedRestriction: null,
    cost: { model: "one_time", note: "pack price" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["licence text; ML clause"],
    knownLimitations: ["Drums only: no arrangement task even if cleared."],
    auditConfidence: "unknown",
  },
  {
    id: "XMIDI",
    name: "XMIDI",
    kind: "open_dataset",
    publisher: "xmusic-project",
    url: "https://github.com/xmusic-project/XMIDI_Dataset",
    formats: ["midi"],
    ensemble: "mixed",
    multitrackShare: null,
    styles: ["contemporary_pop", "rock", "edm_house_techno", "classical_early"],
    regions: ["global"],
    claimedSize: claim(108_023, "108,023 MIDI files with emotion and genre labels (README)"),
    compilationLicence: read("no licence stated anywhere in the repository", "https://github.com/xmusic-project/XMIDI_Dataset"),
    perWorkLicence: unread("none"),
    underlyingWorks: works("unknown", "user_uploads_unverified", read("sources of the MIDI not stated", "https://github.com/xmusic-project/XMIDI_Dataset")),
    statedRestriction: null,
    cost: { model: "free", note: "GitHub" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["a licence; per-file provenance — neither exists"],
    knownLimitations: ["GigaMIDI aggregates it, which suggests scraped provenance; unproven either way."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "ARAB_ANDALUSIAN_CORPUS",
    name: "Arab-Andalusian music corpus (MTG, MusicXML transcriptions)",
    kind: "open_dataset",
    publisher: "MTG-UPF (CompMusic); Zenodo 1291776",
    url: "https://github.com/MTG/arab-andalusian-music",
    formats: ["musicxml", "audio_mix"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["middle_eastern_maqam"],
    regions: ["Morocco (nawba repertoire)"],
    claimedSize: claim(164, "164 concert recordings with MusicXML transcriptions, >125 hours (search summary, secondary); the repo gives no count"),
    compilationLicence: read("no licence stated in the repository; the Zenodo record answered 504", "https://github.com/MTG/arab-andalusian-music"),
    perWorkLicence: unread("https://zenodo.org/records/1291776"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("transcriptions of traditional nawba performances; performers' rights in the recordings not addressed", "https://github.com/MTG/arab-andalusian-music")),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo; MTG site default is NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["the Zenodo record licence; MTG's written position on commercial use"],
    knownLimitations: ["Monophonic maqam-family melody with mizan (rhythmic cycle) annotations — a modal prior, not production."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "TONAS_FLAMENCO",
    name: "TONAS (flamenco a cappella transcriptions) and COFLA",
    kind: "open_dataset",
    publisher: "MTG-UPF / COFLA project",
    url: "https://www.upf.edu/web/mtg/tonas",
    formats: ["midi", "audio_mix"],
    ensemble: "melody_only",
    multitrackShare: null,
    styles: ["flamenco"],
    regions: ["Andalusia"],
    claimedSize: claim(72, "72 a cappella excerpts with manual note transcriptions (secondary)"),
    compilationLicence: unread("https://www.upf.edu/web/mtg/tonas (403)"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("unknown", "copyrighted_transcription", secondary("commercial flamenco recordings, transcribed", "arXiv 1510.04029 (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "MTG; expect NC" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["licence; recording rights"],
    knownLimitations: ["Sung melody only. No flamenco guitar or palmas symbolic source was found in the open."],
    auditConfidence: "unknown",
  },
  {
    id: "JAVANESE_GAMELAN_NOTATION",
    name: "Notation of Javanese Gamelan dataset (Mendeley Data)",
    kind: "open_dataset",
    publisher: "ITS Surabaya (Data in Brief 2024)",
    url: "https://data.mendeley.com/datasets/dvrscpc6vc/1",
    formats: ["pdf_notation"],
    ensemble: "multitrack",
    multitrackShare: null,
    styles: ["southeast_asian"],
    regions: ["Java, Indonesia"],
    claimedSize: claim(35, "35 gendhing in 7 structures, notation for balungan, peking, bonang, kenong/kethuk/kempul/gong (article)"),
    compilationLicence: read("the Data in Brief article is CC BY 4.0; the Mendeley dataset's own licence was not read", "https://pmc.ncbi.nlm.nih.gov/articles/PMC10885543/"),
    perWorkLicence: unread("https://data.mendeley.com/datasets/dvrscpc6vc/1"),
    underlyingWorks: works("unknown", "traditional_unattributed", read("traditional gendhing", "https://pmc.ncbi.nlm.nih.gov/articles/PMC10885543/")),
    statedRestriction: null,
    cost: { model: "free", note: "Mendeley Data" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["dataset licence; an OCR/encoding step from PDF kepatihan notation"],
    knownLimitations: ["PDF, not machine-readable; 35 pieces. Genuinely multi-part, and the only Southeast-Asian ensemble notation found."],
    auditConfidence: "secondary",
  },
  {
    id: "CCMUSIC_CHINESE",
    name: "CCMusic database (Chinese music, audio)",
    kind: "open_dataset",
    publisher: "China Conservatory of Music / CCMusic",
    url: "https://zenodo.org/records/5676893",
    formats: ["audio_mix"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["east_asian"],
    regions: ["China"],
    claimedSize: claim(null, "six datasets (instruments, mode, singing); no symbolic note-level data (TISMIR paper, secondary)"),
    compilationLicence: unread("https://zenodo.org/records/5676893 (not fetched)"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("unknown", "commissioned_original", secondary("recorded by conservatory teams, 'no commodity copyright problem' (paper)", "TISMIR 10.5334/tismir.194 (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["record licence"],
    knownLimitations: ["Audio; no symbolic representation — the paper says so itself."],
    auditConfidence: "secondary",
  },
  {
    id: "CHORO_SONGBOOK_CORPUS",
    name: "Choro Songbook Corpus",
    kind: "open_dataset",
    publisher: "Zenodo 1442765 (2018)",
    url: "https://zenodo.org/records/1442765",
    formats: ["musicxml"],
    ensemble: "melody_plus_chords",
    multitrackShare: null,
    styles: ["latin"],
    regions: ["Brazil"],
    claimedSize: claim(null, "count not read (the record answered 504 on the day)"),
    compilationLicence: unread("https://zenodo.org/records/1442765 (504)"),
    perWorkLicence: unread("not read"),
    underlyingWorks: works("unknown", "public_domain_by_age", secondary("choro repertoire, much of it by composers dead > 70 years (Nazareth d. 1934, Pixinguinha d. 1973 is not)", "general knowledge (secondary)")),
    statedRestriction: null,
    cost: { model: "free", note: "Zenodo" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["record licence; per-tune composer death year; the songbook edition's rights"],
    knownLimitations: ["Lead sheets: an arrangement step is needed before any task."],
    auditConfidence: "unknown",
  },
  {
    id: "MIRTRACKS",
    name: "MIRTracks (royalty-free multitrack audio)",
    kind: "open_dataset",
    publisher: "MIRTracks authors (2025)",
    url: "https://www.sciltp.com/journals/tai/articles/2510001943",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["rock", "edm_house_techno", "contemporary_pop"],
    regions: ["global"],
    claimedSize: claim(null, "240 hours of royalty-free multitrack audio; song count not stated"),
    compilationLicence: read("Creative Commons Attribution 4.0 International (the paper's statement)", "https://www.sciltp.com/journals/tai/articles/2510001943"),
    perWorkLicence: unread("the underlying library and its per-track terms are not named on the page"),
    underlyingWorks: works("unknown", "user_uploads_unverified", read("'royalty-free' — source library not stated", "https://www.sciltp.com/journals/tai/articles/2510001943")),
    statedRestriction: null,
    cost: { model: "free", note: "unknown host" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["the source library's licence; per-track provenance"],
    knownLimitations: ["'Royalty-free' is a business term, not a licence; and it is audio."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "CCMIXTER_STEMS",
    name: "ccMixter stems and samples (per-track CC)",
    kind: "community_archive",
    publisher: "ccMixter / ArtisTech Media",
    url: "https://ccmixter.org/isitlegal",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["contemporary_pop", "hiphop", "edm_house_techno", "rock"],
    regions: ["global community"],
    claimedSize: claim(null, "tens of thousands of uploads (not counted)"),
    compilationLicence: read("every upload carries a CC licence 'marked clearly'; many uploads restrict commercial use, 'many other tracks… allow… commercial use of samples'; no clause about model training", "https://ccmixter.org/isitlegal + http://dig.ccmixter.org/free"),
    perWorkLicence: unread("per track — must be read per upload; commercially-restricted tracks excluded"),
    underlyingWorks: works("unknown", "user_uploads_unverified", read("user uploads; the site does not verify authorship", "https://ccmixter.org/isitlegal")),
    statedRestriction: null,
    cost: { model: "free", note: "per-track filter" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["track id, CC licence (BY or CC0 only), uploader, remix lineage (a remix of an NC source is NC)"],
    knownLimitations: ["Audio stems; the CC BY subset is real but the remix lineage makes per-track review slow."],
    auditConfidence: "verified_primary_source",
  },
  {
    id: "CAMBRIDGE_MT_MIXING_SECRETS",
    name: "Cambridge-MT 'Mixing Secrets' multitrack library",
    kind: "community_archive",
    publisher: "Mike Senior / Cambridge Music Technology",
    url: "https://cambridge-mt.com/ms/mtk/",
    formats: ["audio_stems"],
    ensemble: "audio_stems",
    multitrackShare: null,
    styles: ["rock", "contemporary_pop", "rnb_soul", "hiphop", "edm_house_techno", "jazz_blues", "western_folk"],
    regions: ["global"],
    claimedSize: claim(null, "hundreds of multitracks (not counted; page answered 403)"),
    compilationLicence: unread("https://cambridge-mt.com/ms/mtk/ (403); known to be 'for educational purposes' (secondary)"),
    perWorkLicence: unread("per artist; not read"),
    underlyingWorks: works("unknown", "copyrighted_transcription", secondary("artists' own songs, contributed for mixing practice", "MUSDB18 page: 100 tracks 'originally from The Mixing Secrets Free Multitrack Download Library' (secondary for the terms)")),
    statedRestriction: null,
    cost: { model: "free", note: "educational" },
    acquisition: "NOT_FETCHED",
    rightsRecordNeeds: ["the library's terms; per-artist consent"],
    knownLimitations: ["Expected to be education-only once read; audio in any case."],
    auditConfidence: "unknown",
  },
];

/** The nine sources PR-60 already listed, so the two audits can be diffed. */
export const PR60_CANDIDATES = [
  "LAKH_MIDI", "METAMIDI", "SLAKH2100", "WIKIFONIA", "IMSLP_PD_CC0_SUBSET", "CPDL",
  "GROOVE_MIDI_DATASET", "NOTTINGHAM_MUSIC_DATABASE", "TOONTRACK_MIDI_PACKS",
] as const;
