/**
 * The audited entries (Wave Q — Model Discovery; first pass 2026-09-09, second
 * round 2026-09-09 later the same day).
 *
 * Every row records what was actually read and where. Where a field was not
 * verified from a primary source it says `secondary` or `unknown`, and
 * `classify()` refuses to ship on it. That is the point: the gaps are the
 * useful part of this file.
 *
 * Round 2 read, from primary sources: every repository LICENSE through the
 * GitHub licence API (which returns the file's content), every Hugging Face
 * model-card front matter through the Hub API (`cardData.license`) and, for
 * the Anticipatory Music Transformer, the raw README, config.json and LFS
 * pointers at a pinned revision, plus the repository clone. Dataset cards
 * that answered 401/402 (GigaMIDI, MetaMIDI) are marked secondary. Papers are
 * secondary. Nothing in this file is legal advice.
 *
 * `liveInferenceProven` is true on exactly the entries with an evidence file
 * behind them: a real musical input through the real model on our
 * infrastructure, real notes out, recorded.
 */
import type { ModelEntry } from "./globalModelRegistry";

const unknownLicence = { stated: null, source: null, confidence: "unknown" as const };

export const GLOBAL_MODEL_REGISTRY: ModelEntry[] = [
  // -------------------------------------------------------------------------
  // Multitrack infilling / arrangement — the models closest to our own task
  // -------------------------------------------------------------------------
  {
    id: "COMPOSERS_ASSISTANT_2",
    family: "Composer's Assistant",
    name: "Composer's Assistant 2",
    authorLab: "Martin Malandro (Sam Houston State University)",
    sourceRepository: "https://github.com/m-malandro/composers-assistant-REAPER",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2407.14700",
    releaseDate: "2024-07",
    revision: "v2.1.0 (released 2024-10-09; small model files dated 2024-06-28)",
    parameterCount:
      "large (default shipped): 192,368,256 (measured by model.num_parameters() at load; 769,602,209 bytes fp32); small: ~54M (215,745,913 bytes ÷ 4)",
    architecture:
      "T5ForConditionalGeneration. Large: 16 encoder + 16 decoder layers, d_model 576, d_ff 2304, 12 heads, d_kv 48. Small: 10+10, d_model 384, d_ff 1536, 8 heads. Both gated-GELU, relative attention (4096 buckets / max distance 4096), fp32, transformers 4.31.0 — read from each model/config.json.",
    representation:
      "'unjoined' event vocabulary, exactly 1944 tokens (reproduced from spm_train_functions.get_user_defined_symbols + UnjoinedTokenizer): ;I:0–257 instrument per track, ;R:1–63 repeated-instrument index, ;N:0–127 note-on, ;d:0–192 duration, ;D:0–127 drum hit, ;w:1–192 wait, ;L:1–192 length, ;B:0–7 BPM level, ;M:0–7 loudness level (ppp–fff, one per measure head), ;<extra_id_0..255> T5 span-mask sentinels for infilling, ;<mono>/;<poly>, and ;<instruction_0..511> — 512 control instructions (onset density horizontal/vertical, pitch-class count, pitch-histogram step/leap, onset irregularity, density diversity, rhythmic conditioning). Grid QUANTIZE=(8,6) → 24 steps per quarter, 8-quarter max note length.",
    contextLength: "MAX_LEN 1650 tokens per request (constants.py); relative attention to 4096",
    capabilities: [
      "multitrack_arrangement", "track_completion", "infilling",
      "controllable_generation", "instrument_specific",
    ],
    checkpointAvailable: true,
    checkpointNotes:
      "v2.1.0 assets: composers.assistant.v.2.1.0.zip (683 MB, includes the large model + Python source), CA.v2.1.0.small.model.optional.download.zip (192 MB: model/config.json, model/pytorch_model.bin, generation_config.json, instructions.txt — no separate licence file inside).",
    codeLicense: {
      stated: "MIT License, Copyright (c) 2023 Martin E. Malandro",
      source: "repository LICENSE file, read verbatim via the GitHub contents API",
      confidence: "verified_primary_source",
    },
    weightsLicense: {
      // No separate licence ships with the model. disclaimer.txt says "See also
      // the License", i.e. the repository MIT licence, and adds that the author
      // claims no rights to outputs.
      stated:
        "MIT — the repository LICENSE, and a second in-release Scripts/composers_assistant_v2/license.txt (\"MIT LICENSE, Copyright 2023, 2024 (The authors)\") shipped beside the models; disclaimer.txt: \"We claim no rights to the outputs you generate with the models we've distributed.\"",
      source: "repository LICENSE + in-zip license.txt + disclaimer.txt, all read verbatim; both model zips listed",
      confidence: "verified_primary_source",
    },
    trainingData: {
      stated:
        "\"These models were trained on a set of MIDI files marked as being in the public domain, available under a CC0 license (or otherwise freely available to use without attribution), available under a CC-BY license, or which we had permission from the MIDI file authors to use for training.\" — disclaimer.txt",
      source: "disclaimer.txt + acknowledgments.html (375 KB source list), both read verbatim",
      confidence: "verified_primary_source",
      datasets: [
        "The Mutopia Project (2,451 links; 237 composer rows) — PD classical compositions, CC-BY/CC0/PD typesetting",
        "CocoChorales (Yusong Wu, CC-BY 4.0) — synthetic Bach-style chorales, no underlying work",
        "The Josquin Research Project (josquin.stanford.edu) — Renaissance polyphony, PD",
        "Named contributors who granted permission (Santtu Pesonen, Augustus Knezevich, Bernd Krueger, François Faucher, Henry Howey, HetzlersFakebook, mfiles.co.uk, lutemusic.org, wussu.com, Alain Naigeon, guitarloot.org.uk, Paul Butler, anonymous)",
      ],
      // The dominant share is PD-by-age classical, a synthetic set, and
      // composer-released CC-BY. Two named residuals are recorded under
      // knownLimitations rather than hidden in this boolean.
      underlyingWorksCleared: "yes",
    },
    statedRestriction:
      "Author's own residual-risk clause: \"There is a chance (albeit, in our opinion, a very small one) that the models we've distributed may output copyrighted musical information … You use the models at your own risk.\" Not a commercial restriction.",
    roles: ["FOUNDATION_CANDIDATE", "FINE_TUNE_CANDIDATE", "SPECIALIST", "TEACHER_MODEL"],
    expectedRole:
      "The leading shippable foundation candidate, now on primary-source evidence: multi-track MIDI infilling with fine-grained controls is our exact task, it is a standard HF T5 that runs standalone, and it is the only candidate whose training corpus is dominated by works that are public domain by age.",
    integrationComplexity: "medium",
    knownLimitations: [
      "Residual 1: 18 of 237 Mutopia composer rows have post-1926 death dates — those rows rest on the composer's/arranger's own CC-BY release, not on PD-by-age.",
      "Residual 2: HetzlersFakebook (2 links of ~2,500) is a fake-book site; fake books carry jazz-standard lead sheets, some still in copyright. The author states only 'allowable' files were used.",
      "Corpus is overwhelmingly classical/early music; pop, rock, dance and Hebrew/Mizrahi idioms are essentially absent — a fine-tune on PDMX would not fix that either.",
      "The tokenizer and MIDI→string encoder (midisong.py 100 KB, encoding_functions.py, unjoined_vocab_tokenizer.py, spm_train_functions.py, preprocessing_functions.py) ship as loose Python in the release, not a package; the adapter must vendor them at the pinned revision.",
      "Inference path is a plain XML-RPC wrapper around transformers T5ForConditionalGeneration.generate() (top-p 0.85, encoder_no_repeat_ngram_size, up to 9 re-tries at rising temperature) — runs without REAPER, but the request string is built by REAPER-side code that the adapter must reimplement from encode_midisongbymeasure_with_masks().",
      "Only the 'infill' task is fine-tuned (constants.py: FINETUNE_TASK = 'infill'; 'the plan is to add additional tasks over time').",
      "Instrument vocabulary is 258 GM-ish programs per track (finer than ARRANGER_REMI's 15 families) but there is no section, phrase, harmony-plan or style-grammar token — the deep context of PartGenerationRequestV2 has no slot to enter except the 512 numeric control instructions.",
      "Observed in four real PDMX runs (CPU, 6.5–15.3 s each): one repetition collapse in four at temperature 1.0 (64 notes on a single pitch — the case CA2's own nine-retry loop exists for); the other three produced idiomatic-register, rhythmically plausible parts, one with genuine four-voice polyphony. Harmonic tracking against the context tracks is weak to moderate, and measure-to-measure repetition is high (one trumpet run repeats its bar verbatim). Single-sample quality is not a verdict; the tournament with N seeds and the platform critics is.",
      "Deployed as an isolated Modal worker (services/composers-assistant-worker; cpu=4, no GPU) and proven over HTTPS on 2026-09-09: 401 without the dedicated token, /health verifies the bin sha inside the container, two real infills on the brass score (48 and 39 notes, 5.8–7.9 s inference, warm; ~12 s cold health). The same seed sampled different outputs on the Modal host than locally — CPU T5 sampling is not bit-reproducible across machines, so the tournament runs N seeds and never compares single samples. Evidence: docs/evidence/model-composers-assistant-2-cloud.json.",
      "First live tournament (2026-09-09, 12 classical PDMX tasks × 3 seeds, docs/evidence/model-tournament-live.json): CA2+CTX 73.5 mean vs the platform's CONTEXT_AWARE_ARRANGER 64.6 and REFERENCE 63.0 on the proxy judge (human anchor 90.4); wins bass/keys/organ/reed, loses strings/brass; three times the reference's playability errors (0.25 vs 0.08 per entry) → do_not_promote until a blind listening comparison. Nothing non-classical has been measured.",
      "A 2025 follow-up (arXiv 2506.13001, 'Personalizable Long-Context Symbolic Music Infilling with MIDI-RWKV') shows CA2 admits low-data per-user fine-tuning; it also introduces MIDI-RWKV (GigaMIDI-trained, see MIDI_RWKV) as the comparison.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: true,
    liveEvidence: "docs/evidence/model-composers-assistant-2-live.json",
  },
  {
    id: "ANTICIPATORY_MUSIC_TRANSFORMER",
    family: "Anticipation",
    name: "Anticipatory Music Transformer (music-small/medium/large-800k)",
    authorLab: "John Thickstun, David Hall, Chris Donahue, Percy Liang (Stanford CRFM)",
    sourceRepository: "https://github.com/jthickstun/anticipation",
    huggingFace: "https://huggingface.co/stanford-crfm/music-large-800k",
    paper: "https://arxiv.org/abs/2306.08620",
    releaseDate: "2023-06 (small/medium); 2024-03-13 (large-800k)",
    revision:
      "code af37397922665a0fb8d474d7988b0f3755a38d45 (2024-03-18; module shas pinned in services/anticipatory-worker/model_manifest.json); weights stanford-crfm/music-large-800k @ e206a88d4658661c2757573eae724d5b27213824, model.safetensors sha256 83fb8b9546eacce77a90bb10006b3f569ba342361dce046d078cf2429975e09f (3,120,598,456 bytes); medium-800k @ 93b6eb7e pytorch_model.bin sha256 7af65dba… (1,438,866,529 bytes); small-800k @ fa800530 sha256 45af5006… (512,433,185 bytes)",
    parameterCount:
      "large: 780M (model card; 36 layers, n_embd 1280, 20 heads — config.json read); medium: 360M (24 layers, 1024, 16 heads); small: 128M. Measured at load in the live evidence.",
    architecture:
      "GPT2LMHeadModel (decoder-only), n_positions 1024, gelu_new, scale_attn_by_inverse_layer_idx, fp32; sampled by the repository's own loop (no KV cache: every token re-reads up to 1024 tokens). Trained with anticipation: control events interleaved into the causal stream up to DELTA = 5 s ahead of the events they constrain.",
    representation:
      "arrival-time events, three tokens each: onset (10 ms bins, ≤ 100 s), duration (10 ms bins, ≤ 10 s), note = instrument×128 + pitch (129 instruments: GM 0–127 + drums as 128); a parallel control block of the same shape; REST padding once per second; vocabulary 55,028 (the large checkpoint's embedding has 55,030 rows, the two extra never sampled). Velocity is not modelled. Track identity is not modelled: tracks sharing a program are one instrument.",
    contextLength: "1024 tokens = 341 events; the sampler keeps the last 1017 tokens as a Markov window",
    capabilities: ["infilling", "accompaniment", "track_completion", "controllable_generation", "multitrack_arrangement"],
    checkpointAvailable: true,
    checkpointNotes:
      "Hub org stanford-crfm lists music-{small,medium,large}-{100k,800k} plus small-ar / small-ar-inter variants; all apache-2.0 in cardData; none gated. The large-800k card names a broader corpus than the paper's (see trainingData). Chosen for the worker: large-800k (strongest); medium-800k (Lakh-only, 1.4 GB) recorded as the fallback.",
    codeLicense: {
      stated: "Apache License, Version 2.0 (LICENSE.txt)",
      source: "repository LICENSE.txt read verbatim from a clone at af373979… and via the GitHub licence API (spdx Apache-2.0); README: \"This project is licensed under the terms of the Apache License, Version 2.0.\"",
      confidence: "verified_primary_source",
    },
    weightsLicense: {
      stated: "apache-2.0 (model card front matter of music-large-800k, music-medium-800k and music-small-800k)",
      source: "https://huggingface.co/stanford-crfm/music-large-800k/raw/e206a88d…/README.md (sha256 276146c8…) and the Hub API cardData for the three sizes",
      confidence: "verified_primary_source",
    },
    trainingData: {
      stated:
        "large-800k: \"trained for 800k steps on arrival-time encoded music from the Lakh MIDI dataset, MetaMidi dataset, and transcripts of the FMA audio dataset and 450k commercial music records (transcribed using Google Magenta's ISMIR 2022 music transcription model)\"; medium/small-800k: \"arrival-time encoded music from the Lakh MIDI dataset\". Lakh: \"distributed with a CC-BY 4.0 license\", \"scraped from publicly-available sources on the internet\", the author \"did not transcribe any of the MIDI files\" and attribution \"is not feasible\".",
      source: "the three model cards (publisher's own statements, read verbatim) + https://colinraffel.com/projects/lmd/ (read verbatim); MetaMIDI's terms not re-read this round",
      confidence: "verified_primary_source",
      datasets: ["Lakh MIDI (LMD-full, 176,581 files)", "MetaMIDI (large-800k only)", "FMA audio transcripts (large-800k only)", "450k commercial music records, transcribed (large-800k only)"],
      // The exact case the brief names: the dataset licence is permissive and
      // the underlying transcriptions are of copyrighted recordings — and the
      // large model adds transcriptions of commercial records outright.
      underlyingWorksCleared: "no",
    },
    statedRestriction:
      "None stated by the publisher. The restriction is structural: Lakh MIDI files are transcriptions of copyrighted recordings (the CC-BY-4.0 covers the compilation), and the large model's 450k commercial records are copyrighted works by definition.",
    roles: ["SHADOW_CHALLENGER", "BENCHMARK_ONLY", "ARCHITECTURE_REFERENCE", "TEACHER_MODEL"],
    expectedRole:
      "The round-2 shadow challenger: the strongest public infilling-with-control model that actually runs, on our exact task once the note slot is masked to the held-out instrument. Never ships; never routes to a user; its outputs are benchmark lines and reviewed teacher material at most. The anticipation trick — interleaving control events ahead of the notes they constrain — remains the design to borrow for conditioning ARRANGER_FM on a harmony plan.",
    integrationComplexity: "low",
    knownLimitations: [
      "Lakh/MetaMIDI/transcribed-commercial-records training: not shippable as weights however permissive the model licence looks; RESEARCH_ONLY is the ceiling, and TEACHER outputs need legal review before any student trains on them.",
      "Upstream `generate` writes 'the rest of the band'; our worker adds an instrument mask on the note slot so it writes only the held-out GM program. The model has no instrument-conditioning token, so this is constrained decoding, not an instruction it read.",
      "Single-stream event model with no track identity, no velocity, no bar or metre notion: the window is seconds, tempo changes are flattened to the file's first tempo, tracks sharing a program merge, and every generated note gets a constant velocity.",
      "The vocabulary's clock is 100 s and the context 341 events: the worker translates the window under a 20 s history / 8 s lookahead, and in dense scores the model sees only the last ~340 events.",
      "No KV cache in the upstream sampler: every sampled token re-reads the whole context, so an 8-bar part costs hundreds of full forward passes — a GPU job (A10G) where CA2 is a CPU job.",
      "Proven live on 2026-09-09 on the deployed Modal worker (services/anticipatory-worker, A10G): real PDMX brass score, tuba and trumpet held out, real notes back; see docs/evidence/model-anticipatory-music-transformer-live.json for the numbers, the cost and the quality reading.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: true,
    liveEvidence: "docs/evidence/model-anticipatory-music-transformer-live.json",
  },
  {
    id: "MIDI_GPT",
    family: "MMM / MIDI-GPT",
    name: "MIDI-GPT (yellow_small / yellow_medium / prism_medium / expressive_medium)",
    authorLab: "Metacreation Lab, Simon Fraser University",
    sourceRepository: "https://github.com/Metacreation-Lab/MIDI-GPT",
    huggingFace: "https://huggingface.co/Metacreation/MIDI-GPT",
    paper: "https://arxiv.org/abs/2501.17011",
    releaseDate: "2025-01 (paper); checkpoints updated 2026-07-28",
    revision: "HF 3aa5748ba68e32a43c70ddc66b5e595069484532 (2026-07-28): yellow_small-final, yellow_medium-final, prism_medium-step376000, expressive_medium-step90000 (.safetensors) — not installed",
    parameterCount: "unverified (GPT-2 class small/medium)",
    architecture: "GPT-2 decoder over MMM-style track-separated bar tokens; 4/8-bar (yellow) and 4–16-bar (prism) infill contexts; per-bar and per-track attribute controls (note density, polyphony, duration; prism adds key, pitch range, silence, pitch-class set, genre; expressive adds sub-grid delta tokens and velocity/microtiming)",
    representation: "MMM track-separated MIDI tokens with attribute controls",
    contextLength: "model_dim = context in bars (4–16)",
    capabilities: [
      "multitrack_arrangement", "track_completion", "infilling",
      "controllable_generation", "expressive_performance", "instrument_specific",
    ],
    checkpointAvailable: true,
    checkpointNotes:
      "Two final checkpoints (yellow) and two mid-training ones (prism 376k/500k, expressive 90k/500k) as of 2026-07-28; the repository now ships an InferenceEngine.from_pretrained(), an HTTP REST server and an OSC server.",
    codeLicense: {
      stated: "MIT License, Copyright (c) 2026 Metacreation Lab",
      source: "repository LICENSE read via the GitHub licence API",
      confidence: "verified_primary_source",
    },
    weightsLicense: {
      stated: "cc-by-nc-4.0 — \"Creative Commons Attribution-NonCommercial 4.0 International\"",
      source: "https://huggingface.co/Metacreation/MIDI-GPT model card front matter (raw README read)",
      confidence: "verified_primary_source",
    },
    trainingData: {
      stated: "GigaMIDI v2.0.0 (Metacreation/GigaMIDI), per the model card; GigaMIDI's own card states acquisition under Canadian Fair Dealing for research and non-commercial use",
      source: "MIDI-GPT model card (read); GigaMIDI dataset card answered 401 this round — its terms are recorded from the first pass",
      confidence: "secondary",
      datasets: ["GigaMIDI v2.0.0"],
      underlyingWorksCleared: "no",
    },
    statedRestriction:
      "Weights CC-BY-NC-4.0: non-commercial use only. GigaMIDI acquired under Fair Dealing, limiting it to research and non-commercial use.",
    roles: ["SHADOW_CHALLENGER", "BENCHMARK_ONLY", "ARCHITECTURE_REFERENCE"],
    expectedRole:
      "The most controllable multitrack infiller in the field and a serious challenger to beat on the benchmark — its bar-level attribute controls are the closest thing to our V2 context anyone has tokenised. Its weights can never ship, and its outputs may not be assumed safe as training data.",
    integrationComplexity: "medium",
    knownLimitations: [
      "Non-commercial at the weights layer and the data layer. Fine-tuning does not remove it.",
      "Two of the four checkpoints are explicitly mid-training and expected to be superseded.",
      "Not run this round: the budget went to the one challenger that is licensed for research inference without an NC term on the weights. It is the next shadow arm to add, on the same worker pattern.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "REMI_Z_ARRANGER",
    family: "Unifying Symbolic Music Arrangement (REMI-z)",
    name: "Track-Aware Reconstruction arrangement model (music2music)",
    authorLab: "Longshen Ou, Jingwei Zhao, Ziyu Wang, Gus Xia, Qihao Liang, Ye Wang (NUS / Music X Lab)",
    sourceRepository: "https://github.com/Sonata165/music2music_code",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2408.15176",
    releaseDate: "2025-11 (NeurIPS 2025); code pushed 2025-11-10; REMI-z tokenizer updated 2025-09-09",
    revision: null,
    parameterCount: "unverified",
    architecture: "context-aware segment-level reconstruction: the model rebuilds multitrack music from disentangled content (notes) and style (instrumentation); pre-train then fine-tune per task (band arrangement, piano reduction, drum arrangement; context 768, batch 24, lr 1e-4)",
    representation: "REMI-z — bar sequences ending in b-1, notes grouped by instrument within the bar (track-wise continuity over global time order)",
    contextLength: "768 tokens (fine-tune hparams)",
    capabilities: [
      "multitrack_arrangement", "orchestration", "track_completion",
      "accompaniment", "instrument_specific", "controllable_generation",
    ],
    checkpointAvailable: false,
    checkpointNotes:
      "Code is public (music2music_code: pretrain.py, lightning_train.py, reinst.py, drum_arrange.py) and the REMI-z tokenizer is an installable package (Sonata165/REMI-z, MIT). No checkpoint link in either README as of 2026-09-09; the model must be trained from `LAMD_to_remi.py` — pre-training on a Lakh-derived corpus.",
    codeLicense: {
      stated: "REMI-z tokenizer: MIT (LICENSE, Copyright (c) 2024 Sonata165). music2music_code: no licence file (GitHub reports none).",
      source: "GitHub licence API for both repositories",
      confidence: "verified_primary_source",
    },
    weightsLicense: unknownLicence,
    trainingData: {
      stated: "pre-training script LAMD_to_remi.py (a Lakh-derived MIDI set); fine-tuning data per task not named in the README",
      source: "music2music_code README read via the GitHub API",
      confidence: "secondary",
      datasets: ["Lakh-derived pre-training corpus (LAMD)"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE", "FOUNDATION_CANDIDATE"],
    expectedRole:
      "The most directly relevant published design: one model handling band arrangement, piano reduction and drum arrangement, with any-to-any instrumentation at inference. REMI-z is the representation to measure ARRANGER_REMI against — the code is now public, so that comparison can be run without weights.",
    integrationComplexity: "high",
    knownLimitations: [
      "No checkpoint published. Without weights this is a design and a tokenizer to learn from, not a model to run.",
      "The model code carries no licence file; a training run on it would need the authors' terms first.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "MOONBEAM",
    family: "Moonbeam",
    name: "Moonbeam — MIDI foundation model (absolute + relative attributes)",
    authorLab: "Zixun Guo et al. (Centre for Digital Music, QMUL)",
    sourceRepository: "https://github.com/guozixunnicolas/moonbeam-midi-foundation-model",
    huggingFace: "https://huggingface.co/guozixunnicolas/moonbeam-midi-foundation-model",
    paper: "https://arxiv.org/abs/2505.15559",
    releaseDate: "2025-05; repo pushed 2025-06-12",
    revision: null,
    parameterCount: "unverified (the paper reports two sizes; not read from a config this round)",
    architecture: "LLaMA-recipe transformer with Multidimensional Relative Attention (MRA) over a domain-inspired compound tokenization; two fine-tuning architectures (understanding; conditional generation incl. infilling, 'full anticipatory capabilities')",
    representation: "compound MIDI tokens carrying absolute and relative attributes (onset, duration, pitch, velocity, instrument)",
    contextLength: "512–848 tokens in the inference scripts",
    capabilities: ["infilling", "accompaniment", "controllable_generation", "multitrack_arrangement", "embeddings_retrieval"],
    checkpointAvailable: true,
    checkpointNotes:
      "The pre-trained checkpoint is on the Hub (cardData license apache-2.0); the README's 'Conditional Generation Checkpoint (Commu)' and 'Unconditional Generation Checkpoint (ATEPP-Bach)' links are literally 'https://TODO' — the infilling fine-tune, the part relevant to us, is not published.",
    codeLicense: { stated: "Apache-2.0", source: "GitHub licence API (repository LICENSE)", confidence: "verified_primary_source" },
    weightsLicense: { stated: "apache-2.0", source: "Hub API cardData.license of guozixunnicolas/moonbeam-midi-foundation-model", confidence: "verified_primary_source" },
    trainingData: {
      stated: "\"pretrained on a large and diverse collection of MIDI data totaling 81.6K hours of music and 18 billion tokens\" — composition not named in the README or abstract",
      source: "README (GitHub API) and arXiv abstract",
      confidence: "secondary",
      datasets: ["undisclosed 81.6k-hour MIDI collection"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["FOUNDATION_CANDIDATE", "FINE_TUNE_CANDIDATE", "ARCHITECTURE_REFERENCE"],
    expectedRole:
      "The newest general MIDI foundation with an anticipatory infilling fine-tune in its design; if its corpus resolves and the conditional checkpoint is published it becomes a real foundation candidate. Until then it is an architecture to read (MRA, compound tokens) and a pre-trained base one would have to fine-tune oneself.",
    integrationComplexity: "high",
    knownLimitations: [
      "The infilling / conditional-generation checkpoint is unpublished ('https://TODO'); only the base is available.",
      "81.6k hours of MIDI is more than every clean public corpus combined; the provenance question is open and decisive.",
      "Custom training/inference stack (a vendored llama_recipes / transformers_minimal) — heavier to isolate than a stock HF model.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "MIDI_RWKV",
    family: "MIDI-RWKV",
    name: "MIDI-RWKV (RWKV-7 infilling model)",
    authorLab: "Christian Zhou-Zheng, Philippe Pasquier (Metacreation Lab, SFU)",
    sourceRepository: "https://github.com/christianazinn/MIDI-RWKV",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2506.13001",
    releaseDate: "2025-06; repo pushed 2026-01-24",
    revision: null,
    parameterCount: "unverified (small; edge-device target)",
    architecture: "RWKV-7 linear-attention model for long-context multitrack infilling; state tuning and LoRA for very-low-sample style adaptation; rwkv.cpp / GGML inference",
    representation: "MMM-style track/bar tokens",
    contextLength: "long (linear architecture); unverified",
    capabilities: ["infilling", "multitrack_arrangement", "track_completion", "controllable_generation", "style_conditioned"],
    checkpointAvailable: true,
    checkpointNotes: "midi_rwkv.pth is committed in the repository; conversion to GGML and a rwkv.cpp build are required to run.",
    codeLicense: { stated: "MIT", source: "GitHub licence API (repository LICENSE)", confidence: "verified_primary_source" },
    weightsLicense: { stated: "MIT (the repository licence; the weights file ships inside the repository with no separate terms)", source: "repository LICENSE + README", confidence: "secondary" },
    trainingData: {
      stated: "GigaMIDI (\"The pretraining dataset used: GigaMIDI\"); GigaMIDI is acquired under Canadian Fair Dealing, research and non-commercial use only",
      source: "MIDI-RWKV README (read); GigaMIDI terms from the first pass (dataset card 401 this round)",
      confidence: "secondary",
      datasets: ["GigaMIDI"],
      underlyingWorksCleared: "no",
    },
    statedRestriction: "GigaMIDI: acquired under Fair Dealing; research and non-commercial use only.",
    roles: ["SHADOW_CHALLENGER", "ARCHITECTURE_REFERENCE"],
    expectedRole:
      "Already BLOCKED_LICENSE in the platform catalogue (MIDI_RWKV); recorded here so the registry and the catalogue agree. Its state-tuning recipe for per-user adaptation is the idea worth keeping.",
    integrationComplexity: "medium",
    knownLimitations: ["GigaMIDI-trained: non-commercial at the data layer; fine-tuning does not remove it.", "Non-standard runtime (rwkv.cpp) — not a stock HF model."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "STRUCTURED_ARRANGEMENT",
    family: "Structured Multi-Track Accompaniment Arrangement",
    name: "Structured Multi-Track Accompaniment Arrangement via Style Prior Modelling",
    authorLab: "Jingwei Zhao, Gus Xia, Ziyu Wang, Ye Wang (NUS / Music X Lab) — NeurIPS 2024",
    sourceRepository: "https://github.com/zhaojw1998/Structured-Arrangement-Code",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2410.15079",
    releaseDate: "2024-10",
    revision: null,
    parameterCount: "unverified",
    architecture: "two stages: lead sheet → piano accompaniment (AccoMontage lineage), then a style-prior orchestration model over a multitrack autoencoder, with instrument-choice control",
    representation: "piano-roll style multitrack latents",
    contextLength: "whole song",
    capabilities: ["accompaniment", "orchestration", "multitrack_arrangement", "controllable_generation"],
    checkpointAvailable: true,
    checkpointNotes: "Checkpoints on Google Drive (README link); processed LMD and Slakh2100 sets also on Google Drive.",
    codeLicense: { stated: "no licence file (GitHub reports none)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: {
      stated: "LMD (Lakh) for the prior model, Slakh2100 for the autoencoder (README)",
      source: "repository README (read)",
      confidence: "secondary",
      datasets: ["Lakh MIDI (LMD)", "Slakh2100"],
      underlyingWorksCleared: "no",
    },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE", "BENCHMARK_ONLY"],
    expectedRole:
      "The strongest published lead-sheet → full-band arranger; its orchestration function with instrument control is the closest academic analogue to our Wave-6 orchestration plan. Lakh-trained and unlicensed code: a benchmark and a reference only.",
    integrationComplexity: "high",
    knownLimitations: ["Lakh-derived training; no licence on the code; a lead-sheet-in model, not a hold-one-part-out model — our task would need re-framing."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "GETMUSIC",
    family: "Microsoft Muzic",
    name: "GETMusic (GETScore + GETDiff)",
    authorLab: "Microsoft Research Asia",
    sourceRepository: "https://github.com/microsoft/muzic",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2305.10841",
    releaseDate: "2023-05",
    revision: null,
    parameterCount: "unverified",
    architecture: "non-autoregressive discrete diffusion over a 2D track×time score",
    representation: "GETScore — notes as tokens in a 2D grid, tracks stacked vertically, time horizontal; six tracks (piano 0, guitar 25, bass 32, string 48, lead 80, drums)",
    contextLength: "unverified",
    capabilities: [
      "multitrack_arrangement", "track_completion", "accompaniment",
      "infilling", "controllable_generation",
    ],
    checkpointAvailable: false,
    checkpointNotes: "The README documents `--load_path /path-of-checkpoint` but publishes no checkpoint URL; none located this round either.",
    codeLicense: { stated: "MIT (Muzic repository LICENSE, Copyright (c) Microsoft Corporation)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: {
      stated: "\"GETMusic is trained on a dataset of crawled pop music\"; \"We do not open training data or the data cleansing scripts we used.\"",
      source: "getmusic/README.md in microsoft/muzic (read)",
      confidence: "verified_primary_source",
      datasets: ["undisclosed crawled pop-music MIDI"],
      // Crawled pop music is copyrighted works by definition; the publisher says so and withholds the set.
      underlyingWorksCleared: "no",
    },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE"],
    expectedRole:
      "The any-to-any source→target track capability is precisely our task generalised, and the 2D GETScore layout is a serious alternative to a linearised token stream for keeping tracks aligned. A representation to measure against; there are no weights to run.",
    integrationComplexity: "high",
    knownLimitations: [
      "Non-autoregressive diffusion — harder to condition incrementally than a decoder.",
      "No published checkpoint; crawled pop training set withheld by the publisher.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "MUSECOCO",
    family: "Microsoft Muzic",
    name: "MuseCoco (text → attributes → music)",
    authorLab: "Microsoft Research Asia",
    sourceRepository: "https://github.com/microsoft/muzic",
    huggingFace: "https://huggingface.co/XinXuNLPer/MuseCoco_attribute2music",
    paper: "https://arxiv.org/abs/2306.00110",
    releaseDate: "2023-06 (checkpoints 2023-06-30)",
    revision: null,
    parameterCount: "~200M (attribute-to-music, train-xl.sh) — per the README",
    architecture: "two stages: text-to-attribute understanding (BERT-class) and attribute-to-music generation (Linear-Transformer decoder over REMI-like tokens)",
    representation: "REMI-like multitrack tokens with attribute prefix (instrument set, tempo, metre, key, bar count, emotion, genre, …)",
    contextLength: "unverified",
    capabilities: ["full_symbolic_composition", "controllable_generation", "style_conditioned", "multitrack_arrangement"],
    checkpointAvailable: true,
    checkpointNotes: "attribute2music checkpoint on the Hub under a personal account; licence field not read this round.",
    codeLicense: { stated: "MIT (Muzic repository LICENSE)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: { stated: "not named in the README", source: "musecoco/README.md (read)", confidence: "secondary", datasets: ["undisclosed (the paper names a mix of public MIDI sets)"], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE", "BENCHMARK_ONLY"],
    expectedRole: "Attribute conditioning (instrument set, key, metre, genre) is the part of our V2 context nobody else tokenises so plainly; the two-stage text→attribute→music split is worth copying. Not a hold-one-part-out model.",
    integrationComplexity: "high",
    knownLimitations: ["Generates whole pieces from attributes; no infilling. Weights licence and corpus unread."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "FIGARO",
    family: "FIGARO",
    name: "FIGARO (description-to-sequence, expert + learned descriptions)",
    authorLab: "Dimitri von Rütte, Luca Biggio, Yannic Kilcher, Thomas Hofmann (ETH Zürich) — ICLR 2023",
    sourceRepository: "https://github.com/dvruette/figaro",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2201.10936",
    releaseDate: "2022-01; repo last pushed 2024-10-15",
    revision: null,
    parameterCount: "unverified (hidden 512; VQ-VAE latent 1024, 2048 codes)",
    architecture: "VQ-VAE learned bar descriptions + expert descriptions (instruments, chords, density) → Transformer decoder over REMI-style tokens",
    representation: "REMI+ multitrack tokens with per-bar description prefix",
    contextLength: "256 tokens per bar context (default)",
    capabilities: ["controllable_generation", "multitrack_arrangement", "style_conditioned"],
    checkpointAvailable: true,
    checkpointNotes: "checkpoints.zip (2.3 GB) from polybox.ethz.ch, three variants; no licence text attached to the weights.",
    codeLicense: { stated: "MIT (LICENSE, Copyright (c) 2021 Dimitri von Rütte)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: { stated: "Lakh MIDI (lmd_full.tar.gz) per the README's training instructions", source: "repository README (read)", confidence: "verified_primary_source", datasets: ["Lakh MIDI (LMD-full)"], underlyingWorksCleared: "no" },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE", "BENCHMARK_ONLY"],
    expectedRole: "Bar-level description conditioning (chords, instruments, density) is the closest published analogue to feeding a harmony plan and a style grammar as tokens — the design our vocabulary-extended fine-tune borrows from. Lakh-trained: a reference, not weights.",
    integrationComplexity: "medium",
    knownLimitations: ["Lakh-trained (RESEARCH_ONLY); 2022-era quality; whole-sequence generation rather than hold-one-part-out."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "SYMPHONYNET",
    family: "SymphonyNet",
    name: "SymphonyNet (permutation-invariant symphony generation)",
    authorLab: "CCOM NLP4Music AI Lab (Central Conservatory of Music) — ISMIR 2022",
    sourceRepository: "https://github.com/symphonynet/SymphonyNet",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2205.05448",
    releaseDate: "2022-05",
    revision: null,
    parameterCount: "unverified",
    architecture: "Linear Transformer with a Multi-track Multi-instrument Repeatable (MMR) representation and a 3-D positional embedding; continuation from a 5-measure prompt, optional chord constraint",
    representation: "MMR: bar → track → note tokens, permutation-invariant across tracks",
    contextLength: "unverified",
    capabilities: ["full_symbolic_composition", "orchestration", "multitrack_arrangement", "controllable_generation"],
    checkpointAvailable: true,
    checkpointNotes: "Pre-trained model on Google Drive (README link); no licence text on the weights.",
    codeLicense: { stated: "MIT (LICENSE, Copyright (c) 2021 CCOM NLP4Music AI Lab)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: { stated: "a collected symphony MIDI corpus (the paper); not named in the README", source: "README (read); paper abstract", confidence: "secondary", datasets: ["undisclosed symphony MIDI collection"], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE"],
    expectedRole: "The MMR representation's track permutation invariance is the other serious answer (besides REMI-z and GETScore) to keeping many tracks aligned; the model itself is a continuation generator, not an infiller.",
    integrationComplexity: "high",
    knownLimitations: ["Continuation only, no hold-one-part-out; corpus provenance unread; 2022-era."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  // -------------------------------------------------------------------------
  // Large symbolic foundations (ABC / text-tokenised)
  // -------------------------------------------------------------------------
  {
    id: "MUPT",
    family: "MuPT",
    name: "MuPT-v1-8192 (110M … 1.3B)",
    authorLab: "M-A-P (Multimodal Art Projection)",
    sourceRepository: null,
    huggingFace: "https://huggingface.co/m-a-p/MuPT-v1-8192-1.07B",
    paper: "https://arxiv.org/abs/2404.06393",
    releaseDate: "2024-04",
    revision: "HF 5d56c0b19f9a248beea00129f69e01f19ad0b2e3 (2024-04-10) — not installed",
    parameterCount: "four sizes, 110M to 1.3B per the model card (190M / 550M / 1.07B / 1.97B per the first-pass reading of the paper)",
    architecture: "LLaMA2 decoder (1.07B: 48 layers, hidden 1536, 24 heads)",
    representation: "ABC notation, newlines as <n>, synchronised multi-track ABC (SMT-ABC), merged tracks split in post-processing",
    contextLength: "8192 tokens",
    capabilities: [
      "full_symbolic_composition", "melody_generation", "accompaniment",
      "multitrack_arrangement", "style_conditioned",
    ],
    checkpointAvailable: true,
    checkpointNotes: "Multiple sizes on the M-A-P Hugging Face organisation, Megatron-LM and HF formats; the card names no code repository (the first pass's a43992899/MuPT URL now 404s).",
    codeLicense: { stated: "no dedicated code repository located; the card points at Megatron-LM for training", source: "Hub model card (read)", confidence: "unknown" },
    weightsLicense: {
      stated: "apache-2.0",
      source: "Hub API cardData.license and the raw README of m-a-p/MuPT-v1-8192-1.07B",
      confidence: "verified_primary_source",
    },
    trainingData: {
      stated: "\"trained on a large-scale dataset of symbolic music, including millions of monophonic and polyphonic pieces from different genres and styles\" (~7M pieces); sources not named",
      source: "model card (read) and the paper",
      confidence: "secondary",
      datasets: ["undisclosed 7M-piece symbolic corpus"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["FOUNDATION_CANDIDATE", "FINE_TUNE_CANDIDATE", "TEACHER_MODEL", "BENCHMARK_ONLY"],
    expectedRole:
      "The largest permissively-labelled symbolic foundation found. Its ABC representation is a poor fit for our per-instrument, per-bar arranging context, so it is a candidate to fine-tune or distil from rather than to adopt whole.",
    integrationComplexity: "high",
    knownLimitations: [
      "ABC notation loses the instrument-role, section and articulation structure PartGenerationRequestV2 carries.",
      "Training-corpus provenance is undisclosed, so Apache-2.0 on the weights does not settle commercial use.",
      "Bar-level and track-level conditioning would have to be encoded into ABC text prompts.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "NOTAGEN",
    family: "NotaGen",
    name: "NotaGen / NotaGen-X (110M / 244M / 516M)",
    authorLab: "Yashan Wang et al. (Central Conservatory of Music / collaborators) — IJCAI 2025",
    sourceRepository: "https://github.com/ElectricAlexis/NotaGen",
    huggingFace: "https://huggingface.co/ElectricAlexis/NotaGen",
    paper: "https://arxiv.org/abs/2502.18008",
    releaseDate: "2025-02; NotaGen-X 2025-03",
    revision: "HF 46b9f1466410ed702ca2f63d529524f406b7b30d (2025-02-26): pretrain (3 sizes), pretrain-finetune, pretrain-finetune-RL3, and weights_notagenx_… .pth — not installed",
    parameterCount: "110M (small), 244M (medium), 516M (large; NotaGen-X is the large architecture)",
    architecture: "patch-level decoder + character-level decoder (large: 20 + 6 layers, hidden 1280); NotaGen-X adds a post-training stage between pre-training and fine-tuning, drops key augmentation and runs more CLaMP-DPO iterations",
    representation: "ABC notation, patch-tokenised (patch 16, 1024 patches)",
    contextLength: "1024 patches",
    capabilities: ["full_symbolic_composition", "style_conditioned", "form_section_development"],
    checkpointAvailable: true,
    checkpointNotes: "Pre-trained, fine-tuned, RL (CLaMP-DPO ×3) and NotaGen-X checkpoints on the Hub; NotaGen-X inference is stated to need ~8 GB of GPU memory.",
    codeLicense: { stated: "MIT (LICENSE, Copyright (c) 2025 Yashan Wang)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: { stated: "mit", source: "Hub API cardData.license of ElectricAlexis/NotaGen", confidence: "verified_primary_source" },
    trainingData: {
      stated: "pre-training: 1.6M sheets 'spanning various genres and instrumentations', sources unnamed; fine-tuning: 8,948 classical sheets — DCML corpora 560, OpenScore String Quartets 342, OpenScore Lieder 1,334, ATEPP 55, KernScores 221, and 6,436 'internal sources'",
      source: "paper HTML §data (read); README",
      confidence: "secondary",
      datasets: ["1.6M-piece pre-training corpus (undisclosed composition)", "8,948-sheet classical fine-tuning set (72% 'internal sources')"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["BENCHMARK_ONLY", "TEACHER_MODEL", "ARCHITECTURE_REFERENCE"],
    expectedRole:
      "Strong at classical sheet-music composition, which is not our product. Its three-stage recipe — pretrain, fine-tune on a curated style set, then RL against a CLaMP critic — is the most directly transferable idea here: it is the same shape as our own pretrain → PDMX → reward-model plan.",
    integrationComplexity: "medium",
    knownLimitations: [
      "Classical sheet music, monophonic-to-small-ensemble; not a pop/multitrack arranger and not an infiller.",
      "ABC representation, same structural loss as MuPT.",
      "Pre-training corpus composition undisclosed; 72% of the fine-tuning set is 'internal sources'.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "CHATMUSICIAN",
    family: "ChatMusician",
    name: "ChatMusician (LLaMA-2 7B continued on ABC)",
    authorLab: "M-A-P / Skywork — Yuan et al.",
    sourceRepository: null,
    huggingFace: "https://huggingface.co/m-a-p/ChatMusician",
    paper: "https://arxiv.org/abs/2402.16153",
    releaseDate: "2024-02",
    revision: "HF cd8064911f26cd6701561eb733319adfa88383df (2024-04-08) — not installed",
    parameterCount: "7B (LLaMA-2 base)",
    architecture: "LLaMA-2 decoder, continual pre-training + SFT on ABC and text (MusicPile)",
    representation: "ABC notation as text",
    contextLength: "4096 (LLaMA-2)",
    capabilities: ["music_language_reasoning", "full_symbolic_composition", "controllable_generation", "harmony_reharmonization"],
    checkpointAvailable: true,
    checkpointNotes: "safetensors and bin shards on the Hub; cardData license 'mit'.",
    codeLicense: { stated: "code repository not located this round (the card links a demo, not a repo)", source: null, confidence: "unknown" },
    weightsLicense: { stated: "mit (cardData) — but the base is LLaMA-2, whose Llama 2 Community License binds derivatives regardless of the tag", source: "Hub API cardData + raw README (read)", confidence: "verified_primary_source" },
    trainingData: {
      stated: "MusicPile; 'a large portion of the training data is in the style of Irish music' (Irishman ABC); full composition not stated on the card",
      source: "model card (read)",
      confidence: "secondary",
      datasets: ["MusicPile (Irishman ABC, text and music corpora)"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: "Derivative of LLaMA-2: the Llama 2 Community License applies (acceptable-use policy, 700M-MAU clause) — commercial use is permitted under it, but the 'mit' tag on the card does not describe the actual terms.",
    roles: ["BENCHMARK_ONLY", "ARCHITECTURE_REFERENCE"],
    expectedRole: "The reference for music-language reasoning over symbolic music (chord-conditioned, form-conditioned ABC); irrelevant as an arranger but relevant to the producer-chat layer.",
    integrationComplexity: "high",
    knownLimitations: ["ABC only, folk-dominated corpus, 7B; the card itself warns of hallucination and strict-format-only prompts."],
    auditConfidence: "secondary",
    liveInferenceProven: false,
  },
  {
    id: "MELODYT5",
    family: "MelodyT5",
    name: "MelodyT5 (multi-task melody model)",
    authorLab: "Shangda Wu et al. — ISMIR 2024",
    sourceRepository: "https://github.com/sanderwood/melodyt5",
    huggingFace: "https://huggingface.co/sander-wood/melodyt5",
    paper: "https://arxiv.org/abs/2407.02277",
    releaseDate: "2024-07",
    revision: "HF 5c1594ff1a4c183b5c21635b2df29ebca54392ab — not installed",
    parameterCount: "unverified",
    architecture: "encoder–decoder (patch-level) score-to-score over ABC",
    representation: "ABC notation (melody-centric)",
    contextLength: "unverified",
    capabilities: ["melody_generation", "harmony_reharmonization", "form_section_development"],
    checkpointAvailable: true,
    checkpointNotes: "weights.pth on the Hub; seven tasks: cataloguing, generation, harmonization, melodization, segmentation, transcription, variation.",
    codeLicense: { stated: "MIT (LICENSE, Copyright (c) 2024 Sander Wood)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: { stated: "mit", source: "Hub API cardData.license", confidence: "verified_primary_source" },
    trainingData: { stated: "MelodyHub (261,900 melodies in ABC) — source collections and their licences not stated on the card", source: "model card (read)", confidence: "secondary", datasets: ["MelodyHub"], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["SPECIALIST", "ARCHITECTURE_REFERENCE"],
    expectedRole: "A melody harmonizer / variation model in ABC; the harmonization task is a benchmark for the platform's own harmony work, not an arranger.",
    integrationComplexity: "medium",
    knownLimitations: ["Monophonic melody focus; ABC; corpus provenance unread."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "MIDI_LLM",
    family: "MIDI-LLM",
    name: "MIDI-LLM (Llama-3.2-1B, text-to-MIDI)",
    authorLab: "Shih-Lun Wu et al. — ISMIR 2026",
    sourceRepository: "https://github.com/slSeanWU/MIDI-LLM",
    huggingFace: "https://huggingface.co/slseanwu/MIDI-LLM_Llama-3.2-1B",
    paper: "https://arxiv.org/abs/2511.03942",
    releaseDate: "2025-11; weights 2026-07-27",
    revision: "HF 8b82ab9ec144348900e9ea4623b123e0b12f60b3 — not installed",
    parameterCount: "1.4B (Llama-3.2-1B + 55,030 MIDI tokens in the vocabulary)",
    architecture: "Llama-3.2 decoder with an extended vocabulary (183,286 = 128,256 text + 55,030 MIDI tokens — the AMT arrival-time vocabulary), text prompt → MIDI tokens",
    representation: "AMT-style arrival-time events (onset, duration, instrument-pitch) after a text prompt",
    contextLength: "Llama-3.2 (8k+); MIDI clip length bounded by the 100 s clock",
    capabilities: ["full_symbolic_composition", "controllable_generation", "multitrack_arrangement", "infilling"],
    checkpointAvailable: true,
    checkpointNotes: "One checkpoint on the Hub; the SFT used 'AMT infilling augmentation' — infilling exists in training, not as a documented API.",
    codeLicense: { stated: "LLAMA 3.2 COMMUNITY LICENSE AGREEMENT (LICENSE.md)", source: "GitHub licence API (spdx NOASSERTION; content read)", confidence: "verified_primary_source" },
    weightsLicense: { stated: "llama3.2 — \"subject to the Llama 3.2 Community License\"", source: "Hub API cardData.license + raw README (read)", confidence: "verified_primary_source" },
    trainingData: {
      stated: "MidiCaps (Lakh MIDI paired with captions, ~5B tokens with AMT infilling augmentation), MusicPile (~1.7B tokens), GigaMIDI (~1.4B tokens) — GigaMIDI is research/non-commercial under Fair Dealing",
      source: "model card (read); GigaMIDI terms from the first pass",
      confidence: "secondary",
      datasets: ["MidiCaps (Lakh)", "MusicPile", "GigaMIDI"],
      underlyingWorksCleared: "no",
    },
    statedRestriction: "GigaMIDI component: research and non-commercial use only; Llama 3.2 Community License on code and weights.",
    roles: ["BENCHMARK_ONLY", "ARCHITECTURE_REFERENCE"],
    expectedRole: "Text-to-MIDI, not arrangement; noted because it reuses the AMT vocabulary and shows a 1B text LLM can be taught it — the path to a producer-brief-conditioned generator later.",
    integrationComplexity: "medium",
    knownLimitations: ["Text-to-MIDI from scratch, not hold-one-part-out; GigaMIDI + Lakh training; Llama licence."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "ARIA",
    family: "Aria",
    name: "Aria (aria-medium-base / -gen / -embedding)",
    authorLab: "Louis Bradshaw, Simon Colton (EleutherAI / QMUL)",
    sourceRepository: "https://github.com/EleutherAI/aria",
    huggingFace: "https://huggingface.co/loubb/aria-medium-base",
    paper: "https://arxiv.org/abs/2506.23869",
    releaseDate: "2025-06; weights 2026-04-13",
    revision: "HF 5a1ef36c5007ee10fbe57d61d96725a7244bd2b2 — not installed",
    parameterCount: "~1B (LLaMA-3.2-1B-shaped)",
    architecture: "LLaMA-3.2 (1B) decoder over an expressive piano MIDI tokenization; continuation-first; contrastive embedding variant",
    representation: "absolute-time piano MIDI tokens with velocity and pedal",
    contextLength: "unverified (long-context piano)",
    capabilities: ["expressive_performance", "instrument_specific", "embeddings_retrieval", "full_symbolic_composition"],
    checkpointAvailable: true,
    checkpointNotes: "Three Hub checkpoints (base, gen, embedding); example prompts ship in the repo.",
    codeLicense: { stated: "Apache-2.0 (LICENSE)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: { stated: "apache-2.0 — \"Our models and MIDI tooling are released under the Apache-2.0 license.\"", source: "Hub API cardData + README (read)", confidence: "verified_primary_source" },
    trainingData: {
      stated: "Aria-MIDI: \"~60k hours of MIDI transcriptions of expressive solo-piano recordings\", \"created by transcribing publicly available solo-piano audio recordings\"; dataset card: license cc-by-nc-sa-4.0",
      source: "README (read) + https://huggingface.co/datasets/loubb/aria-midi card front matter (read)",
      confidence: "verified_primary_source",
      datasets: ["Aria-MIDI (CC-BY-NC-SA-4.0; transcribed from audio recordings)"],
      underlyingWorksCleared: "no",
    },
    statedRestriction: "Training data CC-BY-NC-SA-4.0 (non-commercial); the README warns the model may reproduce well-known classical pieces from incomplete deduplication.",
    roles: ["BENCHMARK_ONLY", "ARCHITECTURE_REFERENCE"],
    expectedRole: "The strongest open expressive-piano model — relevant to the expressive-performance gap the first pass named, not to arrangement. Apache weights over NC-licensed transcriptions of recordings: the textbook case of a permissive label that does not settle use.",
    integrationComplexity: "medium",
    knownLimitations: ["Solo piano; NC training data; continuation rather than infilling."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "PIANIST_TRANSFORMER",
    family: "Pianist Transformer",
    name: "Pianist Transformer (score → expressive performance)",
    authorLab: "Hong-Jie You, Jie-Jing Shao, Xiao-Wen Yang, Lin-Han Jia, Lan-Zhe Guo, Yu-Feng Li (Nanjing University)",
    sourceRepository: "https://github.com/yhj137/PianistTransformer",
    huggingFace: "https://huggingface.co/collections/yhj137/pianist-transformer",
    paper: "https://arxiv.org/abs/2512.02652",
    releaseDate: "2025-12",
    revision: null,
    parameterCount: "135M (self-supervised pre-trained model)",
    architecture: "asymmetric Transformer with note-level compression; self-supervised pre-training on 10B tokens of unlabeled MIDI, then performance-rendering fine-tuning",
    representation: "note-level score/performance tokens (piano)",
    contextLength: "long-context (note-level compression); unverified",
    capabilities: ["expressive_performance", "instrument_specific"],
    checkpointAvailable: true,
    checkpointNotes: "Checkpoints in a Hub collection and on ModelScope (project page); not read this round.",
    codeLicense: { stated: "Apache-2.0", source: "GitHub licence API (yhj137/PianistTransformer)", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: { stated: "10B tokens of unlabeled MIDI for pre-training; datasets not named on the project page", source: "arXiv abstract + project page (read)", confidence: "secondary", datasets: ["undisclosed 10B-token piano MIDI corpus"], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["SPECIALIST", "ARCHITECTURE_REFERENCE"],
    expectedRole: "The first performance-rendering model whose outputs a listening study found indistinguishable from a human pianist — the candidate for the expressive-performance gap (piano only), once its weights licence and corpus are read.",
    integrationComplexity: "medium",
    knownLimitations: ["Piano only; performance rendering, not composition or arrangement; weights terms and corpus unread."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "METASCORE_TRANSFORMER",
    family: "MetaScore",
    name: "MetaScore Transformer (text → multitrack score)",
    authorLab: "Weihan Xu, Julian McAuley, Taylor Berg-Kirkpatrick, Shlomo Dubnov, Hao-Wen Dong (UCSD / Michigan) — ISMIR 2025",
    sourceRepository: "https://github.com/wx83/MetaScore_Official",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2410.02084",
    releaseDate: "2024-10; ISMIR 2025; repo pushed 2025-12-15",
    revision: null,
    parameterCount: "unverified",
    architecture: "text-conditioned symbolic music transformer (pretrained LM text encoder → multitrack score decoder) with controls for difficulty, genre, instrument, composer",
    representation: "multitrack score tokens (MusicXML-derived)",
    contextLength: "unverified",
    capabilities: ["full_symbolic_composition", "controllable_generation", "style_conditioned", "multitrack_arrangement"],
    checkpointAvailable: true,
    checkpointNotes: "Checkpoint on Google Drive (README link). Dataset: MetaScore-Raw 963K MuseScore forum scores; public release limited to 228K public-domain + 46K Creative-Commons scores 'due to copyright concerns', the rest on request for research.",
    codeLicense: { stated: "no licence file (GitHub reports none)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: {
      stated: "MetaScore (MuseScore forum scores with user tags and LLM captions); which subset the released model was trained on is not stated in the README",
      source: "README (read) + arXiv abstract",
      confidence: "secondary",
      datasets: ["MetaScore-Plus / -Genre (MuseScore; PD + CC subsets publicly released, the rest restricted)"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE", "BENCHMARK_ONLY"],
    expectedRole: "The same data lineage as PDMX (MuseScore) with an explicit PD/CC split — if the released model turns out to be trained on the cleared subset it is the nearest thing to a cleared text-to-multitrack foundation; that fact is unread.",
    integrationComplexity: "high",
    knownLimitations: ["No code licence; training subset unstated; text-to-score rather than hold-one-part-out."],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
  {
    id: "PHRASELDM",
    family: "PhraseVAE / PhraseLDM",
    name: "PhraseLDM (latent diffusion for full-song multitrack symbolic music)",
    authorLab: "Longshen Ou et al. (NUS)",
    sourceRepository: "https://github.com/Sonata165/PhraseLDM_code",
    huggingFace: null,
    paper: "https://arxiv.org/abs/2512.11348",
    releaseDate: "2025-12; repo pushed 2026-02-03",
    revision: null,
    parameterCount: "unverified",
    architecture: "phrase-level VAE + latent diffusion over phrase latents for whole-song multitrack generation",
    representation: "REMI-z phrases → latents",
    contextLength: "whole song (phrase latents)",
    capabilities: ["full_symbolic_composition", "multitrack_arrangement", "form_section_development"],
    checkpointAvailable: false,
    checkpointNotes: "README not readable at the raw URL this round (404 on main); licence read from the API; no checkpoint verified.",
    codeLicense: { stated: "Apache-2.0", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: unknownLicence,
    trainingData: { ...unknownLicence, datasets: [], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE"],
    expectedRole: "Whole-song structure via phrase latents — relevant to the long-form workstream, not to per-part infilling.",
    integrationComplexity: "high",
    knownLimitations: ["Unconditional/whole-song generation; no weights verified; corpus unread."],
    auditConfidence: "secondary",
    liveInferenceProven: false,
  },
  {
    id: "EQUIVARIANT_MUSIC_TRANSFORMER",
    family: "Equivariant Music Transformer",
    name: "Equivariant Music Transformer (EMT)",
    authorLab: "Zixun Guo, Simon Dixon (QMUL) — ISMIR 2026",
    sourceRepository: null,
    huggingFace: null,
    paper: "https://arxiv.org/abs/2608.03920",
    releaseDate: "2026-08",
    revision: null,
    parameterCount: "unverified",
    architecture: "next-token music transformer trained with an auxiliary equivariance (time-shift / transposition) regularisation by self-distillation",
    representation: "unverified (Moonbeam lineage)",
    contextLength: "unverified",
    capabilities: ["full_symbolic_composition", "embeddings_retrieval"],
    checkpointAvailable: false,
    checkpointNotes: "The abstract says 'code, weights and demos are available online'; the location was not found in this round's searches.",
    codeLicense: unknownLicence,
    weightsLicense: unknownLicence,
    trainingData: { ...unknownLicence, datasets: [], underlyingWorksCleared: "unknown" },
    statedRestriction: null,
    roles: ["ARCHITECTURE_REFERENCE"],
    expectedRole: "The newest representation-learning idea (equivariance to transposition and time shift) — a training trick for ARRANGER_FM, not a model to run.",
    integrationComplexity: "very_high",
    knownLimitations: ["Nothing located to run; unread licences."],
    auditConfidence: "secondary",
    liveInferenceProven: false,
  },
  // -------------------------------------------------------------------------
  // Retrieval / reward
  // -------------------------------------------------------------------------
  {
    id: "CLAMP3",
    family: "CLaMP",
    name: "CLaMP 3",
    authorLab: "Shangda Wu et al. (ACL 2025)",
    sourceRepository: "https://github.com/sanderwood/clamp3",
    huggingFace: "https://huggingface.co/sander-wood/clamp3",
    paper: "https://arxiv.org/abs/2502.10362",
    releaseDate: "2025-02",
    revision: "HF 355625cc1c6f73726bbcd0eb9276ac7152d56426 (2025-02-24): saas and c2 .pth — not installed",
    parameterCount: "unverified (768-d embeddings; 12-layer audio/symbolic encoders; XLM-RoBERTa-base text)",
    architecture: "contrastive multimodal encoders (text / sheet music / MIDI / audio)",
    representation: "bar or MIDI-message units for symbolic; 5-second clips for audio",
    contextLength: "128 text / 128 audio / 512 symbolic patches",
    capabilities: ["embeddings_retrieval", "music_language_reasoning"],
    checkpointAvailable: true,
    checkpointNotes: "SAAS (audio-optimised) and C2 (symbolic; config.py line 66 'saas'→'c2') variants.",
    codeLicense: { stated: "MIT (LICENSE, Copyright (c) 2025 Sander Wood)", source: "GitHub licence API", confidence: "verified_primary_source" },
    weightsLicense: { stated: "mit", source: "Hub API cardData.license + raw README of sander-wood/clamp3", confidence: "verified_primary_source" },
    trainingData: {
      stated: "M4-RAG (2.31M music-text pairs, 27 languages); WikiMT-X (1,000 triplets) for benchmarking; sources and collection method not stated on the card",
      source: "CLaMP 3 model card (read) and ACL 2025 paper",
      confidence: "secondary",
      datasets: ["M4-RAG", "WikiMT-X"],
      underlyingWorksCleared: "unknown",
    },
    statedRestriction: null,
    roles: ["SPECIALIST", "ARCHITECTURE_REFERENCE"],
    expectedRole:
      "The natural backbone for MUSIC_REWARD_MODEL_V1 and for style similarity. NotaGen's CLaMP-DPO shows it working as an RL critic for symbolic music, which is exactly the role our plan reserves for a reward model. Already present in this repo's catalogue as CLAMP3.",
    integrationComplexity: "medium",
    knownLimitations: [
      "Training provenance unread — and a reward model shapes a shipped model, so its own rights matter.",
    ],
    auditConfidence: "verified_primary_source",
    liveInferenceProven: false,
  },
];

/** Entries already present in this repo's own provider catalogue, for the audit. */
export const ALREADY_IN_CATALOGUE = [
  "ANYACCOMP", "HAFM", "SYMPHONYGEN", "METEOR", "MIDI_SAG", "MUSE_CONTROL_LITE",
  "MAGENTA_RT2", "LADA_BAND", "MIDI_RWKV", "DIFFRHYTHM_2", "CLAMP3",
  "MUSICGEN", "ACE_STEP_BASE", "STABLE_AUDIO_3_SMALL_MUSIC", "STABLE_AUDIO_3_MEDIUM",
  "BASIC_PITCH", "MT3", "MR_MT3", "YOUR_MT3", "ALL_IN_ONE", "BS_ROFORMER",
  "DEMUCS", "SHEETSAGE", "CHROMA", "BASS",
] as const;

/**
 * Audited this round and deliberately not given a row: they are audio models,
 * outside the symbolic registry's question. STAGE (ISMIR 2025, a MusicGen
 * fine-tune for stemmed accompaniment), LaDA-Band and DiffRhythm 2 (already
 * in the catalogue as RESEARCH_ONLY), HeartMuLa (2026, audio codec LM).
 */
export const AUDITED_OUT_OF_SCOPE = ["STAGE", "LADA_BAND", "DIFFRHYTHM_2", "HEART_MULA"] as const;
