/**
 * Tier H entries of the real benchmark corpus (Brain B-08). GENERATED by
 * `scripts/select-real-corpus.mjs` on 2026-09-10 from PDMX.csv
 * (222856 admitted rows, 25414 multitrack) and the MIDI on disk; the
 * selection report with every measurement and every gap is
 * `docs/evidence/real-corpus-tier-h-selection.json`. Re-run the script to
 * regenerate; do not edit by hand.
 *
 * Every attribute below was measured from the work's MIDI or read from its
 * PDMX row (see the report's `method`). Rights are per work and two-layered:
 * the score through the row's own licence statement, the **composition**
 * through `compositionRights.ts` (a verified composer dead by the cutoff, or
 * a documented traditional tune) - a work whose composition is unproven is
 * contested and is not here. Coverage gaps are reported by
 * `corpusCoverage`, never filled synthetically.
 */
import type { CorpusEntry } from "./benchmarkCorpusPlan";

export const REAL_CORPUS_TIER_H_GENERATED_AT = "2026-09-10T03:59:30.893Z";

/** Contested candidates (composition unproven) at generation time - excluded from this list and from every Tier H aggregate; see the selection report. */
export const REAL_CORPUS_TIER_H_CONTESTED = 6732;

export const REAL_CORPUS_TIER_H: CorpusEntry[] = [
  {
    "id": "pdmx-QmYoSb5q8XUyPXGaizifu1QRsVLToY1aCQV5gDrMUa99vw",
    "title": "Piano Concerto No.21 in C major K.467",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Piano Concerto No.21 in C major K.467 (PDMX QmYoSb5q8XUyPXGaizifu1QRsVLToY1aCQV5gDrMUa99vw, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Wolfgang Amadeus Mozart",
      "composerDied": 1791
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "swung",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmYoSb5q8XUyPXGaizifu1QRsVLToY1aCQV5gDrMUa99vw",
      "relativePath": "mid/mid/16/35/QmYoSb5q8XUyPXGaizifu1QRsVLToY1aCQV5gDrMUa99vw.mid",
      "sha256": "3c780bfd6438095d6b7f968896f0016e4d0a3c5395d6ab09cddc711520f66b3e",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 104,
        "tracks": 16,
        "families": [
          "brass",
          "keys",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 63,
        "tempoChanges": 0,
        "notesPerBar": 52.44,
        "swingRatio": 0.8939,
        "effectivePitchClasses": 9.28
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmRPTQvtBowZ5rcT7BBkmHYspycANuQY2aZFcTp3S9Muym",
    "title": "Concerto In C MVT2",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Concerto In C MVT2 (PDMX QmRPTQvtBowZ5rcT7BBkmHYspycANuQY2aZFcTp3S9Muym, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Antonio Vivaldi",
      "composerDied": 1741
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/4",
      "feel": "swung",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmRPTQvtBowZ5rcT7BBkmHYspycANuQY2aZFcTp3S9Muym",
      "relativePath": "mid/mid/9/37/QmRPTQvtBowZ5rcT7BBkmHYspycANuQY2aZFcTp3S9Muym.mid",
      "sha256": "404dbf2a5b59ff154e5df83fc32e517822175dd0d99380d291be84d2488fcd03",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 35,
        "tracks": 6,
        "families": [
          "guitar",
          "keys",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 50,
        "tempoChanges": 0,
        "notesPerBar": 35.09,
        "swingRatio": 0.7458,
        "effectivePitchClasses": 8.45
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmTa8epLaUjVkEcV7ZzYbazW6fxEgvwLMC5AuG5uqBKyJ6",
    "title": "Rigoletto",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Rigoletto (PDMX QmTa8epLaUjVkEcV7ZzYbazW6fxEgvwLMC5AuG5uqBKyJ6, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Giuseppe Verdi",
      "composerDied": 1901
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/8",
      "feel": "swung",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmTa8epLaUjVkEcV7ZzYbazW6fxEgvwLMC5AuG5uqBKyJ6",
      "relativePath": "mid/mid/11/9/QmTa8epLaUjVkEcV7ZzYbazW6fxEgvwLMC5AuG5uqBKyJ6.mid",
      "sha256": "446ae6d92e692c9bed25ed20e9a5a331363b11cccad49c80892be3722c5864b9",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 91,
        "tracks": 14,
        "families": [
          "brass",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "3/8",
        "tempoBpm": 69,
        "tempoChanges": 45,
        "notesPerBar": 23.15,
        "swingRatio": 0.9123,
        "effectivePitchClasses": 6.35
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmY8KJiDxZhpTwzNqvX15YfzoSD6X9hkAb5eMw8HAvBDsj",
    "title": "Kleine Orgelmesse or Missa brevis Sancti Joannis de Deo Mass No. 7 in Bb Major",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Kleine Orgelmesse or Missa brevis Sancti Joannis de Deo Mass No. 7 in Bb Major (PDMX QmY8KJiDxZhpTwzNqvX15YfzoSD6X9hkAb5eMw8HAvBDsj, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Joseph Haydn",
      "composerDied": 1809
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmY8KJiDxZhpTwzNqvX15YfzoSD6X9hkAb5eMw8HAvBDsj",
      "relativePath": "mid/mid/16/7/QmY8KJiDxZhpTwzNqvX15YfzoSD6X9hkAb5eMw8HAvBDsj.mid",
      "sha256": "e664c42645689b5b6362308e6e9ec28e2fde796835ec174204195e494fb699fc",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 30,
        "tracks": 7,
        "families": [
          "ensemble",
          "organ",
          "strings"
        ],
        "meter": "6/8",
        "tempoBpm": 75,
        "tempoChanges": 0,
        "notesPerBar": 26.77,
        "swingRatio": 0,
        "effectivePitchClasses": 8.49
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmR8F9HZyxGE7yC37FUaDURa4MaBh6bkoHJz3K1AhFzQRr",
    "title": "Greensleeves",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Greensleeves (PDMX QmR8F9HZyxGE7yC37FUaDURa4MaBh6bkoHJz3K1AhFzQRr, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "traditional": true,
      "source": "Greensleeves: English broadside ballad tune, registered 1580 (Stationers' Company)"
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmR8F9HZyxGE7yC37FUaDURa4MaBh6bkoHJz3K1AhFzQRr",
      "relativePath": "mid/mid/9/7/QmR8F9HZyxGE7yC37FUaDURa4MaBh6bkoHJz3K1AhFzQRr.mid",
      "sha256": "d2a7b1e83cd40a0b7e93f72fd33390f1933a20dd6d671f56641b88c2e427730b",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 31,
        "tracks": 5,
        "families": [
          "ensemble",
          "guitar",
          "strings"
        ],
        "meter": "6/8",
        "tempoBpm": 70,
        "tempoChanges": 0,
        "notesPerBar": 14.03,
        "swingRatio": 0,
        "effectivePitchClasses": 7.49
      },
      "genre": {
        "primary": "folk",
        "families": [
          "folk"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmZWa9Ewjm3w5cjP9a9gutRT7N58S4EMnBAonBd4iN5oMi",
    "title": "Sicilienne Op.78",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Sicilienne Op.78 (PDMX QmZWa9Ewjm3w5cjP9a9gutRT7N58S4EMnBAonBd4iN5oMi, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Gabriel Fauré",
      "composerDied": 1924
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmZWa9Ewjm3w5cjP9a9gutRT7N58S4EMnBAonBd4iN5oMi",
      "relativePath": "mid/mid/17/51/QmZWa9Ewjm3w5cjP9a9gutRT7N58S4EMnBAonBd4iN5oMi.mid",
      "sha256": "d4798e27c9611cbc4dedc64491bda13b226b827f7c59e2182a7674d262d76963",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 89,
        "tracks": 14,
        "families": [
          "bass",
          "brass",
          "drums",
          "guitar",
          "pipe",
          "reed"
        ],
        "meter": "6/8",
        "tempoBpm": 75,
        "tempoChanges": 0,
        "notesPerBar": 51.8,
        "swingRatio": 0.9092,
        "effectivePitchClasses": 8.84
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr",
    "title": "Silent night - Instrumental flute - flugehorn - violin",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Silent night - Instrumental flute - flugehorn - violin (PDMX QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Franz Xaver Gruber",
      "composerDied": 1863
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr",
      "relativePath": "mid/mid/0/13/QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr.mid",
      "sha256": "7c0eba20b4129812668e2eef7982da0b0b04adb6910f376836214cbf0be74dbc",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 93,
        "tracks": 7,
        "families": [
          "bass",
          "brass",
          "drums",
          "keys",
          "pipe",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 90,
        "tempoChanges": 0,
        "notesPerBar": 14.7,
        "swingRatio": 0.0082,
        "effectivePitchClasses": 8.19
      },
      "genre": {
        "primary": "film_game",
        "families": [
          "film_game",
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmRjibSinfVz16xTgqnq4EPza8mrMFTLbqzwJL9wbUJ2io",
    "title": "Glorie daÈi lui Dumnezeu!",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Glorie daÈi lui Dumnezeu! (PDMX QmRjibSinfVz16xTgqnq4EPza8mrMFTLbqzwJL9wbUJ2io, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Dieterich Buxtehude",
      "composerDied": 1707
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmRjibSinfVz16xTgqnq4EPza8mrMFTLbqzwJL9wbUJ2io",
      "relativePath": "mid/mid/9/26/QmRjibSinfVz16xTgqnq4EPza8mrMFTLbqzwJL9wbUJ2io.mid",
      "sha256": "32bbc22dad70211e1abc225bcf3fdb83fca71899222071edc43a597f1213eadb",
      "admittedBy": "tournament-classical",
      "measured": {
        "bars": 64,
        "tracks": 5,
        "families": [
          "ensemble",
          "keys",
          "pipe"
        ],
        "meter": "3/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 19.38,
        "swingRatio": 0.0069,
        "effectivePitchClasses": 6.43
      },
      "genre": {
        "primary": "unlabelled",
        "families": [
          "unlabelled"
        ],
        "source": "none"
      }
    }
  },
  {
    "id": "pdmx-QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1",
    "title": "Symphony No.9 Op.125",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Symphony No.9 Op.125 (PDMX QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Ludwig van Beethoven",
      "composerDied": 1827
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "2/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "sparse",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1",
      "relativePath": "mid/mid/17/36/QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1.mid",
      "sha256": "f384ebdc3cd174f244ed7b886e348a4e80ba673d79f61c8e19ca940204402a86",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 32,
        "tracks": 3,
        "families": [
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "2/4",
        "tempoBpm": 80,
        "tempoChanges": 0,
        "notesPerBar": 5.63,
        "swingRatio": null,
        "effectivePitchClasses": 5.9
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmP8P1EjQNde6Z8i3ZP8JK9ny9cVPQCC2ThtqpaUcqSato",
    "title": "Heilig aus der Deutschen Messe",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Heilig aus der Deutschen Messe (PDMX QmP8P1EjQNde6Z8i3ZP8JK9ny9cVPQCC2ThtqpaUcqSato, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Franz Schubert",
      "composerDied": 1828
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "sparse",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmP8P1EjQNde6Z8i3ZP8JK9ny9cVPQCC2ThtqpaUcqSato",
      "relativePath": "mid/mid/7/7/QmP8P1EjQNde6Z8i3ZP8JK9ny9cVPQCC2ThtqpaUcqSato.mid",
      "sha256": "5d3501f98aeba01e11b6ec8154773c603f6e3316726fd8a06e7bd339f988afca",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 64,
        "tracks": 4,
        "families": [
          "pipe",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 72,
        "tempoChanges": 1,
        "notesPerBar": 5.72,
        "swingRatio": null,
        "effectivePitchClasses": 6.94
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmU1nWTKzCtLUFXgt7kZbsm3pJcN7U1E8kKDwKA6nxhMee",
    "title": "O leggiadr' occhi",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "O leggiadr' occhi (PDMX QmU1nWTKzCtLUFXgt7kZbsm3pJcN7U1E8kKDwKA6nxhMee, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Sigismondo d'India",
      "composerDied": 1629
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "sparse",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmU1nWTKzCtLUFXgt7kZbsm3pJcN7U1E8kKDwKA6nxhMee",
      "relativePath": "mid/mid/12/0/QmU1nWTKzCtLUFXgt7kZbsm3pJcN7U1E8kKDwKA6nxhMee.mid",
      "sha256": "a1ce3ad1e21a78ca3791a46f1f2e90de6896cc72ad81e3460eae8ef1ac16921f",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 81,
        "tracks": 3,
        "families": [
          "ensemble",
          "keys"
        ],
        "meter": "3/4",
        "tempoBpm": 70,
        "tempoChanges": 1,
        "notesPerBar": 4.88,
        "swingRatio": null,
        "effectivePitchClasses": 7.58
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmY5RQf5HHdJfVA95Dn1bE257cHbefkcqEAFGx8ivkCV59",
    "title": "Se La Face Ay Pale - Guillaume Dufay",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Se La Face Ay Pale - Guillaume Dufay (PDMX QmY5RQf5HHdJfVA95Dn1bE257cHbefkcqEAFGx8ivkCV59, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Guillaume Dufay",
      "composerDied": 1474
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "3/2",
      "feel": "straight",
      "harmony": "simple",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmY5RQf5HHdJfVA95Dn1bE257cHbefkcqEAFGx8ivkCV59",
      "relativePath": "mid/mid/16/4/QmY5RQf5HHdJfVA95Dn1bE257cHbefkcqEAFGx8ivkCV59.mid",
      "sha256": "06980cd73ef9d93e1f3cca46f908f6a67ec7ab2cb12036c61d65db32b35313e4",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 31,
        "tracks": 5,
        "families": [
          "guitar",
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "3/2",
        "tempoBpm": 170,
        "tempoChanges": 1,
        "notesPerBar": 13,
        "swingRatio": 0.0222,
        "effectivePitchClasses": 6.6
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmSTacsYPkj7oA7RtKFuF7GP1hzqxWJfzWD81Uo3pJM2Yg",
    "title": "Chandos Anthem No. 4: No. 6 - O worship the Lord in the beauty of holiness",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Chandos Anthem No. 4: No. 6 - O worship the Lord in the beauty of holiness (PDMX QmSTacsYPkj7oA7RtKFuF7GP1hzqxWJfzWD81Uo3pJM2Yg, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "George Frideric Handel",
      "composerDied": 1759
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "3/2",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmSTacsYPkj7oA7RtKFuF7GP1hzqxWJfzWD81Uo3pJM2Yg",
      "relativePath": "mid/mid/10/45/QmSTacsYPkj7oA7RtKFuF7GP1hzqxWJfzWD81Uo3pJM2Yg.mid",
      "sha256": "6d3890af77bfd051737806a01524c5a31bad88092f17585a88217fa5d6152469",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 84,
        "tracks": 4,
        "families": [
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "3/2",
        "tempoBpm": 150,
        "tempoChanges": 0,
        "notesPerBar": 11.68,
        "swingRatio": 0,
        "effectivePitchClasses": 7.67
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmQiv698z1BpNkRnoFvkZvJQPUPn1aZK8vqsKXVQLoVLqS",
    "title": "Hungarian Rhapsody No.15 S.244/15",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Hungarian Rhapsody No.15 S.244/15 (PDMX QmQiv698z1BpNkRnoFvkZvJQPUPn1aZK8vqsKXVQLoVLqS, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Franz Liszt",
      "composerDied": 1886
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmQiv698z1BpNkRnoFvkZvJQPUPn1aZK8vqsKXVQLoVLqS",
      "relativePath": "mid/mid/8/25/QmQiv698z1BpNkRnoFvkZvJQPUPn1aZK8vqsKXVQLoVLqS.mid",
      "sha256": "34e7a1d02a571a73f967b636b1903e135bca8e9b411144f51c8c0807213b7698",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 98,
        "tracks": 14,
        "families": [
          "brass",
          "chromatic_perc",
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 144,
        "tempoChanges": 1,
        "notesPerBar": 38.99,
        "swingRatio": 0.0231,
        "effectivePitchClasses": 9.46
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW",
    "title": "Benedictus uit Messe Solonelle",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Benedictus uit Messe Solonelle (PDMX QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Louis Vierne",
      "composerDied": 1937
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW",
      "relativePath": "mid/mid/1/9/QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW.mid",
      "sha256": "3df52f6e8e21fe4ee2282e975089095b61f5fa22d980161d3f96238bc635ce83",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 57,
        "tracks": 10,
        "families": [
          "ensemble",
          "keys",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 84,
        "tempoChanges": 1,
        "notesPerBar": 16.89,
        "swingRatio": 0,
        "effectivePitchClasses": 9.75
      },
      "genre": {
        "primary": "religious_worship",
        "families": [
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS",
    "title": "Arthur S. Sullivan: Christ is Risen!",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Arthur S. Sullivan: Christ is Risen! (PDMX QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Arthur Sullivan",
      "composerDied": 1900
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS",
      "relativePath": "mid/mid/0/52/QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS.mid",
      "sha256": "8e9eaaba8a4b456d05799c724b46380e76dbf141b8fdd957ce36fe81cd6d0f94",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 76,
        "tracks": 6,
        "families": [
          "brass",
          "ensemble",
          "keys",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 115,
        "tempoChanges": 6,
        "notesPerBar": 34.37,
        "swingRatio": 0,
        "effectivePitchClasses": 7.66
      },
      "genre": {
        "primary": "religious_worship",
        "families": [
          "religious_worship"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmUeMxaCbfQm7LTRPruopP8ixYRDojtRHJ8q5SFRQ1qM6G",
    "title": "Giunto che m'hebb' amor",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Giunto che m'hebb' amor (PDMX QmUeMxaCbfQm7LTRPruopP8ixYRDojtRHJ8q5SFRQ1qM6G, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Benedetto Pallavicino",
      "composerDied": 1601
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmUeMxaCbfQm7LTRPruopP8ixYRDojtRHJ8q5SFRQ1qM6G",
      "relativePath": "mid/mid/12/17/QmUeMxaCbfQm7LTRPruopP8ixYRDojtRHJ8q5SFRQ1qM6G.mid",
      "sha256": "aed917cc1c9fac470ba5afc9fc5ad3a33350ca4f0accff7ea6e9cdb1c8c75d8e",
      "admittedBy": "tournament-classical",
      "measured": {
        "bars": 80,
        "tracks": 5,
        "families": [
          "brass",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 78,
        "tempoChanges": 0,
        "notesPerBar": 10.86,
        "swingRatio": 0,
        "effectivePitchClasses": 8.28
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmRi9oH5ENmQU2NgfFLPQRVhQ7nYYjyzcb5saZ1XJPtmik",
    "title": "Canon and Gigue in D major P.37",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Canon and Gigue in D major P.37 (PDMX QmRi9oH5ENmQU2NgfFLPQRVhQ7nYYjyzcb5saZ1XJPtmik, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Pachelbel",
      "composerDied": 1706
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmRi9oH5ENmQU2NgfFLPQRVhQ7nYYjyzcb5saZ1XJPtmik",
      "relativePath": "mid/mid/9/25/QmRi9oH5ENmQU2NgfFLPQRVhQ7nYYjyzcb5saZ1XJPtmik.mid",
      "sha256": "5db8ee09c7ec80f76e3e605edf4b1efc9526ac4a5554c586fb198cab1e6f8d66",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 53,
        "tracks": 8,
        "families": [
          "guitar",
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 70,
        "tempoChanges": 0,
        "notesPerBar": 29.38,
        "swingRatio": 0,
        "effectivePitchClasses": 6.85
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmY6WMtfD8J78NL7m1T8wDDvYg9EP1FUbKpxpoQPEAFyWC",
    "title": "Parsifal WWV 111",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Parsifal WWV 111 (PDMX QmY6WMtfD8J78NL7m1T8wDDvYg9EP1FUbKpxpoQPEAFyWC, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Richard Wagner",
      "composerDied": 1883
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmY6WMtfD8J78NL7m1T8wDDvYg9EP1FUbKpxpoQPEAFyWC",
      "relativePath": "mid/mid/16/5/QmY6WMtfD8J78NL7m1T8wDDvYg9EP1FUbKpxpoQPEAFyWC.mid",
      "sha256": "d045df4837933db5669c500afe1829bd1bfdae53e211affae7bac993d2350011",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 68,
        "tracks": 27,
        "families": [
          "brass",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 3,
        "notesPerBar": 64.29,
        "swingRatio": 0.0392,
        "effectivePitchClasses": 11.28
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical",
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmQKhXJ45WEpxojLTX2GcPqwgFkUfDXbGVjG3GtdHfGvQn",
    "title": "Maurerische Trauermusik K.477/479a",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Maurerische Trauermusik K.477/479a (PDMX QmQKhXJ45WEpxojLTX2GcPqwgFkUfDXbGVjG3GtdHfGvQn, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Wolfgang Amadeus Mozart",
      "composerDied": 1791
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "2/2",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmQKhXJ45WEpxojLTX2GcPqwgFkUfDXbGVjG3GtdHfGvQn",
      "relativePath": "mid/mid/8/29/QmQKhXJ45WEpxojLTX2GcPqwgFkUfDXbGVjG3GtdHfGvQn.mid",
      "sha256": "f3f5dd1e5e01dd2c1183306b8cebfc63afd361c34c1cad53e4f7d06347408dd1",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 70,
        "tracks": 12,
        "families": [
          "brass",
          "reed",
          "strings"
        ],
        "meter": "2/2",
        "tempoBpm": 70,
        "tempoChanges": 3,
        "notesPerBar": 31.26,
        "swingRatio": 0,
        "effectivePitchClasses": 8.36
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmVub35843rfqDG6a5QWkdikfMyynfsyrYAihB31WJT6Pf",
    "title": "Sanctus à 12 (1597)",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Sanctus à 12 (1597) (PDMX QmVub35843rfqDG6a5QWkdikfMyynfsyrYAihB31WJT6Pf, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Giovanni Gabrieli",
      "composerDied": 1612
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmVub35843rfqDG6a5QWkdikfMyynfsyrYAihB31WJT6Pf",
      "relativePath": "mid/mid/13/46/QmVub35843rfqDG6a5QWkdikfMyynfsyrYAihB31WJT6Pf.mid",
      "sha256": "74fc716692bfb1b1b2230d9a21deda8011dcdf384fb68940e5448016f73ee53b",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 51,
        "tracks": 18,
        "families": [
          "chromatic_perc",
          "keys",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 96,
        "tempoChanges": 0,
        "notesPerBar": 35.02,
        "swingRatio": 0,
        "effectivePitchClasses": 7.81
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmPnMysjKyz1GSqYvR4tFgs3TgL5TgVxqsNGr7MPDUhj2C",
    "title": "Sinfonia in F minor BWV 795",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Sinfonia in F minor BWV 795 (PDMX QmPnMysjKyz1GSqYvR4tFgs3TgL5TgVxqsNGr7MPDUhj2C, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Sebastian Bach",
      "composerDied": 1750
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmPnMysjKyz1GSqYvR4tFgs3TgL5TgVxqsNGr7MPDUhj2C",
      "relativePath": "mid/mid/7/33/QmPnMysjKyz1GSqYvR4tFgs3TgL5TgVxqsNGr7MPDUhj2C.mid",
      "sha256": "05a620974901386fc066f6d5cdc89e2c59ce87f2011166c1a675e2784345eade",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 35,
        "tracks": 3,
        "families": [
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 42,
        "tempoChanges": 4,
        "notesPerBar": 19.03,
        "swingRatio": 0.0073,
        "effectivePitchClasses": 10.76
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmdjNEQuyT2BJ7WKuqsqC6fBx8uuEfDYUPNLoV6VCimnoG",
    "title": "Ave Maria Op. 145",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Ave Maria Op. 145 (PDMX QmdjNEQuyT2BJ7WKuqsqC6fBx8uuEfDYUPNLoV6VCimnoG, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Camille Saint-Saëns",
      "composerDied": 1921
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmdjNEQuyT2BJ7WKuqsqC6fBx8uuEfDYUPNLoV6VCimnoG",
      "relativePath": "mid/mid/3/26/QmdjNEQuyT2BJ7WKuqsqC6fBx8uuEfDYUPNLoV6VCimnoG.mid",
      "sha256": "84e407a5cfa4e347838306a372023c308c7c474e1da688a28a202f67268547f3",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 77,
        "tracks": 6,
        "families": [
          "ensemble",
          "keys",
          "pipe"
        ],
        "meter": "3/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 8.75,
        "swingRatio": 0,
        "effectivePitchClasses": 9.55
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmacZvReyzBnUFUNGyNCk7sfmz8mC6w6knAvPqsHDB9RdF",
    "title": "Repentir",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Repentir (PDMX QmacZvReyzBnUFUNGyNCk7sfmz8mC6w6knAvPqsHDB9RdF, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Charles Gounod",
      "composerDied": 1893
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmacZvReyzBnUFUNGyNCk7sfmz8mC6w6knAvPqsHDB9RdF",
      "relativePath": "mid/mid/0/13/QmacZvReyzBnUFUNGyNCk7sfmz8mC6w6knAvPqsHDB9RdF.mid",
      "sha256": "2e37210173a412b3f07ea312f990070c54894ab07b31d056e41acbe7ec4fe900",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 92,
        "tracks": 8,
        "families": [
          "brass",
          "ensemble",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 72,
        "tempoChanges": 9,
        "notesPerBar": 51.72,
        "swingRatio": 0.0527,
        "effectivePitchClasses": 10.25
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmPSDehUeJySKzfRhGcyeFqV8ket1fRPuS6L11TXtnfryA",
    "title": "Requiem in D minor K.626",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Requiem in D minor K.626 (PDMX QmPSDehUeJySKzfRhGcyeFqV8ket1fRPuS6L11TXtnfryA, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Wolfgang Amadeus Mozart",
      "composerDied": 1791
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmPSDehUeJySKzfRhGcyeFqV8ket1fRPuS6L11TXtnfryA",
      "relativePath": "mid/mid/7/43/QmPSDehUeJySKzfRhGcyeFqV8ket1fRPuS6L11TXtnfryA.mid",
      "sha256": "84db781fd501d1c144d8fa05b4ff6cf88a207770b9c09369658874f2ce921ad3",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 83,
        "tracks": 18,
        "families": [
          "brass",
          "ensemble",
          "keys",
          "organ",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 37,
        "tempoChanges": 7,
        "notesPerBar": 108.17,
        "swingRatio": 0,
        "effectivePitchClasses": 9.94
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmUd76kyxzBGnDj6f4Gdvd1qrPncxUMAp3Qo2G5AGDPmqE",
    "title": "Romance Op.36",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Romance Op.36 (PDMX QmUd76kyxzBGnDj6f4Gdvd1qrPncxUMAp3Qo2G5AGDPmqE, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Camille Saint-Saëns",
      "composerDied": 1921
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmUd76kyxzBGnDj6f4Gdvd1qrPncxUMAp3Qo2G5AGDPmqE",
      "relativePath": "mid/mid/12/15/QmUd76kyxzBGnDj6f4Gdvd1qrPncxUMAp3Qo2G5AGDPmqE.mid",
      "sha256": "cf1574616896864cbc43639438d6fd1f70a7ec2779e77789fb65cda3a885b8fd",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 93,
        "tracks": 12,
        "families": [
          "brass",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 76,
        "tempoChanges": 17,
        "notesPerBar": 14.37,
        "swingRatio": 0,
        "effectivePitchClasses": 8.37
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmYswpCbtf9oM4g58Qj15qWdbjS7CHBMgcS7a4SLiuyTkg",
    "title": "Laudate pueri Dominum",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Laudate pueri Dominum (PDMX QmYswpCbtf9oM4g58Qj15qWdbjS7CHBMgcS7a4SLiuyTkg, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Leone Leoni",
      "composerDied": 1627
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmYswpCbtf9oM4g58Qj15qWdbjS7CHBMgcS7a4SLiuyTkg",
      "relativePath": "mid/mid/16/42/QmYswpCbtf9oM4g58Qj15qWdbjS7CHBMgcS7a4SLiuyTkg.mid",
      "sha256": "5b0bef6bb625931ed8cb749a8d16078f045b67f2091d162844d564b967f19c10",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 110,
        "tracks": 4,
        "families": [
          "brass",
          "keys",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 6.66,
        "swingRatio": 0,
        "effectivePitchClasses": 6.74
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmabLHtHwqSE1MNh6fqJeq5jv3chRXVNzWm3Uub6YU2b3v",
    "title": "La nuict froide et sombre",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "La nuict froide et sombre (PDMX QmabLHtHwqSE1MNh6fqJeq5jv3chRXVNzWm3Uub6YU2b3v, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Orlando di Lasso",
      "composerDied": 1594
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmabLHtHwqSE1MNh6fqJeq5jv3chRXVNzWm3Uub6YU2b3v",
      "relativePath": "mid/mid/0/11/QmabLHtHwqSE1MNh6fqJeq5jv3chRXVNzWm3Uub6YU2b3v.mid",
      "sha256": "8e9fa06c12923a0b2925d4df908c1afe5cc0d94ba8b7871142163faf33967a83",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 34,
        "tracks": 4,
        "families": [
          "brass",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 106,
        "tempoChanges": 0,
        "notesPerBar": 12.88,
        "swingRatio": 0,
        "effectivePitchClasses": 8.94
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmZfbGTDQEsE19m3tsnSiGcm1Z1PCSeQZgRR1fHbRpsNSw",
    "title": "Ave verum corpus K.618",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Ave verum corpus K.618 (PDMX QmZfbGTDQEsE19m3tsnSiGcm1Z1PCSeQZgRR1fHbRpsNSw, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Wolfgang Amadeus Mozart",
      "composerDied": 1791
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmZfbGTDQEsE19m3tsnSiGcm1Z1PCSeQZgRR1fHbRpsNSw",
      "relativePath": "mid/mid/17/19/QmZfbGTDQEsE19m3tsnSiGcm1Z1PCSeQZgRR1fHbRpsNSw.mid",
      "sha256": "9c5ad1116b3825fef24f86b15183efb8042e875d0ee74dfb58bd7d746a4cb57f",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 46,
        "tracks": 8,
        "families": [
          "ensemble",
          "keys",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 60,
        "tempoChanges": 1,
        "notesPerBar": 17.96,
        "swingRatio": 0.087,
        "effectivePitchClasses": 8.84
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmVUs32cGZC7fe5RN2AaeWxiJEb9f2ht2EHCBNqa5z1RRM",
    "title": "Magnificat in E-flat major BWV 243a",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Magnificat in E-flat major BWV 243a (PDMX QmVUs32cGZC7fe5RN2AaeWxiJEb9f2ht2EHCBNqa5z1RRM, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Sebastian Bach",
      "composerDied": 1750
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/8",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmVUs32cGZC7fe5RN2AaeWxiJEb9f2ht2EHCBNqa5z1RRM",
      "relativePath": "mid/mid/13/47/QmVUs32cGZC7fe5RN2AaeWxiJEb9f2ht2EHCBNqa5z1RRM.mid",
      "sha256": "cda4aeb4883670fa76585aa1dc674e3d344fb3be1c210bdbe173725b4c580a08",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 92,
        "tracks": 6,
        "families": [
          "ensemble",
          "organ",
          "strings"
        ],
        "meter": "3/8",
        "tempoBpm": 60,
        "tempoChanges": 0,
        "notesPerBar": 17.67,
        "swingRatio": 0,
        "effectivePitchClasses": 8.37
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmNeeCREFpNohPbnUgeuEWdb6PT1jo2DmqxndJD4dkt8GH",
    "title": "Weihnachtsoratorium BWV 248",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Weihnachtsoratorium BWV 248 (PDMX QmNeeCREFpNohPbnUgeuEWdb6PT1jo2DmqxndJD4dkt8GH, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Sebastian Bach",
      "composerDied": 1750
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "12/8",
      "feel": "compound",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmNeeCREFpNohPbnUgeuEWdb6PT1jo2DmqxndJD4dkt8GH",
      "relativePath": "mid/mid/6/17/QmNeeCREFpNohPbnUgeuEWdb6PT1jo2DmqxndJD4dkt8GH.mid",
      "sha256": "7617759deeeca68002400177ed2f8b3c2d06f1cd0bf81460a9ef664af6f3f445",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 63,
        "tracks": 4,
        "families": [
          "keys",
          "organ",
          "strings"
        ],
        "meter": "12/8",
        "tempoBpm": 75,
        "tempoChanges": 0,
        "notesPerBar": 33.87,
        "swingRatio": 0.0073,
        "effectivePitchClasses": 9.13
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmSkrSgHGjYgtFVKRJMwoXj8qNehF4MFqM3NAcZDfSCWXk",
    "title": "Pictures at an Exhibition",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Pictures at an Exhibition (PDMX QmSkrSgHGjYgtFVKRJMwoXj8qNehF4MFqM3NAcZDfSCWXk, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Modest Mussorgsky",
      "composerDied": 1881
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmSkrSgHGjYgtFVKRJMwoXj8qNehF4MFqM3NAcZDfSCWXk",
      "relativePath": "mid/mid/10/28/QmSkrSgHGjYgtFVKRJMwoXj8qNehF4MFqM3NAcZDfSCWXk.mid",
      "sha256": "5a5e43ac1b816b126f55f4160c867eb00430faec075c0efb951ccf31094d9ff0",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 30,
        "tracks": 13,
        "families": [
          "brass",
          "reed",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 53.33,
        "tempoChanges": 33,
        "notesPerBar": 7.47,
        "swingRatio": null,
        "effectivePitchClasses": 8.93
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmYRN81aYQwTnBC8T29MbuYeEPanGKE1fF7idpSDYcmsW4",
    "title": "Sospir che dal bel petto",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Sospir che dal bel petto (PDMX QmYRN81aYQwTnBC8T29MbuYeEPanGKE1fF7idpSDYcmsW4, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Constantijn Huygens",
      "composerDied": 1687
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmYRN81aYQwTnBC8T29MbuYeEPanGKE1fF7idpSDYcmsW4",
      "relativePath": "mid/mid/16/41/QmYRN81aYQwTnBC8T29MbuYeEPanGKE1fF7idpSDYcmsW4.mid",
      "sha256": "25301e5ca5f897b02e703a68cabb2e7b3d81378bd5ed4007b51e441f625c3914",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 38,
        "tracks": 4,
        "families": [
          "ensemble",
          "keys",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 60,
        "tempoChanges": 1,
        "notesPerBar": 15.05,
        "swingRatio": 0,
        "effectivePitchClasses": 7.95
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmWQW2UNmevbsAeoWY6cFcswHx3veUXD32gaGFRJuRy6UT",
    "title": "Symphonie No.1 Op.14",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Symphonie No.1 Op.14 (PDMX QmWQW2UNmevbsAeoWY6cFcswHx3veUXD32gaGFRJuRy6UT, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Louis Vierne",
      "composerDied": 1937
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "2/2",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmWQW2UNmevbsAeoWY6cFcswHx3veUXD32gaGFRJuRy6UT",
      "relativePath": "mid/mid/14/39/QmWQW2UNmevbsAeoWY6cFcswHx3veUXD32gaGFRJuRy6UT.mid",
      "sha256": "0a08cf1138993ed99176a3a482e97b381c5bc900d851b141b44e0ac808d45783",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 81,
        "tracks": 12,
        "families": [
          "brass",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "2/2",
        "tempoBpm": 176,
        "tempoChanges": 4,
        "notesPerBar": 107.78,
        "swingRatio": 0.0655,
        "effectivePitchClasses": 8.94
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmagNp8uSuDjmqYA4Fdmy5heeqtruuSujihZGHzzHLFveo",
    "title": "Herr Jesu Christ du höchstes Gut BWV 113",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Herr Jesu Christ du höchstes Gut BWV 113 (PDMX QmagNp8uSuDjmqYA4Fdmy5heeqtruuSujihZGHzzHLFveo, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Sebastian Bach",
      "composerDied": 1750
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "12/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmagNp8uSuDjmqYA4Fdmy5heeqtruuSujihZGHzzHLFveo",
      "relativePath": "mid/mid/0/21/QmagNp8uSuDjmqYA4Fdmy5heeqtruuSujihZGHzzHLFveo.mid",
      "sha256": "04e33042234b63ebc397fc64e01372e62f06298149196488c688458e1d3dfd00",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 48,
        "tracks": 6,
        "families": [
          "brass",
          "organ",
          "reed",
          "strings"
        ],
        "meter": "12/8",
        "tempoBpm": 120,
        "tempoChanges": 18,
        "notesPerBar": 46.58,
        "swingRatio": 0,
        "effectivePitchClasses": 8.43
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaiVgivyKRqDRrVGCBm7RntRAS8ycfhXNZPfisacyq8xB",
    "title": "Dido and Aeneas Z.626",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Dido and Aeneas Z.626 (PDMX QmaiVgivyKRqDRrVGCBm7RntRAS8ycfhXNZPfisacyq8xB, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Henry Purcell",
      "composerDied": 1695
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaiVgivyKRqDRrVGCBm7RntRAS8ycfhXNZPfisacyq8xB",
      "relativePath": "mid/mid/0/25/QmaiVgivyKRqDRrVGCBm7RntRAS8ycfhXNZPfisacyq8xB.mid",
      "sha256": "c8e8c9cdb9d434124302a5bf522b215a90b6e4567e7cf5c9288ee815f89e861e",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 58,
        "tracks": 6,
        "families": [
          "ensemble",
          "keys",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 85,
        "tempoChanges": 1,
        "notesPerBar": 17.57,
        "swingRatio": 0.0175,
        "effectivePitchClasses": 8.66
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmbuiKkdzFVTc2nw7gVz27vnKqpxX8wzGJtuJCKVibqXJW",
    "title": "I was Glad",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "I was Glad (PDMX QmbuiKkdzFVTc2nw7gVz27vnKqpxX8wzGJtuJCKVibqXJW, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Hubert Parry",
      "composerDied": 1918
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmbuiKkdzFVTc2nw7gVz27vnKqpxX8wzGJtuJCKVibqXJW",
      "relativePath": "mid/mid/1/46/QmbuiKkdzFVTc2nw7gVz27vnKqpxX8wzGJtuJCKVibqXJW.mid",
      "sha256": "649cfeeea7dccb8a4eb274f43aed41aefc677886c4b3ee890448e0420eaef9ed",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 81,
        "tracks": 13,
        "families": [
          "brass",
          "ensemble",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 72,
        "tempoChanges": 7,
        "notesPerBar": 46.43,
        "swingRatio": 0,
        "effectivePitchClasses": 10.04
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmRazo5uaUEZxMyvVRquR2RJgCTFj2NoVdaaRKCvLWUZVT",
    "title": "Du sollt Gott deinen Herren lieben BWV 77",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Du sollt Gott deinen Herren lieben BWV 77 (PDMX QmRazo5uaUEZxMyvVRquR2RJgCTFj2NoVdaaRKCvLWUZVT, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Johann Sebastian Bach",
      "composerDied": 1750
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmRazo5uaUEZxMyvVRquR2RJgCTFj2NoVdaaRKCvLWUZVT",
      "relativePath": "mid/mid/9/9/QmRazo5uaUEZxMyvVRquR2RJgCTFj2NoVdaaRKCvLWUZVT.mid",
      "sha256": "b00ac710b375ed1e2c5c7509521d1905e41dc5b29ba18e053d96d867c42b0ade",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 65,
        "tracks": 4,
        "families": [
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 60,
        "tempoChanges": 0,
        "notesPerBar": 28.38,
        "swingRatio": 0,
        "effectivePitchClasses": 9.53
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmUWMUkMcVhUk6DJNQf4LmYnhvpL4Gh3YYebVzc2jHon8g",
    "title": "Bring a Torch Jeanette Isabella",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Bring a Torch Jeanette Isabella (PDMX QmUWMUkMcVhUk6DJNQf4LmYnhvpL4Gh3YYebVzc2jHon8g, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "traditional": true,
      "source": "Bring a Torch, Jeanette, Isabella: Provençal carol, 17th century"
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/8",
      "feel": "straight",
      "harmony": "simple",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmUWMUkMcVhUk6DJNQf4LmYnhvpL4Gh3YYebVzc2jHon8g",
      "relativePath": "mid/mid/12/51/QmUWMUkMcVhUk6DJNQf4LmYnhvpL4Gh3YYebVzc2jHon8g.mid",
      "sha256": "ac40ee39be8886196aef4ef5163e72a5d7197c3d3db99267fea0fa00bc4e9a08",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 59,
        "tracks": 6,
        "families": [
          "brass",
          "chromatic_perc",
          "guitar"
        ],
        "meter": "3/8",
        "tempoBpm": 93,
        "tempoChanges": 0,
        "notesPerBar": 7.58,
        "swingRatio": null,
        "effectivePitchClasses": 6.34
      },
      "genre": {
        "primary": "folk",
        "families": [
          "folk"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmSjcutfPijpJPFnCwwpuuVbszjuAFHSg9WFtvMiFZZ8D7",
    "title": "Psalm 90 - Herr du bist uns're Zuflucht",
    "inputType": "midi",
    "rights": {
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Psalm 90 - Herr du bist uns're Zuflucht (PDMX QmSjcutfPijpJPFnCwwpuuVbszjuAFHSg9WFtvMiFZZ8D7, no_license_conflict)",
      "clearedAt": "2026-09-10T03:59:30.891Z",
      "kind": "public_domain",
      "commercialUse": true,
      "composer": "Jan Pieterszoon Sweelinck",
      "composerDied": 1621
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmSjcutfPijpJPFnCwwpuuVbszjuAFHSg9WFtvMiFZZ8D7",
      "relativePath": "mid/mid/10/26/QmSjcutfPijpJPFnCwwpuuVbszjuAFHSg9WFtvMiFZZ8D7.mid",
      "sha256": "36e88901b92520304af98960bd7bbb688e99c8449ff136a99a3be14e08bcb9da",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 29,
        "tracks": 4,
        "families": [
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 55,
        "tempoChanges": 2,
        "notesPerBar": 16.1,
        "swingRatio": 0,
        "effectivePitchClasses": 7.89
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  }
];
