/**
 * Tier H entries of the real benchmark corpus (Brain B-08). GENERATED by
 * `scripts/select-real-corpus.mjs` on 2026-09-10 from PDMX.csv
 * (222856 admitted rows, 25414 multitrack) and the MIDI on disk; the
 * selection report with every measurement and every gap is
 * `docs/evidence/real-corpus-tier-h-selection.json`. Re-run the script to
 * regenerate; do not edit by hand.
 *
 * Every attribute below was measured from the work's MIDI or read from its
 * PDMX row (see the report's `method`); rights are per work, from the row's
 * own licence statement. Coverage gaps are reported by `corpusCoverage`,
 * never filled synthetically.
 */
import type { CorpusEntry } from "./benchmarkCorpusPlan";

export const REAL_CORPUS_TIER_H_GENERATED_AT = "2026-09-10T03:17:23.563Z";

export const REAL_CORPUS_TIER_H: CorpusEntry[] = [
  {
    "id": "pdmx-QmaxnwxSTa3JMZNAFwY8j1fzFKYFPZYsWcAiQrNvWd9hRU",
    "title": "guantanamera",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "guantanamera (PDMX QmaxnwxSTa3JMZNAFwY8j1fzFKYFPZYsWcAiQrNvWd9hRU, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "non_western",
      "production": "acoustic",
      "tradition": "world_traditional"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaxnwxSTa3JMZNAFwY8j1fzFKYFPZYsWcAiQrNvWd9hRU",
      "relativePath": "mid/mid/0/52/QmaxnwxSTa3JMZNAFwY8j1fzFKYFPZYsWcAiQrNvWd9hRU.mid",
      "sha256": "68e98b9a0d0de8e6dff93290356bc656a22810b538e63c5c1d06c37eb09266e5",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 103,
        "tracks": 9,
        "families": [
          "bass",
          "chromatic_perc",
          "drums",
          "guitar",
          "keys"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 41.23,
        "swingRatio": 0.0115,
        "effectivePitchClasses": 7.28
      },
      "genre": {
        "primary": "world_traditional",
        "families": [
          "world_traditional"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmNwf6GRbingp8jNGB7BgyPZ8nhWWvLjF1jZzEXUF4LxvQ",
    "title": "tong hua",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "tong hua (PDMX QmNwf6GRbingp8jNGB7BgyPZ8nhWWvLjF1jZzEXUF4LxvQ, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "non_western",
      "production": "acoustic",
      "tradition": "world_traditional"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmNwf6GRbingp8jNGB7BgyPZ8nhWWvLjF1jZzEXUF4LxvQ",
      "relativePath": "mid/mid/6/50/QmNwf6GRbingp8jNGB7BgyPZ8nhWWvLjF1jZzEXUF4LxvQ.mid",
      "sha256": "90ae96a6e48a700d2404f358c3180993e8cd419301b831b7a93c992fd8e3eb7d",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 66,
        "tracks": 6,
        "families": [
          "drums",
          "keys",
          "strings",
          "synth"
        ],
        "meter": "4/4",
        "tempoBpm": 66,
        "tempoChanges": 0,
        "notesPerBar": 29.42,
        "swingRatio": 0.0031,
        "effectivePitchClasses": 9.7
      },
      "genre": {
        "primary": "world_traditional",
        "families": [
          "world_traditional"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmassW1LM1SqYqu6jnexbafnq2q5BEwVQiT6w79SrxVCvS",
    "title": "Procuro Olvidarte",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Procuro Olvidarte (PDMX QmassW1LM1SqYqu6jnexbafnq2q5BEwVQiT6w79SrxVCvS, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "non_western",
      "production": "acoustic",
      "tradition": "world_traditional"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmassW1LM1SqYqu6jnexbafnq2q5BEwVQiT6w79SrxVCvS",
      "relativePath": "mid/mid/0/42/QmassW1LM1SqYqu6jnexbafnq2q5BEwVQiT6w79SrxVCvS.mid",
      "sha256": "34ef174d90caeec456cba41f4ec997bd2ab6b3585a2d9284fdfb757b6b5ff721",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 43,
        "tracks": 4,
        "families": [
          "brass",
          "ensemble",
          "keys"
        ],
        "meter": "4/4",
        "tempoBpm": 75,
        "tempoChanges": 1,
        "notesPerBar": 15.3,
        "swingRatio": 0.2138,
        "effectivePitchClasses": 7.28
      },
      "genre": {
        "primary": "world_traditional",
        "families": [
          "world_traditional"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmacuG15tfzWWXG7SNHuHpXL7RjEMPURsTNnppD6ALETtH",
    "title": "Christmas Yee in Three",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Christmas Yee in Three (PDMX QmacuG15tfzWWXG7SNHuHpXL7RjEMPURsTNnppD6ALETtH, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "3/4",
      "feel": "swung",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmacuG15tfzWWXG7SNHuHpXL7RjEMPURsTNnppD6ALETtH",
      "relativePath": "mid/mid/0/13/QmacuG15tfzWWXG7SNHuHpXL7RjEMPURsTNnppD6ALETtH.mid",
      "sha256": "c51e1291e6b26d4d5689ced77abee37fa017e07f9e76f5dd93511080b6026c1d",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 151,
        "tracks": 7,
        "families": [
          "bass",
          "brass",
          "drums",
          "keys",
          "reed"
        ],
        "meter": "3/4",
        "tempoBpm": 155,
        "tempoChanges": 0,
        "notesPerBar": 16.28,
        "swingRatio": 1,
        "effectivePitchClasses": 6.9
      },
      "genre": {
        "primary": "jazz",
        "families": [
          "jazz"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmaogLCs2WhXCuJKogH558zJE51JeNXxQ4C7RejKmwPnev",
    "title": "For smart living",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "For smart living (PDMX QmaogLCs2WhXCuJKogH558zJE51JeNXxQ4C7RejKmwPnev, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "8/8",
      "feel": "swung",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaogLCs2WhXCuJKogH558zJE51JeNXxQ4C7RejKmwPnev",
      "relativePath": "mid/mid/0/35/QmaogLCs2WhXCuJKogH558zJE51JeNXxQ4C7RejKmwPnev.mid",
      "sha256": "3e9e188d60d092a91e52d7f34b955a32fb7a9fc07810307513281267a8ff6dbf",
      "admittedBy": "tournament-classical",
      "measured": {
        "bars": 81,
        "tracks": 3,
        "families": [
          "brass",
          "drums",
          "reed"
        ],
        "meter": "8/8",
        "tempoBpm": 95,
        "tempoChanges": 0,
        "notesPerBar": 19.98,
        "swingRatio": 1,
        "effectivePitchClasses": 4.45
      },
      "genre": {
        "primary": "unlabelled",
        "families": [
          "unlabelled"
        ],
        "source": "none"
      }
    }
  },
  {
    "id": "pdmx-QmaChhKKLYJWXX4nbSyCyNtdEk69GGBQJ6DPA1FcazWyY3",
    "title": "On the Take",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "On the Take (PDMX QmaChhKKLYJWXX4nbSyCyNtdEk69GGBQJ6DPA1FcazWyY3, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "swung",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaChhKKLYJWXX4nbSyCyNtdEk69GGBQJ6DPA1FcazWyY3",
      "relativePath": "mid/mid/0/14/QmaChhKKLYJWXX4nbSyCyNtdEk69GGBQJ6DPA1FcazWyY3.mid",
      "sha256": "1c2103beca1ea98dc9effff894b4c267a6d8121fd78f1fa2481d53ddd686c27a",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 112,
        "tracks": 11,
        "families": [
          "brass",
          "drums",
          "keys",
          "reed",
          "synth"
        ],
        "meter": "4/4",
        "tempoBpm": 130,
        "tempoChanges": 0,
        "notesPerBar": 42.66,
        "swingRatio": 0.8338,
        "effectivePitchClasses": 9.38
      },
      "genre": {
        "primary": "blues",
        "families": [
          "blues"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmbuxgCLicDNZhBAFRUN83FnS13caK5St3DbmRmiTnbyFi",
    "title": "Viva Cristo Rey",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Viva Cristo Rey (PDMX QmbuxgCLicDNZhBAFRUN83FnS13caK5St3DbmRmiTnbyFi, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmbuxgCLicDNZhBAFRUN83FnS13caK5St3DbmRmiTnbyFi",
      "relativePath": "mid/mid/1/46/QmbuxgCLicDNZhBAFRUN83FnS13caK5St3DbmRmiTnbyFi.mid",
      "sha256": "5863b8e2cb5bbcb4eeacdeed156bc0fa374fc548a06a0556e4292ec05515a67d",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 121,
        "tracks": 5,
        "families": [
          "guitar",
          "keys",
          "organ",
          "reed"
        ],
        "meter": "6/8",
        "tempoBpm": 100,
        "tempoChanges": 0,
        "notesPerBar": 55.43,
        "swingRatio": 0,
        "effectivePitchClasses": 6.45
      },
      "genre": {
        "primary": "religious_worship",
        "families": [
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmahFMNjxfieADi4t4iM3nCBgr3L2Jymjm8e2wJjczogPF",
    "title": "Dont Let Me Go",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Dont Let Me Go (PDMX QmahFMNjxfieADi4t4iM3nCBgr3L2Jymjm8e2wJjczogPF, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "non_western",
      "production": "acoustic",
      "tradition": "rock"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmahFMNjxfieADi4t4iM3nCBgr3L2Jymjm8e2wJjczogPF",
      "relativePath": "mid/mid/0/23/QmahFMNjxfieADi4t4iM3nCBgr3L2Jymjm8e2wJjczogPF.mid",
      "sha256": "47554f82e44a0632d8074d47925c023194a3af40c6d74582765392ba17cbe8d7",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 130,
        "tracks": 11,
        "families": [
          "bass",
          "brass",
          "drums",
          "guitar",
          "keys",
          "pipe",
          "strings",
          "synth"
        ],
        "meter": "6/8",
        "tempoBpm": 100,
        "tempoChanges": 1,
        "notesPerBar": 51.66,
        "swingRatio": 0.0621,
        "effectivePitchClasses": 6.63
      },
      "genre": {
        "primary": "rock",
        "families": [
          "rock"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmcyP7UNchU4YMGwNp1KhopxYD6CnkkMe3Fs87XEFXMRuM",
    "title": "earth angel will you be mine",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "earth angel will you be mine (PDMX QmcyP7UNchU4YMGwNp1KhopxYD6CnkkMe3Fs87XEFXMRuM, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "6/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmcyP7UNchU4YMGwNp1KhopxYD6CnkkMe3Fs87XEFXMRuM",
      "relativePath": "mid/mid/2/54/QmcyP7UNchU4YMGwNp1KhopxYD6CnkkMe3Fs87XEFXMRuM.mid",
      "sha256": "e841238d0a913a196952d102441b239f438b4f7dee640b45281c29781f3e8ebe",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 37,
        "tracks": 6,
        "families": [
          "bass",
          "drums",
          "guitar",
          "keys",
          "reed"
        ],
        "meter": "6/8",
        "tempoBpm": 100,
        "tempoChanges": 0,
        "notesPerBar": 42.68,
        "swingRatio": null,
        "effectivePitchClasses": 7.53
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmaetaqYGz3UfazAh9AULVNpaxnP62CskUZWfG37g8Q2bW",
    "title": "time in a bottle",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "time in a bottle (PDMX QmaetaqYGz3UfazAh9AULVNpaxnP62CskUZWfG37g8Q2bW, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaetaqYGz3UfazAh9AULVNpaxnP62CskUZWfG37g8Q2bW",
      "relativePath": "mid/mid/0/17/QmaetaqYGz3UfazAh9AULVNpaxnP62CskUZWfG37g8Q2bW.mid",
      "sha256": "7d548020940a19c66fbda035a429e771eaa5eb508aa6195afcdcf09b68b5ceac",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 93,
        "tracks": 9,
        "families": [
          "drums",
          "ensemble",
          "guitar",
          "keys",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 140,
        "tempoChanges": 9,
        "notesPerBar": 47.45,
        "swingRatio": 0,
        "effectivePitchClasses": 8.41
      },
      "genre": {
        "primary": "folk",
        "families": [
          "folk"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr",
    "title": "Silent night - Instrumental flute - flugehorn - violin",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Silent night - Instrumental flute - flugehorn - violin (PDMX QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "3/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr",
      "relativePath": "mid/mid/0/13/QmacY5xSh18WXR348MvKWuvzpuAfRqe8ieh6m8gpNQbyNr.mid",
      "sha256": "7c0eba20b4129812668e2eef7982da0b0b04adb6910f376836214cbf0be74dbc",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 93,
        "tracks": 7,
        "families": [
          "bass",
          "brass",
          "drums",
          "keys",
          "pipe",
          "strings"
        ],
        "meter": "3/4",
        "tempoBpm": 90,
        "tempoChanges": 0,
        "notesPerBar": 14.7,
        "swingRatio": 0.0082,
        "effectivePitchClasses": 8.19
      },
      "genre": {
        "primary": "film_game",
        "families": [
          "film_game",
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1",
    "title": "Symphony No.9 Op.125",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Symphony No.9 Op.125 (PDMX QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "2/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "sparse",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1",
      "relativePath": "mid/mid/17/36/QmZpW5y91mNNqfY1ofLXkGQDe31eJfr8FR4JWcpT6qapD1.mid",
      "sha256": "f384ebdc3cd174f244ed7b886e348a4e80ba673d79f61c8e19ca940204402a86",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 32,
        "tracks": 3,
        "families": [
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "2/4",
        "tempoBpm": 80,
        "tempoChanges": 0,
        "notesPerBar": 5.63,
        "swingRatio": null,
        "effectivePitchClasses": 5.9
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmYwCRCydYK2Na6mn5mh9AMMb64BwZv5yx1DpigpyKBtLC",
    "title": "I Can't Breathe",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "I Can't Breathe (PDMX QmYwCRCydYK2Na6mn5mh9AMMb64BwZv5yx1DpigpyKBtLC, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "sparse",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmYwCRCydYK2Na6mn5mh9AMMb64BwZv5yx1DpigpyKBtLC",
      "relativePath": "mid/mid/16/50/QmYwCRCydYK2Na6mn5mh9AMMb64BwZv5yx1DpigpyKBtLC.mid",
      "sha256": "09521652fbc5a12b2ba16b8e99c71e5cc00de596b8442dc42cd49ab0f15c9bd8",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 64,
        "tracks": 7,
        "families": [
          "drums",
          "keys",
          "organ",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 72,
        "tempoChanges": 1,
        "notesPerBar": 5.31,
        "swingRatio": 0,
        "effectivePitchClasses": 6.98
      },
      "genre": {
        "primary": "film_game",
        "families": [
          "film_game"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-Qmf7FdCC3DBZvRLTi39zUniikKvXYdZky7upgtJLUpb9Xa",
    "title": "Eleven",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Eleven (PDMX Qmf7FdCC3DBZvRLTi39zUniikKvXYdZky7upgtJLUpb9Xa, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "sparse",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "Qmf7FdCC3DBZvRLTi39zUniikKvXYdZky7upgtJLUpb9Xa",
      "relativePath": "mid/mid/5/6/Qmf7FdCC3DBZvRLTi39zUniikKvXYdZky7upgtJLUpb9Xa.mid",
      "sha256": "ff847fd747e612cf188e68962e5d793036297d7bdf4a793e9e5877de533b85ad",
      "admittedBy": "b08-csv-scan",
      "measured": {
        "bars": 49,
        "tracks": 10,
        "families": [
          "bass",
          "brass",
          "chromatic_perc",
          "keys"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 5.41,
        "swingRatio": null,
        "effectivePitchClasses": 5.64
      },
      "genre": {
        "primary": "classical",
        "families": [
          "classical"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmWu1GKEdGjxwwV9ePmmSbmUN4y5cmYMpMkXJK2EUxVh1J",
    "title": "Mamma Mia!",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Mamma Mia! (PDMX QmWu1GKEdGjxwwV9ePmmSbmUN4y5cmYMpMkXJK2EUxVh1J, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmWu1GKEdGjxwwV9ePmmSbmUN4y5cmYMpMkXJK2EUxVh1J",
      "relativePath": "mid/mid/14/46/QmWu1GKEdGjxwwV9ePmmSbmUN4y5cmYMpMkXJK2EUxVh1J.mid",
      "sha256": "fce667842c63efae4711e6405b3fd7110a52085b69b6c70fc4f14cec8e3d2542",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 83,
        "tracks": 17,
        "families": [
          "brass",
          "drums",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 140,
        "tempoChanges": 0,
        "notesPerBar": 72.67,
        "swingRatio": 0.0242,
        "effectivePitchClasses": 9.04
      },
      "genre": {
        "primary": "musical_theatre",
        "families": [
          "musical_theatre"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmaPWhAxxRc8s16bjJVeEGEKEvKWKzNqg7W2qakbByRrL4",
    "title": "Pure Cocaine",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Pure Cocaine (PDMX QmaPWhAxxRc8s16bjJVeEGEKEvKWKzNqg7W2qakbByRrL4, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaPWhAxxRc8s16bjJVeEGEKEvKWKzNqg7W2qakbByRrL4",
      "relativePath": "mid/mid/0/37/QmaPWhAxxRc8s16bjJVeEGEKEvKWKzNqg7W2qakbByRrL4.mid",
      "sha256": "30f639964d68bec2f3e30bc81849ff6a10162ff2618e657d3ff982e901392d82",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 33,
        "tracks": 11,
        "families": [
          "brass",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 60,
        "tempoChanges": 0,
        "notesPerBar": 48.33,
        "swingRatio": 0.0497,
        "effectivePitchClasses": 6.29
      },
      "genre": {
        "primary": "hiphop",
        "families": [
          "hiphop",
          "wind_band_marching"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW",
    "title": "Benedictus uit Messe Solonelle",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Benedictus uit Messe Solonelle (PDMX QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW",
      "relativePath": "mid/mid/1/9/QmbaPnp5ffQMNGPJh7cF5pTU3ewYpAhJ3i3EfooSny54jW.mid",
      "sha256": "3df52f6e8e21fe4ee2282e975089095b61f5fa22d980161d3f96238bc635ce83",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 57,
        "tracks": 10,
        "families": [
          "ensemble",
          "keys",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 84,
        "tempoChanges": 1,
        "notesPerBar": 16.89,
        "swingRatio": 0,
        "effectivePitchClasses": 9.75
      },
      "genre": {
        "primary": "religious_worship",
        "families": [
          "religious_worship"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaCJHoZ3Un2y3r9vWYYAuxFjNgQSmYcLvmztgFDh4SK6E",
    "title": "country roads",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "country roads (PDMX QmaCJHoZ3Un2y3r9vWYYAuxFjNgQSmYcLvmztgFDh4SK6E, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaCJHoZ3Un2y3r9vWYYAuxFjNgQSmYcLvmztgFDh4SK6E",
      "relativePath": "mid/mid/0/14/QmaCJHoZ3Un2y3r9vWYYAuxFjNgQSmYcLvmztgFDh4SK6E.mid",
      "sha256": "dbd43b3c86a4769fcd2dae48e5cb8e9b46e7f0b658d59eb46a9eb4c66fccb870",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 82,
        "tracks": 10,
        "families": [
          "brass",
          "chromatic_perc",
          "drums",
          "ethnic",
          "keys",
          "organ",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 100,
        "tempoChanges": 23,
        "notesPerBar": 54.05,
        "swingRatio": 0,
        "effectivePitchClasses": 7.53
      },
      "genre": {
        "primary": "pop",
        "families": [
          "pop"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmabLFxpikYVjcZXgubR9kVaJN6ctKXYSYnWYMpBsWubN5",
    "title": "Nipsey Hussle x Victory Lap",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Nipsey Hussle x Victory Lap (PDMX QmabLFxpikYVjcZXgubR9kVaJN6ctKXYSYnWYMpBsWubN5, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmabLFxpikYVjcZXgubR9kVaJN6ctKXYSYnWYMpBsWubN5",
      "relativePath": "mid/mid/0/11/QmabLFxpikYVjcZXgubR9kVaJN6ctKXYSYnWYMpBsWubN5.mid",
      "sha256": "f1f8bd04e55872b6f0d6570dfe82c3c583829bad10f557a8c0a66840245f5e8d",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 26,
        "tracks": 10,
        "families": [
          "brass",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 85,
        "tempoChanges": 0,
        "notesPerBar": 48.35,
        "swingRatio": 0.0244,
        "effectivePitchClasses": 6.27
      },
      "genre": {
        "primary": "wind_band_marching",
        "families": [
          "wind_band_marching"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-Qma2qXH7BTNA9mf19TPCYLmsP5sZBDxJ3SzdNi7oQVdqyT",
    "title": "let me down slowly",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "let me down slowly (PDMX Qma2qXH7BTNA9mf19TPCYLmsP5sZBDxJ3SzdNi7oQVdqyT, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "slow",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "Qma2qXH7BTNA9mf19TPCYLmsP5sZBDxJ3SzdNi7oQVdqyT",
      "relativePath": "mid/mid/0/1/Qma2qXH7BTNA9mf19TPCYLmsP5sZBDxJ3SzdNi7oQVdqyT.mid",
      "sha256": "f385f0472a7ae9f07ffb7e001e8eb130f8bfcabaffd2cd97acfe3ef59882f399",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 52,
        "tracks": 7,
        "families": [
          "bass",
          "drums",
          "guitar",
          "keys",
          "pipe"
        ],
        "meter": "4/4",
        "tempoBpm": 75,
        "tempoChanges": 1,
        "notesPerBar": 41.33,
        "swingRatio": 0.0077,
        "effectivePitchClasses": 6.91
      },
      "genre": {
        "primary": "pop",
        "families": [
          "pop",
          "rnb_funk_soul"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmbqqfxB2FW85LZJLL7HwSxbaSSMWC4oqioxXfKF7GFhzQ",
    "title": "overnight celebrtiy",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "overnight celebrtiy (PDMX QmbqqfxB2FW85LZJLL7HwSxbaSSMWC4oqioxXfKF7GFhzQ, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmbqqfxB2FW85LZJLL7HwSxbaSSMWC4oqioxXfKF7GFhzQ",
      "relativePath": "mid/mid/1/38/QmbqqfxB2FW85LZJLL7HwSxbaSSMWC4oqioxXfKF7GFhzQ.mid",
      "sha256": "875585dd88a2250017021905885435c1ed25935fce3117be82588077957c4825",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 43,
        "tracks": 5,
        "families": [
          "bass",
          "drums",
          "ensemble",
          "ethnic",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 180,
        "tempoChanges": 2,
        "notesPerBar": 27.21,
        "swingRatio": 0,
        "effectivePitchClasses": 8.98
      },
      "genre": {
        "primary": "hiphop",
        "families": [
          "hiphop"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmanYWjTEPXebCvngzAdXN3vojzCtRmLKyLGMov4U82HwX",
    "title": "Gangsta's Paradise",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Gangsta's Paradise (PDMX QmanYWjTEPXebCvngzAdXN3vojzCtRmLKyLGMov4U82HwX, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmanYWjTEPXebCvngzAdXN3vojzCtRmLKyLGMov4U82HwX",
      "relativePath": "mid/mid/0/33/QmanYWjTEPXebCvngzAdXN3vojzCtRmLKyLGMov4U82HwX.mid",
      "sha256": "ba53a87f34c874b88a2f9469705ef5aaab6796b161bb78e69b284ad7dffe1be1",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 36,
        "tracks": 11,
        "families": [
          "brass",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 80,
        "tempoChanges": 0,
        "notesPerBar": 41.83,
        "swingRatio": 0.0208,
        "effectivePitchClasses": 6.14
      },
      "genre": {
        "primary": "hiphop",
        "families": [
          "hiphop"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmeuGpDFNwqhaKhtUNuCQdcxiq2TwT1S1f3Rr2H685XJXj",
    "title": "i got you babe",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "i got you babe (PDMX QmeuGpDFNwqhaKhtUNuCQdcxiq2TwT1S1f3Rr2H685XJXj, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "12/8",
      "feel": "compound",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmeuGpDFNwqhaKhtUNuCQdcxiq2TwT1S1f3Rr2H685XJXj",
      "relativePath": "mid/mid/4/46/QmeuGpDFNwqhaKhtUNuCQdcxiq2TwT1S1f3Rr2H685XJXj.mid",
      "sha256": "8e250cb6d03fb8c2a9a0cdc8af9881ab1cf0112ea5c1ed50f8a2614b51b66847",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 39,
        "tracks": 7,
        "families": [
          "brass",
          "guitar",
          "keys",
          "organ",
          "pipe",
          "reed"
        ],
        "meter": "12/8",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 40.44,
        "swingRatio": null,
        "effectivePitchClasses": 8.66
      },
      "genre": {
        "primary": "reggae_ska",
        "families": [
          "reggae_ska"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-Qma4X9oCvTBVazSqVsqZ7j8YLH5ouhEnzkEQRPDgM14Gsa",
    "title": "cold duck time",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "cold duck time (PDMX Qma4X9oCvTBVazSqVsqZ7j8YLH5ouhEnzkEQRPDgM14Gsa, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "Qma4X9oCvTBVazSqVsqZ7j8YLH5ouhEnzkEQRPDgM14Gsa",
      "relativePath": "mid/mid/0/3/Qma4X9oCvTBVazSqVsqZ7j8YLH5ouhEnzkEQRPDgM14Gsa.mid",
      "sha256": "17e554b89f1928126f840cfdd3b8c9ababe0082156d93b5a7b6904e5aa1c5ba0",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 30,
        "tracks": 3,
        "families": [
          "bass",
          "brass",
          "keys"
        ],
        "meter": "4/4",
        "tempoBpm": 124,
        "tempoChanges": 3,
        "notesPerBar": 9.67,
        "swingRatio": 0,
        "effectivePitchClasses": 5.95
      },
      "genre": {
        "primary": "jazz",
        "families": [
          "jazz",
          "rnb_funk_soul"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmdRTNCGVUhi7wa7cGC1vynEHxbo5rupUehZ4GQuJqkH4N",
    "title": "Counterpoint/Pie Jesu",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Counterpoint/Pie Jesu (PDMX QmdRTNCGVUhi7wa7cGC1vynEHxbo5rupUehZ4GQuJqkH4N, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "moderate",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmdRTNCGVUhi7wa7cGC1vynEHxbo5rupUehZ4GQuJqkH4N",
      "relativePath": "mid/mid/3/41/QmdRTNCGVUhi7wa7cGC1vynEHxbo5rupUehZ4GQuJqkH4N.mid",
      "sha256": "08bf6942344e615fa9888eaf08412bab2348a8909d0cb9dabefef6b8743715fb",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 29,
        "tracks": 5,
        "families": [
          "brass",
          "ensemble",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 76,
        "tempoChanges": 0,
        "notesPerBar": 10.79,
        "swingRatio": 0.0455,
        "effectivePitchClasses": 7.4
      },
      "genre": {
        "primary": "musical_theatre",
        "families": [
          "musical_theatre"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-Qma1c7LuqVV8Jyw1GmBnwdqKZPeoNTahvqbNkYZqQhMwN2",
    "title": "sos",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "sos (PDMX Qma1c7LuqVV8Jyw1GmBnwdqKZPeoNTahvqbNkYZqQhMwN2, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "Qma1c7LuqVV8Jyw1GmBnwdqKZPeoNTahvqbNkYZqQhMwN2",
      "relativePath": "mid/mid/0/0/Qma1c7LuqVV8Jyw1GmBnwdqKZPeoNTahvqbNkYZqQhMwN2.mid",
      "sha256": "f88c422d4b8f88502b6fc5028e3c5d2a09127e030148032002c02be0f010c995",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 64,
        "tracks": 9,
        "families": [
          "bass",
          "keys",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 100,
        "tempoChanges": 1,
        "notesPerBar": 40.02,
        "swingRatio": 0,
        "effectivePitchClasses": 6.27
      },
      "genre": {
        "primary": "electronic",
        "families": [
          "electronic"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmarK8WuALDnUkYx44Nrk5Knx4bMsmh1m8Jduyz3R1V9PD",
    "title": "them changes",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "them changes (PDMX QmarK8WuALDnUkYx44Nrk5Knx4bMsmh1m8Jduyz3R1V9PD, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "2/2",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmarK8WuALDnUkYx44Nrk5Knx4bMsmh1m8Jduyz3R1V9PD",
      "relativePath": "mid/mid/0/40/QmarK8WuALDnUkYx44Nrk5Knx4bMsmh1m8Jduyz3R1V9PD.mid",
      "sha256": "b6fe5d320cc0ba22d974bb5dc9715d89ff7fc198a7a4c35a21c15ae4dfb1c9f4",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 124,
        "tracks": 8,
        "families": [
          "bass",
          "drums",
          "ensemble",
          "guitar",
          "keys"
        ],
        "meter": "2/2",
        "tempoBpm": 160,
        "tempoChanges": 0,
        "notesPerBar": 35.52,
        "swingRatio": 0.0011,
        "effectivePitchClasses": 8.31
      },
      "genre": {
        "primary": "rnb_funk_soul",
        "families": [
          "rnb_funk_soul"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS",
    "title": "Arthur S. Sullivan: Christ is Risen!",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Arthur S. Sullivan: Christ is Risen! (PDMX QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS",
      "relativePath": "mid/mid/0/52/QmaxCMVTUnP27mT65k76NYKsVy9Eev7nAYskQ17mcidUkS.mid",
      "sha256": "8e9eaaba8a4b456d05799c724b46380e76dbf141b8fdd957ce36fe81cd6d0f94",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 76,
        "tracks": 6,
        "families": [
          "brass",
          "ensemble",
          "keys",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 115,
        "tempoChanges": 6,
        "notesPerBar": 34.37,
        "swingRatio": 0,
        "effectivePitchClasses": 7.66
      },
      "genre": {
        "primary": "religious_worship",
        "families": [
          "religious_worship"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmVCMwJFL9Q67AL1TyeBGTLbu2a5uHnpiFivsBr339Tymr",
    "title": "build me up buttercup",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "build me up buttercup (PDMX QmVCMwJFL9Q67AL1TyeBGTLbu2a5uHnpiFivsBr339Tymr, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmVCMwJFL9Q67AL1TyeBGTLbu2a5uHnpiFivsBr339Tymr",
      "relativePath": "mid/mid/13/14/QmVCMwJFL9Q67AL1TyeBGTLbu2a5uHnpiFivsBr339Tymr.mid",
      "sha256": "5957d5fce535c48e756f94a6a3046bacf5ba84ee00dbe534ae972992128fc869",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 79,
        "tracks": 25,
        "families": [
          "brass",
          "drums",
          "pipe",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 128,
        "tempoChanges": 0,
        "notesPerBar": 73.56,
        "swingRatio": 0.0652,
        "effectivePitchClasses": 7.09
      },
      "genre": {
        "primary": "rnb_funk_soul",
        "families": [
          "rnb_funk_soul"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmdR8JT7qjszfGL9ivGsbCKx9UgnNvfiPAWkKwBhdPJs2L",
    "title": "Blues bossa sax+guitare+accompagnement",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "Blues bossa sax+guitare+accompagnement (PDMX QmdR8JT7qjszfGL9ivGsbCKx9UgnNvfiPAWkKwBhdPJs2L, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmdR8JT7qjszfGL9ivGsbCKx9UgnNvfiPAWkKwBhdPJs2L",
      "relativePath": "mid/mid/3/41/QmdR8JT7qjszfGL9ivGsbCKx9UgnNvfiPAWkKwBhdPJs2L.mid",
      "sha256": "206d1f1dd666ba1564a1584159ccb59269041ff7fb2780d78a7730001c211d04",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 36,
        "tracks": 8,
        "families": [
          "bass",
          "drums",
          "guitar",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 1,
        "notesPerBar": 27.64,
        "swingRatio": 0.1585,
        "effectivePitchClasses": 7.83
      },
      "genre": {
        "primary": "blues",
        "families": [
          "blues",
          "latin"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-Qma3KDfPJTb2ybD5UBqm5JAuSzYoBaGRqN8gogjMF53J9w",
    "title": "sandstorm",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "sandstorm (PDMX Qma3KDfPJTb2ybD5UBqm5JAuSzYoBaGRqN8gogjMF53J9w, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "Qma3KDfPJTb2ybD5UBqm5JAuSzYoBaGRqN8gogjMF53J9w",
      "relativePath": "mid/mid/0/2/Qma3KDfPJTb2ybD5UBqm5JAuSzYoBaGRqN8gogjMF53J9w.mid",
      "sha256": "0eb1a555fcc2b0f4232559b242740309f4dd1c6b74fcc8202b9811aa8b619fa8",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 65,
        "tracks": 20,
        "families": [
          "bass",
          "brass",
          "drums",
          "reed",
          "strings"
        ],
        "meter": "4/4",
        "tempoBpm": 125,
        "tempoChanges": 1,
        "notesPerBar": 54.45,
        "swingRatio": 0.0009,
        "effectivePitchClasses": 9.38
      },
      "genre": {
        "primary": "electronic",
        "families": [
          "electronic"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmSj6ei4HACHGvcbAXCaV8evjAHdgaqyrTdwJdKZCsCsz3",
    "title": "Take Me Home Country Roads",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Take Me Home Country Roads (PDMX QmSj6ei4HACHGvcbAXCaV8evjAHdgaqyrTdwJdKZCsCsz3, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "fast",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmSj6ei4HACHGvcbAXCaV8evjAHdgaqyrTdwJdKZCsCsz3",
      "relativePath": "mid/mid/10/26/QmSj6ei4HACHGvcbAXCaV8evjAHdgaqyrTdwJdKZCsCsz3.mid",
      "sha256": "70d48f4bee4404f72fb3a59d9f3a41558f5711022a070b19a2ca9d630de6f075",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 123,
        "tracks": 6,
        "families": [
          "bass",
          "brass",
          "drums",
          "guitar",
          "organ"
        ],
        "meter": "4/4",
        "tempoBpm": 166,
        "tempoChanges": 3,
        "notesPerBar": 19.19,
        "swingRatio": 0.0033,
        "effectivePitchClasses": 6.83
      },
      "genre": {
        "primary": "country",
        "families": [
          "country",
          "folk"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmZAqZ5sWmk1bVXiTQsW2kBQhKWJfbN7jDAT9C7abGqSxU",
    "title": "Musical Hair: Where do I go (arranged for small R&B band)",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Musical Hair: Where do I go (arranged for small R&B band) (PDMX QmZAqZ5sWmk1bVXiTQsW2kBQhKWJfbN7jDAT9C7abGqSxU, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmZAqZ5sWmk1bVXiTQsW2kBQhKWJfbN7jDAT9C7abGqSxU",
      "relativePath": "mid/mid/17/10/QmZAqZ5sWmk1bVXiTQsW2kBQhKWJfbN7jDAT9C7abGqSxU.mid",
      "sha256": "0a5e782759199dfabcbbe1f59d569e07aaee286424403b0e5de288a46d365c6b",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 65,
        "tracks": 9,
        "families": [
          "bass",
          "ensemble",
          "guitar",
          "keys",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 38.62,
        "swingRatio": 0.0228,
        "effectivePitchClasses": 8
      },
      "genre": {
        "primary": "musical_theatre",
        "families": [
          "musical_theatre"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmTqqMaBHWUp9D5UZyBQLQEKH7uivDdctjuz4RftniwCUi",
    "title": "sleeping sun",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "sleeping sun (PDMX QmTqqMaBHWUp9D5UZyBQLQEKH7uivDdctjuz4RftniwCUi, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "complex",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmTqqMaBHWUp9D5UZyBQLQEKH7uivDdctjuz4RftniwCUi",
      "relativePath": "mid/mid/11/38/QmTqqMaBHWUp9D5UZyBQLQEKH7uivDdctjuz4RftniwCUi.mid",
      "sha256": "2be0e5b9cdf327456ad3d0cf36ad0b572a13bdea79d006b445348929a68694c6",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 109,
        "tracks": 9,
        "families": [
          "bass",
          "chromatic_perc",
          "drums",
          "guitar",
          "pipe",
          "synth"
        ],
        "meter": "4/4",
        "tempoBpm": 110,
        "tempoChanges": 0,
        "notesPerBar": 18.88,
        "swingRatio": 0.0047,
        "effectivePitchClasses": 10.11
      },
      "genre": {
        "primary": "metal",
        "families": [
          "metal"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaGSbbadetKUxXVTcFYk9QaqRGQyi2KRtWmckqBD2Z1dK",
    "title": "i will survive",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "i will survive (PDMX QmaGSbbadetKUxXVTcFYk9QaqRGQyi2KRtWmckqBD2Z1dK, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaGSbbadetKUxXVTcFYk9QaqRGQyi2KRtWmckqBD2Z1dK",
      "relativePath": "mid/mid/0/22/QmaGSbbadetKUxXVTcFYk9QaqRGQyi2KRtWmckqBD2Z1dK.mid",
      "sha256": "d860a157c1638f5589749172b0703635deed8cd5193c9c471e891fcf2dee8072",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 92,
        "tracks": 11,
        "families": [
          "bass",
          "brass",
          "drums",
          "ensemble",
          "guitar",
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 116,
        "tempoChanges": 1,
        "notesPerBar": 54.32,
        "swingRatio": 0,
        "effectivePitchClasses": 8.96
      },
      "genre": {
        "primary": "electronic",
        "families": [
          "electronic"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaAJQvJnwF4yghG8p3s5gzvrKYkJG23atgk8Hdg8dkopa",
    "title": "This Girl - The Kungs for Pep band",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "This Girl - The Kungs for Pep band (PDMX QmaAJQvJnwF4yghG8p3s5gzvrKYkJG23atgk8Hdg8dkopa, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaAJQvJnwF4yghG8p3s5gzvrKYkJG23atgk8Hdg8dkopa",
      "relativePath": "mid/mid/0/10/QmaAJQvJnwF4yghG8p3s5gzvrKYkJG23atgk8Hdg8dkopa.mid",
      "sha256": "7ec5a7f6e42c4da66c102a3aea310190feeadd3cee85ef06fb1c01bcc29ffc5e",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 38,
        "tracks": 13,
        "families": [
          "brass",
          "drums",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 130,
        "tempoChanges": 0,
        "notesPerBar": 69.79,
        "swingRatio": 0.0072,
        "effectivePitchClasses": 6.97
      },
      "genre": {
        "primary": "wind_band_marching",
        "families": [
          "wind_band_marching"
        ],
        "source": "tags"
      }
    }
  },
  {
    "id": "pdmx-QmShENbwkZFu1WzVmUfschPHEAVVmm83mxcaBNr3GqBbam",
    "title": "amaranth",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/mark/1.0/",
      "work": "amaranth (PDMX QmShENbwkZFu1WzVmUfschPHEAVVmm83mxcaBNr3GqBbam, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmShENbwkZFu1WzVmUfschPHEAVVmm83mxcaBNr3GqBbam",
      "relativePath": "mid/mid/10/23/QmShENbwkZFu1WzVmUfschPHEAVVmm83mxcaBNr3GqBbam.mid",
      "sha256": "53e81f9ae14d3cbd0b05bb643c40cd5c8abd7beca8e84a15e90ccc545fd7624e",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 124,
        "tracks": 9,
        "families": [
          "bass",
          "ensemble",
          "guitar",
          "keys",
          "strings",
          "synth"
        ],
        "meter": "4/4",
        "tempoBpm": 128,
        "tempoChanges": 0,
        "notesPerBar": 35.63,
        "swingRatio": 0,
        "effectivePitchClasses": 7.59
      },
      "genre": {
        "primary": "metal",
        "families": [
          "metal"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmUJGQdm7iiPTE6xX4DrR3Z13YSRKK5ULX6i3vr8iZxwCr",
    "title": "earthbound - onett",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "earthbound - onett (PDMX QmUJGQdm7iiPTE6xX4DrR3Z13YSRKK5ULX6i3vr8iZxwCr, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmUJGQdm7iiPTE6xX4DrR3Z13YSRKK5ULX6i3vr8iZxwCr",
      "relativePath": "mid/mid/12/27/QmUJGQdm7iiPTE6xX4DrR3Z13YSRKK5ULX6i3vr8iZxwCr.mid",
      "sha256": "cc4e6060fdea9db3afc1b5ae68907e032e60296b66b63ed2f8df103ecd67a7bf",
      "admittedBy": "tournament-classical",
      "measured": {
        "bars": 63,
        "tracks": 5,
        "families": [
          "bass",
          "brass",
          "drums",
          "ensemble"
        ],
        "meter": "4/4",
        "tempoBpm": 110,
        "tempoChanges": 0,
        "notesPerBar": 30.05,
        "swingRatio": 0.025,
        "effectivePitchClasses": 7.67
      },
      "genre": {
        "primary": "film_game",
        "families": [
          "film_game"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaCHVw1Uoj5ot5ciMpYCj2ffGga8PsJAzq94mfx7PUXW3",
    "title": "Señorita",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "Señorita (PDMX QmaCHVw1Uoj5ot5ciMpYCj2ffGga8PsJAzq94mfx7PUXW3, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "moderate",
      "density": "dense",
      "ensemble": "large",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaCHVw1Uoj5ot5ciMpYCj2ffGga8PsJAzq94mfx7PUXW3",
      "relativePath": "mid/mid/0/14/QmaCHVw1Uoj5ot5ciMpYCj2ffGga8PsJAzq94mfx7PUXW3.mid",
      "sha256": "9d6356a608ff724e577dc526a44b0ebfd29aaa494b4e54cbc6919d8f70b4a53b",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 84,
        "tracks": 18,
        "families": [
          "brass",
          "drums",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 59.35,
        "swingRatio": 0.0044,
        "effectivePitchClasses": 8.12
      },
      "genre": {
        "primary": "pop",
        "families": [
          "pop",
          "rnb_funk_soul"
        ],
        "source": "genres"
      }
    }
  },
  {
    "id": "pdmx-QmaLyZRXXjfypokZs1VXcjrCyU7huPwxKj1DetTLLn2dzY",
    "title": "postcards from italy",
    "inputType": "midi",
    "rights": {
      "kind": "public_domain",
      "reference": "https://creativecommons.org/publicdomain/zero/1.0/",
      "work": "postcards from italy (PDMX QmaLyZRXXjfypokZs1VXcjrCyU7huPwxKj1DetTLLn2dzY, no_license_conflict)",
      "clearedAt": "2026-09-10T03:17:23.562Z",
      "commercialUse": true
    },
    "attributes": {
      "tempoBand": "medium",
      "meter": "4/4",
      "feel": "straight",
      "harmony": "simple",
      "density": "dense",
      "ensemble": "small",
      "idiom": "western",
      "production": "acoustic"
    },
    "symbolicSource": {
      "kind": "pdmx_midi",
      "workId": "QmaLyZRXXjfypokZs1VXcjrCyU7huPwxKj1DetTLLn2dzY",
      "relativePath": "mid/mid/0/30/QmaLyZRXXjfypokZs1VXcjrCyU7huPwxKj1DetTLLn2dzY.mid",
      "sha256": "25c8029f3ea7bfddd46d48e19651b49e85a96f3c2bd67a94c425857ae1765499",
      "admittedBy": "tournament-global",
      "measured": {
        "bars": 100,
        "tracks": 5,
        "families": [
          "drums",
          "guitar",
          "keys",
          "pipe",
          "reed"
        ],
        "meter": "4/4",
        "tempoBpm": 120,
        "tempoChanges": 0,
        "notesPerBar": 38.78,
        "swingRatio": 0.0113,
        "effectivePitchClasses": 6.75
      },
      "genre": {
        "primary": "folk",
        "families": [
          "folk"
        ],
        "source": "genres"
      }
    }
  }
];
