import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const bossaLatin: StyleKnowledgeEntry = {
  id: "bossa_latin",
  label: { en: "bossa nova / Latin", he: "בוסה נובה / לטיני" },
  match: {
    requires: [[t("genre", "bossa"), t("genre", "bossa_nova"), t("genre", "samba"), t("genre", "latin"), t("tradition", "brazilian"), t("tradition", "latin"), t("tradition", "cuban")]],
    boosts: [{ slot: "word", term: "instrument=guitar" }, { slot: "word", term: "mood=romantic" }],
  },
  levels: {
    genre: { "identity.genre": kv("latin", 0.8, "the Latin family") },
    subgenre: { "identity.subgenre": kv("bossa_nova", 0.7, "the bossa nova; samba and son differ in rhythm") },
    tradition: {
      "identity.tradition": kv("brazilian", 0.8, "Brazilian"),
      "identity.region": kv("brazil", 0.8, "Rio"),
    },
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("small_acoustic_combo", 0.7, "nylon guitar, bass, light percussion, a flute or piano"),
      "arrangement.familyPriority": kv(["guitar", "bass", "percussion", "keys", "winds", "strings"], 0.6, "the guitar first"),
      "sound.referenceInstruments": kv(["nylon-string guitar", "upright bass", "brushed kit or rim clicks", "flute", "piano"], 0.7, "the instruments of the style"),
    },
    rhythmic: {
      "groove.family": kv("bossa", 0.9, "the bossa pattern"),
      "groove.subdivision": kv("16th", 0.6, "sixteenth-note guitar pattern"),
      "groove.syncopation": kv(0.55, 0.7, "the clave places most onsets off the beat"),
      "groove.fillFrequency": kv("rare", 0.7, "the pattern never breaks"),
      "groove.kickSnareLanguage": kv("bossa_clave_rim_click", 0.8, "rim click on the clave, bass drum on one and three"),
      "groove.tempoBehavior": kv("strict_grid", 0.5, "steady"),
      "bass.attackPosition": kv("on_the_beat", 0.7, "root on one, fifth on three, an anticipation into the change"),
      "bass.motion": kv("root_fifth", 0.85, "root and fifth"),
      "bass.lockToKick": kv(true, 0.7, "with the bass drum"),
      "keys.chordRhythm": kv("syncopated", 0.8, "syncopated comping"),
    },
    harmonic: {
      "harmony.extensions": kv("extended", 0.85, "sevenths, ninths, altered dominants"),
      "harmony.modalFlavour": kv("major_with_chromatic_ii_V_chains", 0.6, "major keys with chromatic ii-V chains"),
      "harmony.harmonicRhythm": kv("moderate", 0.6, "a chord a bar, two in the turnarounds"),
      "harmony.parallelism": kv("tolerated", 0.5, "guitar voicings slide in parallel"),
      "harmony.passingChords": kv("frequent", 0.7, "chromatic passing chords"),
      "keys.voicingWidth": kv("close", 0.7, "closed guitar voicings with the seventh and ninth"),
      "melodic.phraseLength": kv("regular", 0.6, "even phrases"),
      "melodic.callAndResponse": kv("none", 0.5, "none"),
      "melodic.hookExpectation": kv(false, 0.5, "a tune, not a hook"),
    },
    orchestration: {
      "strings.role": kv("pad", 0.4, "strings pad in the orchestrated records"),
      "strings.articulation": kv("legato", 0.6, "legato"),
      "brassWinds.role": kv("solo", 0.4, "a flute or sax line"),
      "keys.role": kv("comping", 0.6, "comping"),
      "arrangement.doubling": kv("none", 0.6, "nothing doubled"),
      "arrangement.textureLadder": kv({ intro: "duo", verse: "bed", chorus: "bed", instrumental: "bed", outro: "duo" }, 0.5, "it stays intimate"),
      "arrangement.silenceConventions": kv(["no drum fills; the pattern never breaks"], 0.7, "how bossa uses silence"),
      "arrangement.transitionLanguage": kv("thin_build", 0.5, "no fills; a small build"),
      "arrangement.development": kv("repetition", 0.6, "repetition"),
      "arrangement.phraseBehavior": kv("continuous", 0.6, "continuous"),
      "arrangement.arcTemplate": kv("band_steady", 0.5, "steady"),
    },
    aesthetic: {
      "sound.aesthetic": kv("intimate", 0.6, "close and quiet"),
      "sound.instrumentation": kv("acoustic", 0.85, "acoustic"),
      "sound.roomSize": kv("small", 0.6, "a small room"),
      "sound.saturation": kv("warm", 0.6, "warm"),
      "sound.stereo": kv("natural", 0.7, "natural"),
    },
    performance: {
      "performance.articulationLanguage": kv("legato", 0.5, "connected, soft"),
      "performance.dynamics": kv("narrow", 0.75, "quiet throughout"),
      "performance.humanise": kv("natural", 0.6, "played"),
      "melodic.ornamentation": kv("light", 0.6, "light"),
      "groove.microtiming": kv("on_top", 0.5, "on the beat"),
    },
  },
  basis: "common practice of bossa nova; B-09 specialist, not measured",
  coverage: "general_practice",
};
