import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const edmDance: StyleKnowledgeEntry = {
  id: "edm_dance",
  label: { en: "EDM / dance", he: "אלקטרוני / דאנס" },
  match: {
    requires: [[t("genre", "dance"), t("genre", "edm"), t("genre", "house"), t("genre", "techno"), t("genre", "trance"), t("genre", "electronic"), t("aesthetic", "electronic"), t("word", "production_feel=electronic")]],
    boosts: [{ slot: "scene", term: "dance" }, { slot: "scene", term: "club" }, { slot: "word", term: "instrument=synth" }],
  },
  levels: {
    genre: { "identity.genre": kv("dance", 0.9, "music to dance to, produced electronically") },
    subgenre: "unknown",
    tradition: "unknown",
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("electronic_production", 0.9, "programmed drums, synth bass, synth layers"),
      "arrangement.familyPriority": kv(["drums", "bass", "synth", "pads", "fx", "keys"], 0.7, "drums and bass first"),
      "sound.referenceInstruments": kv(["kick sample", "sub bass", "supersaw lead", "pad synth", "riser fx"], 0.7, "the sounds of the style"),
    },
    rhythmic: {
      "groove.family": kv("four_on_floor", 0.85, "kick on every beat"),
      "groove.subdivision": kv("16th", 0.6, "sixteenth hats and offbeat bass"),
      "groove.syncopation": kv(0.3, 0.4, "offbeat hats and bass"),
      "groove.fillFrequency": kv("moderate", 0.5, "fills and risers before drops"),
      "groove.kickSnareLanguage": kv("four_on_floor_clap_2_4", 0.85, "kick on every beat, clap on two and four"),
      "groove.tempoBehavior": kv("strict_grid", 0.95, "a grid"),
      "bass.attackPosition": kv("on_the_beat", 0.6, "on the grid, side-chained to the kick"),
      "bass.motion": kv("riff", 0.6, "a repeating bass figure"),
      "bass.lockToKick": kv(true, 0.8, "locked and side-chained"),
      "keys.chordRhythm": kv("stabs", 0.6, "chord stabs"),
    },
    harmonic: {
      "harmony.extensions": kv("sevenths", 0.5, "minor sevenths and ninths in the pads"),
      "harmony.modalFlavour": kv("natural_minor", 0.6, "natural minor loops"),
      "harmony.harmonicRhythm": kv("slow", 0.6, "four- and eight-bar loops"),
      "harmony.parallelism": kv("characteristic", 0.7, "stacked fifths and octaves"),
      "harmony.passingChords": kv("none", 0.6, "none"),
      "keys.voicingWidth": kv("wide", 0.55, "wide supersaw voicings"),
      "melodic.phraseLength": kv("regular", 0.8, "eight- and sixteen-bar phrases"),
      "melodic.callAndResponse": kv("none", 0.5, "none"),
      "melodic.hookExpectation": kv(true, 0.8, "the drop is the hook"),
    },
    orchestration: {
      "strings.role": kv("none", 0.5, "no strings by default"),
      "brassWinds.role": kv("none", 0.7, "no brass"),
      "keys.role": kv("arpeggio", 0.5, "arpeggiated synths"),
      "arrangement.doubling": kv("octaves", 0.6, "octave-layered leads"),
      "arrangement.textureLadder": kv({ intro: "duo", verse: "bed", prechorus: "bed", chorus: "tutti", breakdown: "duo", outro: "duo" }, 0.6, "build, drop, breakdown"),
      "arrangement.silenceConventions": kv(["a beat of silence before the drop", "the kick leaves in the breakdown"], 0.7, "how the style uses silence"),
      "arrangement.transitionLanguage": kv("riser", 0.85, "risers and snare rolls"),
      "arrangement.development": kv("additive", 0.7, "layers are added every eight bars"),
      "arrangement.phraseBehavior": kv("motivic", 0.5, "a motif repeated and filtered"),
      "arrangement.arcTemplate": kv("electronic_drop", 0.9, "the drop arc"),
    },
    aesthetic: {
      "sound.aesthetic": kv("electronic", 0.9, "electronic"),
      "sound.instrumentation": kv("electronic", 0.95, "synthesised"),
      "sound.roomSize": kv("large", 0.5, "big reverbs on the pads, dry drums"),
      "sound.saturation": kv("clean", 0.5, "clean and loud"),
      "sound.stereo": kv("wide", 0.8, "wide"),
    },
    performance: {
      "performance.articulationLanguage": kv("pulsed", 0.7, "pulsed"),
      "performance.dynamics": kv("wide", 0.6, "the dynamic is the arrangement: breakdown to drop"),
      "performance.humanise": kv("quantized", 0.9, "quantised"),
      "melodic.ornamentation": kv("none", 0.7, "none"),
      "groove.microtiming": kv("quantized", 0.9, "on the grid"),
    },
  },
  basis: "common practice of mainstream EDM; B-09 specialist, not measured",
  coverage: "general_practice",
};
