import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const gospel: StyleKnowledgeEntry = {
  id: "gospel",
  label: { en: "gospel", he: "גוספל" },
  match: { requires: [[t("genre", "gospel"), t("tradition", "gospel")]], boosts: [{ slot: "word", term: "vocal_treatment=choir" }, { slot: "word", term: "instrument=organ" }] },
  levels: {
    genre: { "identity.genre": kv("gospel", 0.9, "the brief names it") },
    subgenre: "unknown",
    tradition: { "identity.tradition": kv("gospel", 0.9, "the African-American church tradition") },
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("rhythm_section_with_organ_and_choir", 0.7, "organ, piano, bass, kit, choir"),
      "arrangement.familyPriority": kv(["keys", "bass", "drums", "guitar", "brass"], 0.6, "keys lead the band"),
      "sound.referenceInstruments": kv(["hammond organ", "grand piano", "electric bass", "drum kit", "choir"], 0.7, "the instruments of the style"),
    },
    rhythmic: {
      "groove.family": [
        kv("shuffle", 0.5, "the 12/8 shuffle of the traditional ballad"),
        kv("backbeat", 0.45, "the straight backbeat of contemporary gospel"),
      ],
      "groove.subdivision": kv("12_8", 0.5, "the triplet grid of the ballad"),
      "groove.swingRatio": kv(0.6, 0.4, "a lilt in the eighths of the shuffle"),
      "groove.syncopation": kv(0.4, 0.5, "pushes into the changes"),
      "groove.fillFrequency": kv("frequent", 0.7, "fills and runs everywhere"),
      "groove.kickSnareLanguage": kv("backbeat_with_pushes", 0.6, "two and four with anticipations"),
      "groove.tempoBehavior": kv("breathing", 0.6, "the tempo breathes with the choir"),
      "bass.attackPosition": kv("laid_back", 0.5, "a hair late"),
      "bass.motion": kv("walking", 0.5, "walking and octave runs into the changes"),
      "bass.lockToKick": kv(true, 0.6, "with the kick on the downbeats"),
      "keys.chordRhythm": kv("pulsing", 0.6, "pulsing, driving keys"),
    },
    harmonic: {
      "harmony.extensions": kv("extended", 0.85, "ninths, elevenths and thirteenths as the default colour"),
      "harmony.modalFlavour": kv("major_with_secondary_dominants_and_borrowed_iv", 0.7, "major with secondary dominants and the borrowed iv"),
      "harmony.harmonicRhythm": kv("fast", 0.6, "chords on every beat in the run-ups"),
      "harmony.parallelism": kv("characteristic", 0.8, "parallel triads and planed voicings are the sound"),
      "harmony.cadenceLanguage": kv("plagal cadences and chromatic approach chords; the vamp modulates up", 0.7, "the cadences of the style"),
      "harmony.passingChords": kv("frequent", 0.85, "passing chords between every change"),
      "keys.voicingWidth": kv("wide", 0.6, "wide two-handed voicings"),
      "melodic.phraseLength": kv("regular", 0.6, "even phrases with a vamp"),
      "melodic.callAndResponse": kv("structural", 0.9, "leader and choir"),
      "melodic.hookExpectation": kv(true, 0.7, "the vamp is the hook"),
    },
    orchestration: {
      "arrangement.introFigure": kv("piano_motif", 0.55, "the organ or piano plays the turnaround before the first line"),
      "arrangement.endingGesture": kv("held_final_chord", 0.6, "the last chord is held under the choir"),
      "strings.role": kv("none", 0.5, "no strings by default"),
      "brassWinds.role": kv("section", 0.5, "a horn section in the bigger productions"),
      "keys.role": kv("comping", 0.8, "the keys drive"),
      "arrangement.doubling": kv("unison_sections", 0.6, "the choir in parts, horns in unison"),
      "arrangement.textureLadder": kv({ intro: "bed", verse: "bed", chorus: "full", bridge: "full", outro: "tutti" }, 0.5, "it builds to the vamp"),
      "arrangement.silenceConventions": kv(["the band drops out for the a cappella choir moment", "a stop before the vamp"], 0.6, "how gospel uses silence"),
      "arrangement.transitionLanguage": kv("drum_fills", 0.7, "fills and runs"),
      "arrangement.development": kv("additive", 0.6, "the vamp adds and modulates"),
      "arrangement.phraseBehavior": kv("call_response", 0.9, "call and response"),
      "arrangement.arcTemplate": kv("pop_build", 0.55, "a build to the end"),
    },
    aesthetic: {
      "sound.aesthetic": [
        kv("raw_band", 0.5, "a live church recording"),
        kv("polished_pop", 0.4, "the contemporary produced record"),
      ],
      "sound.instrumentation": kv("acoustic", 0.6, "played instruments"),
      "sound.roomSize": kv("large", 0.55, "a church"),
      "sound.saturation": kv("warm", 0.6, "warm"),
      "sound.stereo": kv("natural", 0.55, "natural"),
    },
    performance: {
      "performance.articulationLanguage": kv("accented", 0.6, "accented"),
      "performance.dynamics": kv("wide", 0.8, "from a whisper to a shout"),
      "performance.humanise": kv("loose", 0.6, "loose, human"),
      "melodic.ornamentation": kv("heavy", 0.8, "runs and melisma"),
      "groove.microtiming": kv("behind", 0.5, "behind the beat"),
      "keys.pedal": kv("per_chord", 0.5, "with the chord"),
    },
  },
  pulse: {
    writtenBpm: { min: 50, max: 140 },
    above: "half_time",
    below: "as_written",
    strategy: "steady_pulse",
    halfTimeStrategy: "half_time_feel",
    never: ["four_on_floor", "rubato"],
    confidence: 0.6,
    why: "the 12/8 ballad is felt in four slow beats and the contemporary backbeat in four fast ones; both are the written tempo inside this band. The choir's tempo breathes, but the arrangement is not rubato.",
  },
  basis: "common practice of gospel; B-09 specialist, not measured",
  coverage: "general_practice",
};
