import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const jazzStandard: StyleKnowledgeEntry = {
  id: "jazz_standard",
  label: { en: "a jazz standard (small combo, swing)", he: "סטנדרט ג'אז (הרכב קטן, סווינג)" },
  match: {
    requires: [[t("genre", "jazz"), t("genre", "swing"), t("genre", "bebop")]],
    boosts: [{ slot: "ensemble", term: "big_band" }, { slot: "word", term: "instrument=sax" }],
  },
  levels: {
    genre: { "identity.genre": kv("jazz", 0.9, "the brief names it") },
    subgenre: { "identity.subgenre": kv("standard_swing", 0.6, "the swinging standard; modal, fusion and Latin jazz differ") },
    tradition: "unknown",
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("small_combo", 0.7, "piano trio plus a horn"),
      "arrangement.familyPriority": kv(["drums", "bass", "keys", "brass", "winds", "guitar"], 0.6, "rhythm section first, a horn on top"),
      "sound.referenceInstruments": kv(["grand piano", "upright bass", "ride-led kit", "tenor sax", "trumpet"], 0.7, "the instruments of the style"),
    },
    rhythmic: {
      "groove.family": kv("swung", 0.85, "swing"),
      "groove.swingRatio": kv(0.62, 0.6, "a medium swing; faster tempos straighten it"),
      "groove.subdivision": kv("triplet", 0.6, "the triplet grid"),
      "groove.syncopation": kv(0.45, 0.5, "comping and melody fall off the beat"),
      "groove.fillFrequency": kv("moderate", 0.5, "fills at phrase ends"),
      "groove.kickSnareLanguage": kv("ride_pattern_feathered_kick", 0.7, "ride cymbal pattern, feathered bass drum, hi-hat on two and four"),
      "groove.tempoBehavior": kv("moderate", 0.4, "any tempo; the feel changes with it"),
      "bass.attackPosition": kv("on_the_beat", 0.5, "walking on the beat"),
      "bass.motion": kv("walking", 0.85, "a walking line"),
      "bass.lockToKick": kv(false, 0.6, "the bass walks; the kick feathers"),
      "keys.chordRhythm": kv("syncopated", 0.7, "syncopated comping"),
    },
    harmonic: {
      "harmony.extensions": kv("extended", 0.85, "sevenths, ninths, thirteenths, alterations"),
      "harmony.modalFlavour": kv("functional_ii_V_I", 0.7, "functional harmony with ii-V-I chains"),
      "harmony.harmonicRhythm": kv("fast", 0.6, "two chords a bar is common"),
      "harmony.parallelism": kv("tolerated", 0.5, "planed voicings move in parallel"),
      "harmony.cadenceLanguage": kv("ii-V-I with tritone substitutions and turnarounds", 0.7, "the cadences of the standard"),
      "harmony.passingChords": kv("frequent", 0.7, "passing and substitute chords everywhere"),
      "keys.voicingWidth": kv("open", 0.65, "rootless and drop-2 voicings"),
      "melodic.phraseLength": kv("irregular", 0.5, "phrases across the bar line"),
      "melodic.callAndResponse": kv("occasional", 0.6, "trading and answering"),
      "melodic.hookExpectation": kv(false, 0.6, "a head, not a hook"),
    },
    orchestration: {
      "strings.role": kv("none", 0.6, "no strings in the combo"),
      "brassWinds.role": kv("solo", 0.6, "a horn plays the head and solos"),
      "brassWinds.articulation": kv("marcato", 0.4, "articulated swing eighths"),
      "keys.role": kv("comping", 0.85, "the piano comps"),
      "arrangement.doubling": kv("none", 0.6, "nothing doubled"),
      "arrangement.textureLadder": kv({ intro: "duo", verse: "bed", chorus: "bed", instrumental: "full", outro: "duo" }, 0.4, "the head, then solos"),
      "arrangement.silenceConventions": kv(["the head is stated once, quietly", "trading fours"], 0.4, "how the combo uses silence"),
      "arrangement.transitionLanguage": kv("drum_fills", 0.5, "a fill into the next chorus"),
      "arrangement.development": kv("transformative", 0.8, "every chorus transforms the material"),
      "arrangement.phraseBehavior": kv("call_response", 0.7, "answering phrases"),
      "arrangement.arcTemplate": kv("band_steady", 0.4, "steady; the arc is in the solos"),
    },
    aesthetic: {
      "sound.aesthetic": kv("raw_band", 0.45, "a band in a room; none of the produced dresses fit"),
      "sound.instrumentation": kv("acoustic", 0.85, "acoustic"),
      "sound.roomSize": kv("medium", 0.5, "a studio room"),
      "sound.saturation": kv("warm", 0.6, "warm"),
      "sound.stereo": kv("natural", 0.7, "natural"),
    },
    performance: {
      "performance.articulationLanguage": kv("accented", 0.6, "accented swing eighths"),
      "performance.dynamics": kv("moderate", 0.55, "played dynamics"),
      "performance.articulationVocabulary": kv(["accent", "ghost", "staccato", "legato", "fall"], 0.6, "the vocabulary"),
      "performance.humanise": kv("loose", 0.7, "loose, human"),
      "melodic.ornamentation": kv("moderate", 0.6, "turns, enclosures, ghost notes"),
      "groove.microtiming": kv("behind", 0.55, "the section sits back"),
    },
  },
  basis: "common practice of the small-combo jazz standard; B-09 specialist, not measured",
  coverage: "general_practice",
};
