import { kv, t, type StyleKnowledgeEntry } from "./schema";

/** Israeli Mizrahi pop: a pop backbeat under a maqsum-family rhythm, unison string lines answering the voice, heavy vocal ornamentation. */
export const mizrahiPop: StyleKnowledgeEntry = {
  id: "mizrahi_pop",
  label: { en: "Israeli Mizrahi pop", he: "פופ מזרחי ישראלי" },
  match: {
    requires: [[t("tradition", "mizrahi"), t("tradition", "yemenite"), t("tradition", "moroccan"), t("tradition", "andalusian")]],
    boosts: [{ slot: "genre", term: "pop" }, { slot: "tradition", term: "israeli" }, { slot: "tradition", term: "arabic" }, { slot: "tradition", term: "greek" }, { slot: "tradition", term: "turkish" }],
  },
  levels: {
    genre: { "identity.genre": kv("pop", 0.8, "a produced pop song in form and length") },
    subgenre: { "identity.subgenre": kv("mizrahi_pop", 0.85, "the Israeli Mizrahi pop mainstream") },
    tradition: {
      "identity.tradition": kv("mizrahi", 0.9, "the tradition the brief names"),
      "identity.region": kv("israel", 0.8, "an Israeli style with Arabic, Greek and Turkish roots"),
      "melodic.pitchSystem": kv("maqam_coloured_equal_12", 0.6, "instruments play twelve-tone; the maqam colour lives in the scale choice and in sung ornaments, which may bend quarter-tones"),
    },
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("produced_band_with_oriental_strings", 0.6, "a pop rhythm section plus strings, oud or bouzouki, and darbuka"),
      "arrangement.familyPriority": kv(["drums", "bass", "keys", "strings", "guitar", "percussion"], 0.55, "the produced core first; the oriental colour on top"),
      "sound.referenceInstruments": kv(["oud", "bouzouki or baglama", "kanun", "violin section", "darbuka", "electric bass", "synth strings"], 0.6, "the instruments the style is recognised by"),
    },
    rhythmic: {
      "groove.family": kv("maqsum", 0.6, "the maqsum / malfuf family under a pop backbeat"),
      "groove.subdivision": kv("16th", 0.55, "sixteenth-note darbuka motion"),
      "groove.syncopation": kv(0.45, 0.5, "the dum-tak placements fall off the beat often"),
      "groove.fillFrequency": kv("moderate", 0.6, "darbuka fills at phrase ends"),
      "groove.kickSnareLanguage": kv("maqsum_kick_with_backbeat", 0.55, "kick follows the dum, snare keeps two and four"),
      "groove.tempoBehavior": kv("moderate", 0.5, "medium tempos; the dance tunes are faster"),
      "bass.attackPosition": kv("on_the_beat", 0.6, "on the kick"),
      "bass.motion": kv("riff", 0.55, "a repeating bass figure with the rhythm"),
      "bass.lockToKick": kv(true, 0.65, "the bass follows the dum"),
      "keys.chordRhythm": kv("pulsing", 0.5, "keys pulse with the rhythm; strings carry the sustain"),
    },
    harmonic: {
      "harmony.extensions": kv("triads", 0.6, "triads and open fifths; the colour is modal, not extended"),
      "harmony.modalFlavour": kv("hijaz_or_natural_minor", 0.65, "maqam Hijaz (the freygish colour) or Nahawand (natural minor)"),
      "harmony.harmonicRhythm": kv("moderate", 0.6, "a chord a bar, often fewer"),
      "harmony.parallelism": kv("characteristic", 0.7, "melodic doubling in unison and octaves; parallel motion is the sound"),
      "harmony.cadenceLanguage": kv("Phrygian half cadence and V-i; a held dominant before the refrain", 0.55, "the cadences of the style"),
      "harmony.passingChords": kv("sparse", 0.5, "few passing chords; the line carries the interest"),
      "keys.voicingWidth": kv("close", 0.5, "close keyboard voicings, the strings open the picture"),
      "melodic.phraseLength": kv("regular", 0.6, "even phrases with an instrumental answer"),
      "melodic.callAndResponse": kv("structural", 0.6, "an instrumental line answers every vocal phrase"),
      "melodic.hookExpectation": kv(true, 0.7, "a sung refrain and an instrumental hook"),
    },
    orchestration: {
      "arrangement.introFigure": kv("tonic_pad", 0.55, "a synth or oud pad on the tonic before the darbuka enters"),
      "arrangement.endingGesture": kv("stop", 0.6, "the loop ends on a hit"),
      "strings.role": kv("lines", 0.7, "unison string lines answer the voice and carry the hook"),
      "strings.articulation": kv("legato", 0.6, "bowed lines with slides"),
      "strings.register": kv("upper_mid", 0.55, "above the voice"),
      "strings.entry": kv("throughout", 0.6, "strings are in from the intro"),
      "brassWinds.role": kv("none", 0.5, "brass is not part of the mainstream sound"),
      "keys.role": kv("comping", 0.55, "keys comp; the strings lead"),
      "arrangement.doubling": kv("unison_sections", 0.75, "strings and a plucked instrument in unison"),
      "arrangement.textureLadder": kv({ intro: "bed", verse: "full", chorus: "full", bridge: "bed", outro: "bed" }, 0.5, "full most of the way; the bridge thins"),
      "arrangement.silenceConventions": kv(["the instrumental answer owns the gap between vocal phrases", "percussion never stops once it enters"], 0.55, "how the style uses silence"),
      "arrangement.transitionLanguage": kv("drum_fills", 0.55, "a darbuka or kit fill leads into each section"),
      "arrangement.development": kv("repetition", 0.55, "the hook returns unchanged; the last refrain modulates up"),
      "arrangement.phraseBehavior": kv("call_response", 0.7, "voice and instrument alternate"),
      "arrangement.arcTemplate": kv("pop_build", 0.6, "a pop arc"),
      "arrangement.registerTendency": kv("mid", 0.5, "mid register with the strings above"),
    },
    aesthetic: {
      "sound.aesthetic": kv("polished_pop", 0.6, "a polished radio production"),
      "sound.instrumentation": kv("hybrid", 0.7, "acoustic oriental instruments over a produced rhythm section"),
      "sound.roomSize": kv("medium", 0.5, "a produced room"),
      "sound.saturation": kv("clean", 0.5, "clean, bright"),
      "sound.stereo": kv("wide", 0.55, "wide strings, centred voice and bass"),
    },
    performance: {
      "performance.articulationLanguage": kv("accented", 0.55, "accented attacks, slides between notes"),
      "performance.dynamics": kv("moderate", 0.55, "a produced dynamic range"),
      "performance.articulationVocabulary": kv(["slide", "trill", "mordent", "legato", "accent"], 0.5, "the ornaments the lines carry"),
      "performance.humanise": kv("natural", 0.5, "played lines over a programmed rhythm"),
      "melodic.ornamentation": kv("heavy", 0.75, "the sung line is heavily ornamented; instruments imitate it"),
      "groove.microtiming": kv("on_top", 0.5, "on the beat"),
    },
  },
  pulse: {
    writtenBpm: { min: 85, max: 145 },
    above: "half_time",
    below: "as_written",
    strategy: "syncopated",
    halfTimeStrategy: "half_time_feel",
    never: ["four_on_floor", "rubato"],
    confidence: 0.6,
    why: "the maqsum's dum-tak cycle is the pulse; a mizrahi pop tune counted above about 145 is being counted in eighths. The darbuka pattern is syncopated, never a four-on-the-floor grid.",
  },
  basis: "common practice of Israeli Mizrahi pop as the B-09 specialist knows it; the owner's world by proximity; not measured (no rights-clear corpus, PR-76)",
  coverage: "general_practice",
};
