import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const orchestralCinematic: StyleKnowledgeEntry = {
  id: "orchestral_cinematic",
  label: { en: "orchestral / cinematic", he: "תזמורתי / קולנועי" },
  match: {
    requires: [[t("genre", "cinematic"), t("genre", "orchestral"), t("genre", "film"), t("genre", "score"), t("aesthetic", "cinematic"), t("aesthetic", "orchestral"), t("ensemble", "orchestra"), t("word", "production_feel=cinematic"), t("word", "production_feel=orchestral")]],
    boosts: [{ slot: "word", term: "mood=epic" }, { slot: "word", term: "instrument=strings" }],
  },
  levels: {
    genre: { "identity.genre": kv("cinematic", 0.85, "orchestral writing in the film idiom") },
    subgenre: "unknown",
    tradition: "unknown",
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("orchestra", 0.85, "strings, brass, winds, percussion"),
      "arrangement.familyPriority": kv(["strings", "brass", "winds", "percussion", "keys"], 0.75, "strings first"),
      "sound.referenceInstruments": kv(["string orchestra", "french horns", "low brass", "timpani", "harp", "celesta"], 0.75, "the orchestra"),
    },
    rhythmic: {
      "groove.family": kv("straight", 0.6, "straight; ostinati in the action cues"),
      "groove.subdivision": kv("quarter", 0.4, "long values; ostinati in eighths"),
      "groove.fillFrequency": kv("rare", 0.6, "no fills; swells and hits"),
      "groove.tempoBehavior": kv("rubato_tolerant", 0.6, "the tempo breathes"),
      "bass.attackPosition": kv("sustained", 0.7, "held low strings and brass"),
      "bass.motion": kv("pedal", 0.6, "pedal points"),
      "keys.chordRhythm": kv("sustained", 0.5, "held"),
    },
    harmonic: {
      "harmony.extensions": kv("triads", 0.6, "triads with suspensions and added tones; sevenths sparingly"),
      "harmony.modalFlavour": kv("modal_mixture_lydian_aeolian", 0.5, "modal mixture, lydian and aeolian colour"),
      "harmony.harmonicRhythm": kv("slow", 0.65, "long harmonies"),
      "harmony.parallelism": kv("tolerated", 0.55, "planed triads and parallel octaves in doublings"),
      "harmony.passingChords": kv("sparse", 0.5, "few"),
      "keys.voicingWidth": kv("wide", 0.8, "wide spacing across the orchestra"),
      "melodic.phraseLength": kv("long", 0.6, "long phrases"),
      "melodic.callAndResponse": kv("occasional", 0.5, "between choirs of the orchestra"),
      "melodic.hookExpectation": kv(false, 0.5, "a theme, not a hook"),
    },
    orchestration: {
      "strings.role": kv("tutti", 0.8, "the string body carries the writing"),
      "strings.articulation": kv("legato", 0.7, "legato by default; tremolo and spiccato for tension"),
      "strings.register": kv("wide", 0.8, "the whole range"),
      "strings.entry": kv("throughout", 0.7, "always present"),
      "brassWinds.role": kv("section", 0.75, "brass and winds as sections"),
      "brassWinds.articulation": kv("marcato", 0.55, "marcato hits, legato lines"),
      "keys.role": kv("bed", 0.4, "piano or harp as colour"),
      "arrangement.doubling": kv("orchestral", 0.9, "orchestral doubling"),
      "arrangement.textureLadder": kv({ intro: "duo", verse: "bed", prechorus: "full", chorus: "tutti", bridge: "bed", outro: "duo" }, 0.6, "a solo opens; the tutti is the climax"),
      "arrangement.silenceConventions": kv(["a solo instrument opens", "the tutti releases to a single held note"], 0.6, "how the orchestra uses silence"),
      "arrangement.transitionLanguage": kv("swells_and_builds", 0.85, "swells, rolls and builds"),
      "arrangement.development": kv("dynamic_arc", 0.8, "a dynamic arc over the whole cue"),
      "arrangement.phraseBehavior": kv("motivic", 0.75, "motivic development"),
      "arrangement.arcTemplate": kv("cinematic_swell", 0.9, "the swell arc"),
      "arrangement.registerTendency": kv("wide", 0.7, "wide"),
    },
    aesthetic: {
      "sound.aesthetic": [
        kv("cinematic", 0.7, "the film dress: orchestra with percussion and hybrid elements"),
        kv("orchestral", 0.5, "the concert dress: no kit, no synths"),
      ],
      "sound.instrumentation": kv("orchestral", 0.95, "orchestral"),
      "sound.roomSize": kv("hall", 0.85, "a scoring stage"),
      "sound.saturation": kv("clean", 0.7, "clean"),
      "sound.stereo": kv("wide", 0.75, "the width of the stage"),
    },
    performance: {
      "performance.articulationLanguage": kv("legato", 0.7, "legato"),
      "performance.dynamics": kv("wide", 0.9, "pp to ff"),
      "performance.articulationVocabulary": kv(["legato", "tremolo", "staccato", "marcato", "pizzicato", "swell"], 0.7, "the orchestral vocabulary"),
      "performance.humanise": kv("natural", 0.7, "an ensemble, not a grid"),
      "melodic.ornamentation": kv("light", 0.5, "light"),
      "groove.microtiming": kv("loose", 0.5, "ensemble spread"),
    },
  },
  basis: "common practice of orchestral film writing; B-09 specialist, not measured",
  coverage: "general_practice",
};
