import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const rock: StyleKnowledgeEntry = {
  id: "rock",
  label: { en: "rock (guitar band)", he: "רוק (להקת גיטרות)" },
  match: {
    requires: [[t("genre", "rock"), t("genre", "punk"), t("genre", "metal"), t("genre", "grunge"), t("genre", "indie")]],
    boosts: [{ slot: "word", term: "instrument=guitar" }, { slot: "aesthetic", term: "raw" }, { slot: "aesthetic", term: "raw_band" }],
  },
  levels: {
    genre: { "identity.genre": kv("rock", 0.9, "the brief names it") },
    subgenre: "unknown",
    tradition: "unknown",
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("guitar_band", 0.8, "guitars, bass, kit, sometimes keys"),
      "arrangement.familyPriority": kv(["drums", "bass", "guitar", "keys"], 0.7, "the band"),
      "sound.referenceInstruments": kv(["electric guitar", "electric bass", "drum kit", "organ or piano"], 0.7, "the instruments of the style"),
    },
    rhythmic: {
      "groove.family": kv("backbeat", 0.85, "a straight backbeat"),
      "groove.subdivision": kv("8th", 0.7, "driving eighths"),
      "groove.syncopation": kv(0.2, 0.4, "mostly on the beat"),
      "groove.fillFrequency": kv("moderate", 0.7, "fills at every section end"),
      "groove.kickSnareLanguage": kv("backbeat_2_and_4", 0.9, "snare on two and four"),
      "groove.tempoBehavior": kv("strict_grid", 0.5, "steady"),
      "bass.attackPosition": kv("on_the_beat", 0.7, "with the kick"),
      "bass.motion": kv("root_fifth", 0.6, "roots and fifths in eighths"),
      "bass.lockToKick": kv(true, 0.8, "locked"),
      "keys.chordRhythm": kv("pulsing", 0.5, "pulsing organ or piano when present"),
    },
    harmonic: {
      "harmony.extensions": kv("triads", 0.8, "power chords and triads"),
      "harmony.modalFlavour": kv("major_mixolydian_or_minor_pentatonic", 0.6, "the rock modes"),
      "harmony.harmonicRhythm": kv("moderate", 0.6, "a chord a bar, riff-based"),
      "harmony.parallelism": kv("characteristic", 0.85, "power chords are parallel fifths; that is the sound"),
      "harmony.passingChords": kv("sparse", 0.6, "few"),
      "keys.voicingWidth": kv("open", 0.6, "open voicings, power chords"),
      "melodic.phraseLength": kv("regular", 0.7, "four-bar phrases"),
      "melodic.callAndResponse": kv("occasional", 0.5, "guitar answers the voice"),
      "melodic.hookExpectation": kv(true, 0.8, "a riff or a chorus hook"),
    },
    orchestration: {
      "strings.role": kv("none", 0.6, "no strings by default"),
      "brassWinds.role": kv("none", 0.7, "no brass by default"),
      "keys.role": kv("comping", 0.5, "keys comp when present"),
      "arrangement.doubling": kv("octaves", 0.6, "doubled guitars, octave bass"),
      "arrangement.textureLadder": kv({ intro: "full", verse: "bed", prechorus: "full", chorus: "full", bridge: "bed", outro: "full" }, 0.55, "the band plays; verses thin the guitars"),
      "arrangement.silenceConventions": kv(["a breakdown verse with bass and drums only", "the guitars stop for the last pre-chorus bar"], 0.5, "how rock uses silence"),
      "arrangement.transitionLanguage": kv("drum_fills", 0.8, "a drum fill into every section"),
      "arrangement.development": kv("repetition", 0.6, "the riff repeats; the last chorus doubles"),
      "arrangement.phraseBehavior": kv("continuous", 0.55, "continuous"),
      "arrangement.arcTemplate": kv("band_steady", 0.75, "the band arc"),
    },
    aesthetic: {
      "sound.aesthetic": kv("raw_band", 0.7, "a band in a room"),
      "sound.instrumentation": kv("acoustic", 0.55, "played instruments, amplified"),
      "sound.roomSize": kv("medium", 0.5, "a live room"),
      "sound.saturation": kv("driven", 0.8, "driven amps"),
      "sound.stereo": kv("natural", 0.55, "guitars left and right, the rest centred"),
    },
    performance: {
      "performance.articulationLanguage": kv("accented", 0.65, "accented"),
      "performance.dynamics": kv("moderate", 0.55, "loud, with a quieter verse"),
      "performance.articulationVocabulary": kv(["palm_mute", "accent", "slide", "strum_down"], 0.6, "the guitar vocabulary"),
      "performance.humanise": kv("natural", 0.6, "played"),
      "melodic.ornamentation": kv("light", 0.5, "bends and slides"),
      "groove.microtiming": kv("on_top", 0.55, "on top of the beat"),
    },
  },
  basis: "common practice of the rock band record; B-09 specialist, not measured",
  coverage: "general_practice",
};
