import { kv, t, type StyleKnowledgeEntry } from "./schema";

export const singerSongwriterAcoustic: StyleKnowledgeEntry = {
  id: "singer_songwriter_acoustic",
  label: { en: "acoustic singer-songwriter", he: "זמר-יוצר אקוסטי" },
  match: {
    requires: [[t("genre", "singer_songwriter"), t("genre", "folk"), t("genre", "acoustic"), t("aesthetic", "acoustic"), t("word", "production_feel=acoustic")]],
    boosts: [{ slot: "word", term: "instrument=guitar" }, { slot: "ensemble", term: "solo" }, { slot: "aesthetic", term: "intimate" }],
  },
  levels: {
    genre: { "identity.genre": kv("acoustic", 0.85, "an acoustic song around one voice and one instrument") },
    subgenre: "unknown",
    tradition: "unknown",
    era: "unknown",
    ensemble: {
      "identity.ensembleType": kv("solo_or_small_acoustic", 0.75, "voice and guitar or piano, sometimes a small band"),
      "arrangement.familyPriority": kv(["guitar", "keys", "bass", "percussion", "strings"], 0.55, "the guitar or piano first; everything else optional"),
      "sound.referenceInstruments": kv(["steel-string acoustic guitar", "upright or felt piano", "brushed kit", "upright bass"], 0.55, "the instruments of the style"),
    },
    rhythmic: {
      "groove.family": kv("straight", 0.6, "straight strumming or fingerpicking"),
      "groove.subdivision": kv("8th", 0.6, "eighth-note strums"),
      "groove.fillFrequency": kv("rare", 0.7, "almost no fills"),
      "groove.tempoBehavior": kv("breathing", 0.5, "the tempo breathes with the singer"),
      "bass.attackPosition": kv("on_the_beat", 0.5, "simple"),
      "bass.motion": kv("roots", 0.55, "roots"),
      "keys.chordRhythm": kv("arpeggiated", 0.5, "broken chords under the voice"),
    },
    harmonic: {
      "harmony.extensions": kv("sevenths", 0.5, "add9 and sus colour from open strings"),
      "harmony.modalFlavour": kv("major", 0.4, "diatonic major, often with a mixolydian bVII"),
      "harmony.harmonicRhythm": kv("moderate", 0.55, "a chord a bar or two a bar"),
      "harmony.parallelism": kv("tolerated", 0.5, "guitar shapes move in parallel"),
      "harmony.passingChords": kv("sparse", 0.5, "few"),
      "keys.voicingWidth": kv("open", 0.6, "open guitar-like voicings"),
      "melodic.phraseLength": kv("regular", 0.6, "even phrases"),
      "melodic.callAndResponse": kv("none", 0.5, "no dialogue; the voice carries it"),
      "melodic.hookExpectation": kv(false, 0.4, "a refrain, not necessarily a hook"),
    },
    orchestration: {
      "arrangement.introFigure": kv("piano_motif", 0.55, "the accompanying instrument (a guitar here) states the tune's first phrase alone"),
      "arrangement.endingGesture": kv("held_final_chord", 0.6, "the last chord rings out"),
      "strings.role": kv("pad", 0.45, "if strings come, they pad late"),
      "strings.articulation": kv("legato", 0.7, "legato"),
      "strings.entry": kv("late", 0.5, "in the last chorus, if at all"),
      "brassWinds.role": kv("none", 0.7, "no brass"),
      "keys.role": kv("bed", 0.5, "a bed when present"),
      "arrangement.doubling": kv("none", 0.7, "nothing is doubled"),
      "arrangement.textureLadder": kv({ intro: "solo", verse: "duo", chorus: "bed", bridge: "duo", outro: "solo" }, 0.6, "one instrument opens; the texture never gets full"),
      "arrangement.silenceConventions": kv(["drums may never enter", "the first verse is voice and one instrument"], 0.65, "how the style uses silence"),
      "arrangement.transitionLanguage": kv("thin_build", 0.6, "a thin build, never a fill"),
      "arrangement.development": kv("additive", 0.55, "a second instrument joins for the second verse"),
      "arrangement.phraseBehavior": kv("continuous", 0.5, "continuous accompaniment"),
      "arrangement.arcTemplate": kv("intimate_ballad", 0.7, "intimate"),
    },
    aesthetic: {
      "sound.aesthetic": kv("intimate", 0.8, "close, small, real"),
      "sound.instrumentation": kv("acoustic", 0.85, "acoustic instruments"),
      "sound.roomSize": kv("small", 0.7, "a small room"),
      "sound.saturation": kv("warm", 0.6, "warm"),
      "sound.stereo": kv("natural", 0.7, "natural"),
    },
    performance: {
      "performance.articulationLanguage": kv("legato", 0.5, "connected"),
      "performance.dynamics": kv("moderate", 0.5, "the singer's range"),
      "performance.humanise": kv("loose", 0.6, "played freely"),
      "melodic.ornamentation": kv("light", 0.6, "light"),
      "groove.microtiming": kv("loose", 0.5, "not to a grid"),
    },
  },
  pulse: {
    writtenBpm: { min: 60, max: 125 },
    above: "half_time",
    below: "as_written",
    strategy: "steady_pulse",
    halfTimeStrategy: "half_time_feel",
    never: ["four_on_floor", "syncopated"],
    confidence: 0.65,
    why: "one player and a voice: the strum is the pulse and it breathes. A four-on-the-floor kick under a fingerpicked song is a reading nobody in this world would give.",
  },
  basis: "common practice of the acoustic singer-songwriter record; B-09 specialist, not measured",
  coverage: "general_practice",
};
