"""Validate a signed Beat This release before changing API canonical records."""
from __future__ import annotations

import argparse
import base64
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

import promote_modal

ACTIVATION_PATHS = {
    "artifacts/api-server/src/lib/beatThisPromotion.generated.ts",
    "services/beat-this-worker/release-attestation.json",
}


def verify_signature(record: dict, signature: str, public_key: str) -> None:
    try:
        signature_bytes = base64.b64decode(signature, validate=True)
    except ValueError as exc:
        raise ValueError("promotion signature is not base64") from exc
    if len(signature_bytes) != 64:
        raise ValueError("promotion signature is not Ed25519")
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        payload_path = root / "record.json"
        signature_path = root / "signature.bin"
        public_key_path = root / "public.pem"
        payload_path.write_text(promote_modal.canonical(record))
        signature_path.write_bytes(signature_bytes)
        public_key_path.write_text(public_key)
        result = subprocess.run(
            [
                "openssl", "pkeyutl", "-verify", "-pubin",
                "-inkey", str(public_key_path), "-rawin",
                "-in", str(payload_path), "-sigfile", str(signature_path),
            ],
            capture_output=True,
            check=False,
        )
    if result.returncode:
        raise ValueError("promotion signature does not match the public key")


def validate(
    bundle: object,
    public_key: str,
    evidence: dict,
    refresh: object,
    health: object,
) -> dict:
    promote_modal.validate_release_evidence(evidence)
    if (
        not isinstance(refresh, dict)
        or refresh.get("schemaVersion") != 1
        or refresh.get("provider") != "BEAT_THIS"
        or refresh.get("modalAppId") != evidence["modalAppId"]
        or refresh.get("modalDeploymentId") != evidence["modalDeploymentId"]
        or not isinstance(refresh.get("stoppedContainerIds"), list)
        or refresh.get("staleContainerIds") != []
    ):
        raise ValueError("container refresh proof does not match release evidence")
    if not isinstance(bundle, dict) or set(bundle) != {"record", "signature"}:
        raise ValueError("promotion bundle must contain exactly record and signature")
    record = bundle.get("record")
    signature = bundle.get("signature")
    if not isinstance(record, dict) or not isinstance(signature, str):
        raise ValueError("promotion bundle fields are invalid")
    expected_fields = {
        "provider": "BEAT_THIS",
        "modalAppId": evidence["modalAppId"],
        "modalDeploymentId": evidence["modalDeploymentId"],
        "modalFunctionId": evidence["modalFunctionId"],
        "modalImageId": evidence["modalImageId"],
        "endpointOrigin": evidence["endpointOrigin"],
        "sourceRevision": evidence["sourceRevision"],
        "sourceImageDigest": evidence["sourceImageDigest"],
        "releaseEvidenceSha256": promote_modal.release_evidence_sha256(evidence),
    }
    if any(record.get(key) != value for key, value in expected_fields.items()):
        raise ValueError("promotion record does not match captured release evidence")
    smoke_checkpoint = evidence["smokeEvidence"]["checkpoint"]["sha256"]
    if record.get("checkpointSha256") != smoke_checkpoint:
        raise ValueError("promotion checkpoint does not match real smoke evidence")
    promote_modal.verify_live_health(health, record)
    verify_signature(record, signature, public_key)
    return record


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as temporary:
        temporary.write(text)
        temporary.flush()
        os.fsync(temporary.fileno())
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)


def activate(
    bundle: dict,
    public_key: str,
    evidence: dict,
    refresh: dict,
    health: dict,
    api_output: Path,
    release_output: Path,
) -> None:
    _, generated, release_json = canonical_documents(
        bundle, public_key, evidence, refresh, health
    )
    atomic_write(api_output, generated)
    atomic_write(release_output, release_json)


def canonical_documents(
    bundle: dict,
    public_key: str,
    evidence: dict,
    refresh: dict,
    health: dict,
) -> tuple[dict, str, str]:
    record = validate(bundle, public_key, evidence, refresh, health)
    bundle_json = promote_modal.canonical(bundle)
    generated = (
        "/* Generated by the fail-closed Beat This release workflow. */\n"
        f"export const committedBeatThisPromotionBundle = {json.dumps(bundle_json)};\n"
        f"export const committedBeatThisPromotionPublicKey = {json.dumps(public_key)};\n"
    )
    release = {
        "schemaVersion": 1,
        "provider": "BEAT_THIS",
        "record": record,
        "signature": bundle["signature"],
        "publicKey": public_key,
        "containerRefresh": refresh,
        "smokeEvidence": evidence["smokeEvidence"],
        "liveHealth": health,
    }
    # Validate both complete documents before replacing either canonical file.
    if not re.fullmatch(r"[a-f0-9]{40}", record["sourceRevision"]):
        raise ValueError("release source revision is not immutable")
    release_json = promote_modal.canonical(release) + "\n"
    return record, generated, release_json


def verify_retained_activation(
    bundle: dict,
    public_key: str,
    evidence: dict,
    refresh: dict,
    health: dict,
    api_output: Path,
    release_output: Path,
    expected_source_revision: str,
) -> None:
    record, generated, release_json = canonical_documents(
        bundle, public_key, evidence, refresh, health
    )
    if record["sourceRevision"] != expected_source_revision:
        raise ValueError("retained activation source revision changed")
    if api_output.read_text() != generated:
        raise ValueError(
            "activation branch generated bundle or public key changed"
        )
    if release_output.read_text() != release_json:
        raise ValueError("activation branch release attestation changed")


def git_output(repository: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repository,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        raise ValueError("activation branch Git lineage is invalid")
    return result.stdout.strip()


def verify_activation_commit(
    repository: Path, expected_source_revision: str
) -> None:
    repository = repository.resolve()
    head = git_output(repository, "rev-parse", "HEAD")
    parent = git_output(repository, "rev-parse", "HEAD^")
    count = git_output(
        repository,
        "rev-list",
        "--count",
        f"{expected_source_revision}..{head}",
    )
    if parent != expected_source_revision or count != "1":
        raise ValueError(
            "activation branch is not the original source child commit"
        )
    changed = set(
        filter(
            None,
            git_output(
                repository,
                "diff",
                "--name-only",
                expected_source_revision,
                head,
                "--",
            ).splitlines(),
        )
    )
    if changed != ACTIVATION_PATHS:
        raise ValueError(
            "activation branch changed files outside the canonical records"
        )
    for relative in ACTIVATION_PATHS:
        path = repository / relative
        if not path.is_file() or path.is_symlink():
            raise ValueError(
                "activation branch canonical record is not a regular file"
            )


def authenticated_release_branch(
    evidence: dict, retained_run_branch: str
) -> str:
    run_branch = promote_modal.validate_release_branch(retained_run_branch)
    signed_branch = evidence.get("releaseBranch")
    if signed_branch is None:
        return run_branch
    signed_branch = promote_modal.validate_release_branch(signed_branch)
    if signed_branch != run_branch:
        raise ValueError(
            "signed release branch differs from retained workflow run"
        )
    return signed_branch


def main() -> None:
    parser = argparse.ArgumentParser()
    for name in (
        "bundle", "public-key", "evidence", "refresh", "health", "api-output",
        "release-output",
    ):
        parser.add_argument(f"--{name}", required=True)
    parser.add_argument("--verify-existing", action="store_true")
    parser.add_argument("--expected-source-revision")
    parser.add_argument("--repository")
    parser.add_argument("--retained-run-branch")
    parser.add_argument("--github-output")
    args = parser.parse_args()
    values = (
        json.loads(Path(args.bundle).read_text()),
        Path(args.public_key).read_text(),
        json.loads(Path(args.evidence).read_text()),
        json.loads(Path(args.refresh).read_text()),
        json.loads(Path(args.health).read_text()),
        Path(args.api_output),
        Path(args.release_output),
    )
    if args.verify_existing:
        if not args.expected_source_revision:
            parser.error(
                "--expected-source-revision is required with --verify-existing"
            )
        if not all((
            args.repository,
            args.retained_run_branch,
            args.github_output,
        )):
            parser.error(
                "--repository, --retained-run-branch, and --github-output "
                "are required with --verify-existing"
            )
        verify_activation_commit(
            Path(args.repository), args.expected_source_revision
        )
        verify_retained_activation(
            *values, args.expected_source_revision
        )
        release_branch = authenticated_release_branch(
            values[2], args.retained_run_branch
        )
        with Path(args.github_output).open("a") as output:
            output.write(f"base_branch={release_branch}\n")
    else:
        if any((
            args.expected_source_revision,
            args.repository,
            args.retained_run_branch,
            args.github_output,
        )):
            parser.error(
                "verification-only arguments require --verify-existing"
            )
        activate(*values)


if __name__ == "__main__":
    main()